name: NeatSeq_Flow
channels:
  - conda-forge
dependencies:
# Deps of Neatseq_Flow
  - python=3.6.5
  - pyyaml
  - bunch
  #Neatseq_Flow
  - pip:
    - git+https://github.com/bioinfo-core-BGU/neatseq-flow.git
    - git+https://github.com/bioinfo-core-BGU/neatseq-flow-modules.git
