name: NeatSeq_Flow
dependencies:
# Deps of Neatseq_Flow
  - python=2.7   # or 2.7
  - pyyaml
  - bunch
  #Neatseq_Flow
  - pip:
    - git+https://github.com/bioinfo-core-BGU/neatseq-flow.git
    - git+https://github.com/bioinfo-core-BGU/neatseq-flow-modules.git
