#from distutils.core import setup
from setuptools import find_packages, setup

setup(
    name                = 'NeatSeq-Flow-modules',
    version             = '1.1.0',
    author              = 'Menachem Sklarz',
    author_email        = 'sklarz@bgu.ac.il',
    maintainer          = 'Menachem Sklarz',
    maintainer_email    = 'sklarz@bgu.ac.il',
    url                 = 'http://neatseq-flow.readthedocs.io/projects/neatseq-flow-modules/en/latest/',
    description         = 'Shared modules and workflows for use with NeatSeq-Flow',
    license             = 'Creative Commons Attribution-Noncommercial-Share Alike license',
    long_description    =  open('README').read(),
    download_url        = 'https://github.com/bioinfo-core-BGU/neatseq-flow-modules',
    platforms           = ["POSIX","Windows"],
    packages            = [
                            'Modules.Annotation',
                            'Modules.Assembly',
                            'Modules.ChIP_seq',
                            'Modules.clustering',
                            'Modules.Liron.cgMLST_and_MLST_typing_module',
                            'Modules.Liron.Collect_results_module',
                            'Modules.Liron.Cutadapt_module',
                            'Modules.Liron.Gassst_module',
                            'Modules.Liron.Prokka_module',
                            'Modules.Liron.Roary_module',
                            'Modules.Liron.RSEM_module',
                            'Modules.Liron.Snippy_module',
                            'Modules.Liron.Trim_Galore_module',
                            'Modules.Liron',
                            'Modules.main_NSF_classes.Assembly',
                            'Modules.main_NSF_classes.ChIP_seq',
                            'Modules.main_NSF_classes.Generic',
                            'Modules.main_NSF_classes.IGVtools',
                            'Modules.main_NSF_classes.mapping',
                            'Modules.main_NSF_classes.preparing',
                            'Modules.main_NSF_classes.Reports',
                            'Modules.main_NSF_classes.RNA_seq',
                            'Modules.main_NSF_classes.searching',
                            'Modules.main_NSF_classes.UCSCtools',
                            'Modules.main_NSF_classes.variants',
                            'Modules.main_NSF_classes',
                            'Modules.mapping',
                            'Modules.metagenomics',
                            'Modules.microbiology',
                            'Modules.miscellaneous',
                            'Modules.QIIME',
                            'Modules.Reports',
                            'Modules.searching',
                            'Modules.Transcriptomics',
                            'Modules.UCSCtools',
                            'Modules.variants'],
    data_files          = [('Workflows',['Workflows/Assembly_Indexing_mapping.yaml',
                                        'Workflows/BLAST_db.yaml',
                                        'Workflows/BLAST_fasta.yaml',
                                        'Workflows/ChIP_seq_bowtie2.yaml',
                                        'Workflows/Clustering.yaml',
                                        'Workflows/Metagenomics.yaml',
                                        'Workflows/parameter_set_QIIME/qiime1_mapping.txt',
                                        'Workflows/parameter_set_QIIME/qiime1_params.txt',
                                        'Workflows/parameter_set_QIIME/QIIME_workflow.yaml',
                                        'Workflows/parameter_set_QIIME/sample_file_paired_small.nsfs',
                                        'Workflows/RNA_seq_reference.yaml',
                                        'Workflows/RNA_seq_Trinity.yaml',
                                        'Workflows/variant_calling.yaml']),
                            ('Workflows/Sample_sets',['Workflows/sample_sets/ChIP_tabular.nsfs',
                                                        'Workflows/sample_sets/Fasta.nsfs',
                                                        'Workflows/sample_sets/PE.nsfs',
                                                        'Workflows/sample_sets/PE_ChIP.nsfs',
                                                        'Workflows/sample_sets/PE_tabular.nsfs',
                                                        'Workflows/sample_sets/SE.nsfs',])],
    # install_requires    = [],
    classifiers         = [
                          'Development Status :: 4 - Beta',
                          'Environment :: Console',
                          'Intended Audience :: End Users',
                          'Intended Audience :: Developers',
                          'License :: OSI Approved :: Python Software Foundation License',
                          'Operating System :: Microsoft :: Windows',
                          'Operating System :: POSIX',
                          'Programming Language :: Python',
                          ],
    )
    

    
