---
title: "NeatSeq Flow Proteomics module Results"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    # fig.height: 10
    # fig.width:  10
    # mathjax: local
    #self_contained: FALSE
#runtime: shiny


params:
    opt: NA
    test2do: NA
    results: NA
    general: NA
    SE: NA
    SE_BatchRemoved: NA
    base_out_dir: NA
    Annotation: NA
    Annotation_flag: NA
    ORGANISM: ''
    KEGG_flag: FALSE
    ORGANISM_KEGG_flag: FALSE
    KEGG_KAAS_flag: FALSE
    GO_flag: FALSE
    GO2gene_MF: NA
    GO2name_MF: NA
    GO2gene_BP: NA
    GO2name_BP: NA
    GO2gene_CC: NA
    GO2name_CC: NA
---

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

## Parameters Used in This Analysis:
```{r echo = FALSE, error = TRUE, comment='', message = FALSE, warning = FALSE}
test2do = params$test2do
if (test2do=='LRT' | test2do=='GENERAL'){
    opt$CONTRAST = NA
}else{
    opt$CONTRAST = test2do
}

parameters_used = as.data.frame(x = unlist(opt),row.names = names(opt))
colnames(parameters_used)=c('values')
print.data.frame(parameters_used,right = F,quote = F)
```


```{r echo = FALSE, error = TRUE, comment='', message = FALSE, warning = FALSE}
#####################Functions################################

plotPCA<-function (object, intgroup = "condition", ntop = 500, returnData = FALSE) {
  if (ntop!='all'){
    rv <- genefilter::rowVars(assay(object))
    select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                       length(rv)))]
    pca <- prcomp(t(assay(object)[select, ]))
  }else{
    pca <- prcomp(t(assay(object)))
  }
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, 
                                               drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }else{
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2],PC3 = pca$x[, 3], group = group, 
                  intgroup.df, name = colnames(object))
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:3]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "group")) + 
    geom_point(size = 3) + xlab(paste0("PC1: ", round(percentVar[1] * 
                                                        100), "% variance")) + ylab(paste0("PC2: ", round(percentVar[2] * 
                                                                                                            100), "% variance")) + coord_fixed()
}


cluster_enricher<-function(clusters,num,Type,organism,universe,keyType,Ontology="BP",pvalueCutoff=0.05,pAdjustMethod='fdr',qvalueCutoff=0.05){
  res_red=unique(names(clusters))
  Genes=res_red[res_red  %in% names(clusters[clusters %in% num])]
  if (Type=="GO"){
    res=enrichGO(gene      = Genes,
                 OrgDb         = organism,
                 universe      = universe,
                 keytype       = keyType,
                 ont           = Ontology,
                 pAdjustMethod = pAdjustMethod,
                 pvalueCutoff  = pvalueCutoff,
                 qvalueCutoff  = qvalueCutoff)
  }else{
    res=enrichKEGG(gene          = Genes, 
                   organism      = organism,
                   pAdjustMethod = pAdjustMethod,
                   pvalueCutoff  = pvalueCutoff,
                   qvalueCutoff  = qvalueCutoff,
                   universe      = universe,
                   keyType       = keyType,  
                   minGSSize     = 0,
                   maxGSSize     = length(res_red))
    
    
    
  }
  return(res)
}


clusters_enricher=function(outDir, clusters,Type,organism,universe,keyType,file_name,Ontology="BP",pvalueCutoff=0.05,pAdjustMethod='fdr',qvalueCutoff=0.05,maxCategory=1000){
    allRes=list()
    original_allRes=list()
    cluster_names=list()
    count=1
    for (i in sort(unique(clusters))){
        temp=cluster_enricher(clusters,c(i),Type,organism,universe,keyType,Ontology,pvalueCutoff,pAdjustMethod,qvalueCutoff)
        if (length(temp)>0){
          allRes[count]<-temp
          cluster_names[count]=i
          count=count+1
        }
    } 
    names(allRes)=cluster_names
    allRes=clusterProfiler::merge_result(enrichResultList =allRes)
    allRes@fun<-"enrichGO"
    write.csv(x = allRes@compareClusterResult,
            file =file.path(outDir,paste(file_name,'.csv',collapse = "")) ,
            quote = TRUE,
            row.names = TRUE)
            
    Enrichment_table  = datatable(allRes@compareClusterResult,
                                  caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',
                                                                            'Table: ', 
                                                                            htmltools::em(paste("This Table is of",paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse  = ' ')))
                                                                    ),
                                  options = list(keys = TRUE ,
                                                 scrollX = TRUE,
                                                 fixedHeader = FALSE,
                                                 fixedColumns = TRUE,
                                                 pageLength = 5,
                                                 scrollY = 300,
                                                 orderClasses=TRUE,
                                                 autoWidth = TRUE,
                                                 scroller = TRUE,
                                                 dom = 'Bfrtip',
                                                 buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                                                 deferRender = TRUE),
                                  class = 'cell-border stripe',
                                  filter = 'top',
                                  extensions = c('Buttons','FixedColumns','FixedHeader','KeyTable','Scroller'))
    original_allRes = allRes
    Simplify_title = c()
    if (dim(allRes@compareClusterResult)[1]>0){
        if (Type=="GO"){
            allRes@fun<-"enrichGO"
            temp_allRes<-try(clusterProfiler::simplify(allRes, cutoff=0.7, by="p.adjust", select_fun=min),silent = T)
            if (!inherits(temp_allRes,"try-error")){
                Simplify_title = list(htmltools::h6('*Simplify:  Redundant GO Terms Were Removed From the Figure, Showing Only the Most Significant Among Very Similar (>0.7) GO Terms; For more information see GOSemSim and clusterProfiler R packages'))
                allRes=temp_allRes
                file_name=paste("Simplify",file_name,collapse = "_")
                write.csv(x = allRes@compareClusterResult,file =file.path(outDir,paste(file_name,'.csv',sep='',collapse = "")) ,quote = FALSE,row.names = TRUE)
            }
        }else{
            allRes@fun<-"enrichKEGG"
        }
        if (dim(allRes@compareClusterResult)[1]>50){
            font.size=4
        }else{
            font.size=9
        }

        if (dim(allRes@compareClusterResult)[1]>0){
            # cat(sprintf("<h4>%s</h4>", paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ") ))
            fig_filename = file.path(outDir,paste(file_name,".pdf",sep='',collapse = ""))
            fig = enrichplot::dotplot(allRes,x=allRes@compareClusterResult$Cluster,showCategory=maxCategory,font.size =font.size)
            ggplot2::ggsave(filename = fig_filename ,fig,dpi = 600,device = "pdf",width = 20,height = 20)
            
            plotly_fig<-try(plotly::ggplotly(fig,dynamicTicks = T),silent = T)
            
            if (inherits(plotly_fig,"try-error")){
                fig_filename = file.path(outDir,paste(file_name,".png",sep='',collapse = ""))
                ggplot2::ggsave(filename = fig_filename,fig ,width = 6.99, height =6.99, units = "in")
                link = xfun::embed_file(path = fig_filename ,name = '',text = '' )
                link$name='img'
                link$attribs$src = link$attribs$href
                link$attribs$href = NULL
                plotly_fig = htmltools::img(link,alt = '')
            }
            grid::grid.newpage()
            return(list(original_allRes,list(htmltools::h4(paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ")),plotly_fig,Simplify_title,Enrichment_table)))
        }
    }
    
     return(list(original_allRes,list(htmltools::h4(paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ")))))
}


General_Enrichment_Test<-function(clusters,num,TERM2NAME,TERM2GENE,pAdjustMethod='fdr',pvalueCutoff=0.05){
  res_red=unique(TERM2GENE[,2])
  Genes=res_red[res_red  %in% names(clusters[clusters %in% num])]
  
  res=enricher(Genes, TERM2GENE=TERM2GENE, 
               TERM2NAME=TERM2NAME,
               minGSSize     = 0,
               maxGSSize     = length(res_red),
               pAdjustMethod = pAdjustMethod,
               pvalueCutoff  = pvalueCutoff
  ) 
  
  return(res)
}


generat_urls<-function(allRes,gene2ko){
  temp_table=allRes@compareClusterResult
  temp_table$URL=apply(X = temp_table,MARGIN = 1,FUN = function(x) paste(c("http://www.kegg.jp/kegg-bin/show_pathway?",stringi::stri_replace_all(str = x["ID"],replacement = "",regex = "path:",collapse = ""),"/", paste(sapply( unlist(stringi::stri_split(str = x["geneID"],regex = "/")),FUN = function(x) gene2ko[gene2ko$V1==x,"V2"]),collapse = "+") ),collapse = ""))
  allRes@compareClusterResult=temp_table
  return(allRes)
}


Clusters_Enrichment_Test=function(outDir,clusters,TERM2NAME,TERM2GENE,file_name,Type,pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE,maxCategory=1000){
    allRes=list()
    original_allRes = list()
    cluster_names=list()
    count=1
    for (i in sort(unique(clusters))){
        temp=General_Enrichment_Test(clusters,c(i),TERM2NAME,TERM2GENE,pAdjustMethod,pvalueCutoff )
        if (length(temp)>0){
          allRes[count]<-temp
          cluster_names[count]=i
          count=count+1
        }
    } 
    names(allRes)=cluster_names
    allRes=clusterProfiler::merge_result(enrichResultList =allRes)
    if (Type=="KO"){
        allRes<-generat_urls(allRes,gene2ko)
    }
    write.csv(x = allRes@compareClusterResult,
            file =file.path(outDir,paste(file_name,'.csv',collapse = "")) ,
            quote = TRUE,
            row.names = TRUE)
            
    Enrichment_table  = datatable(allRes@compareClusterResult,
                                  caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',
                                                                            'Table: ', 
                                                                            htmltools::em(paste("This Table is of",paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse  = ' ')))
                                                                    ),
                                  options = list(keys = TRUE ,
                                                 scrollX = TRUE,
                                                 fixedHeader = FALSE,
                                                 fixedColumns = TRUE,
                                                 pageLength = 5,
                                                 scrollY = 300,
                                                 orderClasses=TRUE,
                                                 autoWidth = TRUE,
                                                 scroller = TRUE,
                                                 dom = 'Bfrtip',
                                                 buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                                                 deferRender = TRUE),
                                  class = 'cell-border stripe',
                                  filter = 'top',
                                  extensions = c('Buttons','FixedColumns','FixedHeader','KeyTable','Scroller'))

    original_allRes = allRes
    Simplify_title = c()
    if (Type=="GO"){
        allRes@fun<-"enrichGO"
        temp_allRes<-try(clusterProfiler::simplify(allRes, cutoff=0.7, by="p.adjust", select_fun=min),silent = T)
        if (!inherits(temp_allRes,"try-error")){
            Simplify_title = list(htmltools::h6('*Simplify:  Redundant GO Terms Were Removed From the Figure, Showing Only the Most Significant Among Very Similar (>0.7) GO Terms; For more information see GOSemSim and clusterProfiler R packages'))
            allRes=temp_allRes
            file_name=paste("Simplify",file_name,collapse = "_")
            write.csv(x = allRes@compareClusterResult,file =file.path(outDir,paste(file_name,'.csv',sep='',collapse = "")) ,quote = FALSE,row.names = TRUE)
        }
    }else{
        allRes@fun<-"enrichKEGG"
    }
    if (dim(allRes@compareClusterResult)[1]>50){
        font.size=4
    }else{
        font.size=9
    }

    if (dim(allRes@compareClusterResult)[1]>0){
        # cat(sprintf("<h4>%s</h4>", paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ") ))
        saveRDS(allRes,file=file.path(outDir,paste(file_name,".rds",sep='',collapse = "")))
        fig_filename = file.path(outDir,paste(file_name,".pdf",sep='',collapse = ""))
        fig = enrichplot::dotplot(allRes,showCategory=maxCategory,font.size =font.size)
        ggplot2::ggsave(filename = fig_filename,fig ,dpi = 600,device = "pdf",width = 20,height = 20)
        plotly_fig<-try(plotly::ggplotly(fig,dynamicTicks = T),silent = T)
        
        if (inherits(plotly_fig,"try-error")){
            fig_filename = file.path(outDir,paste(file_name,".png",sep='',collapse = ""))
            ggplot2::ggsave(filename = fig_filename,fig ,width = 6.99, height =6.99, units = "in")
            link = xfun::embed_file(path = fig_filename ,name = '',text = '' )
            link$name='img'
            link$attribs$src = link$attribs$href
            link$attribs$href = NULL
            plotly_fig = htmltools::img(link,alt = '')
        }
        grid::grid.newpage()
        return(list(original_allRes,list(htmltools::h4(paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ")),plotly_fig,Simplify_title,Enrichment_table)))
    }
    
    return(list(original_allRes,list(htmltools::h4(paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ")),Enrichment_table)))
}


plot_clusters<-function(clusters,vs_ano,color_group=c('Type','Time'),titles=c("Type","Time","Normalized counts"),split_by=c(),smooth=T,X_AXIS_ORDER=NA){
  plot_list  = list()
  title_list = list()
  count=1
  for (i in sort(unique(clusters))){
    Df=data.frame()
    genes=names(clusters[clusters==i])
    for (j in genes){
      if (length(split_by)>0){
        temp=subset.data.frame(x =vs_ano,,c(split_by,color_group,j))
        colnames(temp)=c("split_by","Type","Time","EXP")
        Df=rbind(Df,temp)
      }else{
        temp=subset.data.frame(x =vs_ano,,c(color_group,j))
        colnames(temp)=c("Type","Time","EXP")
        Df=rbind(Df,temp)
      }
    }
    if (color_group[1]==color_group[2]){
      Df$Type='Trend'
    }
    if (length(X_AXIS_ORDER)>1){
      Df$Time <-factor(Df$Time,levels=intersect(X_AXIS_ORDER,unique(Df$Time)))
    }
    if (length(split_by)>0){
      title_list[count]=list(c(i,length(genes)) ) 
      plot_list[count]=list(ggplot(data=Df, aes(x=Time, y=EXP, group=Type)) + 
                              facet_wrap(~split_by, ncol=1,scales = "free_y",strip.position = c("right"))+
                              theme(strip.text.y = element_text(size = 7, colour = "black"))+#,face="bold" ,angle = 90))+
                              #theme(strip.background = element_blank())+
                              ggtitle( paste(paste("Cluster ", i  ,sep="") ,length(genes) ,sep="\n")) +
                              #theme(plot.title = element_text(colour = "black", size = 12)) + 
                              theme(legend.position  ="none")+
                              xlab(titles[2]) +
                              ylab(titles[3]) +
                              theme(axis.title   = element_text(colour = "black", size = 10) )+
                              theme(legend.title = element_text(colour = "black", size = 10) )+
                              theme(legend.text  = element_text(colour = "black", size = 8) )+
                              theme(axis.text.y  = element_text(colour = "black", size = 6))+
                              theme(axis.text.x  = element_text(colour = "black", size = 6))+
                              theme(plot.margin  = unit(c(0.5,0.2,0.5,0.2),"cm")  )+
                              #scale_color_discrete(name=titles[1])+
                              #scale_linetype_manual(name=titles[1],values=c(1,5))+
                              scale_x_discrete(limits=unique(Df$Time),guide = guide_axis(n.dodge = 2))+
                              theme(legend.key.width =unit(3,"line")) 
                            #scale_y_continuous(breaks=c(seq(0,10,by=2)) )
      )
    }else{
      title_list[count]=list(c(i,length(genes)) ) 
      plot_list[count]=list(ggplot(data=Df, aes(x=Time, y=EXP, group=Type)) + 
                              ggtitle( paste(paste("Cluster ", i  ,sep="") ,length(genes) ,sep="\n")) +
                              #theme(plot.title = element_text(colour = "black", size = 12)) + 
                              theme(legend.position  ="none")+
                              xlab(titles[2]) +
                              ylab(titles[3]) +
                              theme(axis.title   = element_text(colour = "black", size = 10) )+
                              theme(legend.title = element_text(colour = "black", size = 10) )+
                              theme(legend.text  = element_text(colour = "black", size = 8) )+
                              theme(axis.text.y  = element_text(colour = "black", size = 6))+
                              theme(axis.text.x  = element_text(colour = "black", size = 6))+
                              theme(plot.margin  = unit(c(0.5,0.2,0.5,0.2),"cm")  )+
                              #scale_color_discrete(name=titles[1])+
                              #scale_linetype_manual(name=titles[1],values=c(1,5))+
                              scale_x_discrete(limits=unique(Df$Time),guide = guide_axis(n.dodge = 2))+
                              theme(legend.key.width = unit(3,"line")) 
                            #scale_y_continuous(breaks=c(seq(0,10,by=2)) )
      )
    }
    
    
    if (smooth){
      if ( (dim(Df)[1]<30000) && (length(unique(Df$Time))>3)){
        old_plot = plot_list[[count]] 
        res <- try( list(plot_list[[count]] + 
                           stat_smooth(method="loess",
                                       fullrange=F,
                                       size=0.5,
                                       span=1,
                                       aes(linetype=Type,color=Type)) ),
                    silent = T)
        if (inherits(res,"try-error")){
          plot_list[count]=list(old_plot +
                           stat_smooth(method='glm',
                                       formula = y ~ poly(x, length(unique(Df$Time))-1),
                                       fullrange=F,
                                       size=0.5,
                                       aes(linetype=Type,color=Type)) 
                                )
          # plot_list[count]=list(plot_list[[count]] + 
          # stat_smooth(method="loess", span = 0.1 ,fullrange=F, size=0.5 ,aes(linetype=Type,color=Type)) 
          # )
        }else{
          plot_list[count]=res
          
        }
      }else{
        plot_list[count]=list(plot_list[[count]]+
                                stat_smooth(method='glm',
                                            formula = y ~ poly(x, length(unique(Df$Time))-1),
                                            fullrange=F,
                                            size=0.5,
                                            aes(linetype=Type,color=Type)) 
        )
      }
      gp2=plot_list[count]
      res<-try(get_legend(gp2[[1]] + theme(legend.position  ="right")+guides(color=guide_legend(title=titles[1]),linetype=guide_legend(title=titles[1]))) ,silent = T)
      if (inherits(res,"try-error")){
        plot_list[count]=list(plot_list[[count]]+
                                stat_summary(fun.y=mean, geom="point", size = 3,aes(color=Type))+
                                stat_summary(fun.data = "mean_se", geom = "errorbar", width = .3,size = 1,aes(color=Type),show.legend = F)
        )
      }
    }else{
      plot_list[count]=list(plot_list[[count]]+
                              stat_summary(fun.y=mean, geom="line", size = 1.3,aes(linetype=Type,color=Type))+
                              stat_summary(fun.data = "mean_se", geom = "errorbar", width = .3,size = 1,aes(color=Type),show.legend = F)
      )
    }
    
    count=count+1  
  }
  
  # ml_plotly = sapply(X =c(1:length(plot_list)),
  # FUN = function(x) list(ggplotly(plot_list[[x]]) %>% 
  # style(text=paste(
  # paste("Cluster:",title_list[[x]][1],sep=" ") ,
  # paste("Number of Genes:",title_list[[x]][2],sep=" ") ,
  # sep = "<br />" ),
  # hoverinfo = "text")))
  
  # ml_plotly = subplot(c(ml_plotly),
  # nrows = ceiling(length(plot_list)/3),
  # titleX = T,
  # titleY  = F,
  # shareX = T,
  # shareY = F) %>%
  # layout(title='Clusters',legend = list(orientation = 'h', y = -0.2))
  gp2=plot_list[1]
  num_of_plots=length(plot_list)
  # grob_cols = 2
  # grob_rows = 2
  
  # if (num_of_plots <= 2) {
  #   grob_rows=1
  #   grob_cols=num_of_plots
  # } else if (num_of_plots <= 4) {
  #   grob_rows = grob_cols = 2
  # } else {
  #   grob_rows=2
  #   grob_cols=2
  # }
  if (sqrt(num_of_plots) > round(sqrt(num_of_plots))){
    grob_rows = round(sqrt(num_of_plots))+1
    grob_cols = grob_rows
  } else{
    grob_rows = round(sqrt(num_of_plots))
    grob_cols = grob_rows
  }
  
  if (color_group[1]==color_group[2]){
    ml<-marrangeGrob(plot_list, nrow=grob_rows, ncol=grob_cols, top=NULL)
  } else {
    legend <- get_legend(gp2[[1]] + theme(legend.position  ="right")+guides(color=guide_legend(title=titles[1]),linetype=guide_legend(title=titles[1])))
    ml<-marrangeGrob(plot_list, nrow=grob_rows, ncol=grob_cols,right=legend, top=NULL)
  }
  
  return(list(ml))#,ml_plotly))
}


plot_sheard_genes<-function(allRes,outDir,file_name){
    heatmaps=list()
    if (length(allRes)>1){
        for (cluster in unique(allRes$Cluster)){
            TEMP = na.omit(allRes[allRes$Cluster==cluster,])
            genes = unique(unlist(stringi::stri_split(paste(TEMP$geneID,sep = ,collapse = '/'),fixed = '/')))
            
            if ((length(TEMP$ID)>1) &&((length(genes)>1))){
                mat  = matrix(0, nrow = length(TEMP$ID), ncol = length(genes))
                rownames(mat) = TEMP$ID
                colnames(mat) = genes


                for (x in TEMP$ID){
                  for (y in genes){
                    mat[x,y] = length( unlist(intersect( unlist(stringi::stri_split(TEMP[TEMP$ID==x,'geneID'],fixed = '/')),y )))
                    
                  }
                }

                rownames(mat) = TEMP$Description
                
                if ((length(TEMP$ID)>20) || ((length(genes)>200))){
                    heat_map = pheatmap(mat = mat,cluster_rows = T,
                                        cluster_cols = T,
                                        silent = T,
                                        legend = F)
                
                }else{
                    if (length(unique(as.vector(mat)))==2 ){
                        color=colorRampPalette(c('white','pink'))(2)
                        mybreaks=NA
                    }else{
                        color=colorRampPalette(c('pink'))(1)
                        mybreaks=c(0,1)
                    }
                    heat_map = pheatmap(mat = mat,cluster_rows = T,
                            treeheight_col = 0,
                            treeheight_row = 0,
                            width = 5,
                            height =5,
                            cellheight = 10,
                            fontsize_row =5,
                            fontsize_col = 1,
                            main = paste('Cluster ',cluster),
                            border_color = 'white',
                            cluster_cols = T,
                            breaks = mybreaks,
                            filename = file.path(outDir,paste('Cluster',cluster,'_genes2term_',file_name,".pdf",collapse = "")),
                            color = color,
                            legend = F)
                         
                }
                write.csv(x = mat[heat_map$tree_row$order,heat_map$tree_col$order],
                      quote = T,
                      row.names = T,
                      file = file.path(outDir,paste('Cluster',cluster,'_genes2term_',file_name,".csv",collapse = "")))
        
            
                mat  = matrix(0, nrow = length(TEMP$ID), ncol = length(TEMP$ID))
                rownames(mat) = TEMP$ID
                colnames(mat) = TEMP$ID

                for (x in TEMP$ID){
                  for (y in TEMP$ID){
                    mat[x,y] =100*(2*length( unlist(intersect( unlist(stringi::stri_split(TEMP[TEMP$ID==x,'geneID'],fixed = '/')),unlist(stringi::stri_split(TEMP[TEMP$ID==y,'geneID'],fixed = '/'))))))/(length(unlist(stringi::stri_split(TEMP[TEMP$ID==x,'geneID'],fixed = '/'))) +  length(unlist(stringi::stri_split(TEMP[TEMP$ID==y,'geneID'],fixed = '/'))))
                    
                  }
                }

                rownames(mat) = TEMP$Description
                colnames(mat) = TEMP$Description
                if (length(unique(as.vector(mat)))>1 ){
                    color=colorRampPalette(rev(RColorBrewer::brewer.pal(n = 7, name ="RdYlBu") ))( 100)
                    mybreaks=seq(0,1,0.01)
                }else{
                    color=colorRampPalette(c('red'))(1)
                    mybreaks=c(0,1)
                }
                    
                if (length(TEMP$ID)>20){
                    heat_map = pheatmap(mat = mat,cluster_rows = T,
                                        main = paste('Cluster ',cluster),
                                        treeheight_col = 0,
                                        treeheight_row = 0,
                                        cluster_cols = T,
                                        silent = T,
                                        legend = T)
                
                }else{
                    heat_map = pheatmap(mat = mat,cluster_rows = T,
                                width = 5,
                                height =5,
                                treeheight_col = 0,
                                treeheight_row = 0,
                                breaks = mybreaks,
                                fontsize_row =5,
                                fontsize_col = 5,
                                main = paste('Cluster ',cluster),
                                border_color = 'white',
                                cluster_cols = T,
                                color = color,
                                filename = file.path(outDir,paste('Cluster',cluster,'_term2term_',file_name,".pdf",collapse = "")),
                                legend = T)
                }

                write.csv(x = mat[heat_map$tree_row$order,heat_map$tree_col$order],
                          quote = T,
                          row.names = T,
                          file = file.path(outDir,paste('Cluster',cluster,'_term2term_',file_name,".csv",collapse = "")))
                
                heatmap_title=htmltools::h4(paste(unlist(stringi::stri_split(str = paste('Cluster',cluster,file_name,' Terms Genes Overlap',collapse = ""),fixed='_')),collapse = " "))
                heatmaps = c(heatmaps ,list(heatmap_title))
                mat = mat[heat_map$tree_row$order,heat_map$tree_col$order]
                heatmaps = c(heatmaps ,list(plot_ly(z = mat,
                                                    x=colnames(mat),
                                                    y=rownames(mat),
                                                    colors = color,
                                                    type = "heatmap")
                                             )
                            )
            }
        }
        
    }
    return(heatmaps)
}


Run_click<-function(mat,click_path,outDir,HOMOGENEITY = 0.5){
      InputFile = file.path(outDir,'clickInput.orig')
      writeLines(text =  paste(dim(mat)[1],dim(mat)[2],sep = ' ' ),con = InputFile)
      write.table(x = mat,append = T,file = InputFile ,sep = '\t',col.names = F)
      lines=c()
      lines = c(lines,'DATA_TYPE ')
      lines = c(lines,'FP ')
      lines = c(lines,'INPUT_FILES_PREFIX ')
      lines = c(lines,file.path(outDir,'clickInput '))
      lines = c(lines,'OUTPUT_FILE_PREFIX ')
      lines = c(lines,file.path(outDir,'clickOutput '))
      lines = c(lines,'SIMILARITY_TYPE ')
      lines = c(lines,'CORRELATION ')
      lines = c(lines,'HOMOGENEITY ')
      lines = c(lines,as.character(HOMOGENEITY))
      writeLines(text =  lines,con = file.path(outDir,'params.txt'))
      system(command = paste('chmod 777 ',InputFile,sep = ' ') )
      system(command = paste('chmod 777 ',file.path(outDir,'params.txt'),sep = ' ') )
      Sys.sleep(1)
      system(command = paste(click_path,file.path(outDir,'params.txt'),sep = ' '),wait = T )
      Sys.sleep(50)
      clusters = read.table(file = file.path(outDir,'clickOutput.res.sol'),sep = '\t',header = F,row.names = 1)
      clusters = setNames(unlist(as.list(clusters)), row.names(clusters))
      return(clusters)
}


convert_agregate<-function(df,index,subject,sep){
  l1=apply(X = df,MARGIN = 1,FUN = function(x) {
    m=as.data.frame( x = stringi::stri_split(str = x[subject],regex = sep),col.names = c("v1"))
    m["index"]<-x[index]
    return(m[c("index","v1")])
  })
  return(do.call(what = "rbind",args = l1) )
}


create_gene2kegg <- function(Annotation,useKO=F){
    kegg_id=''
    if (('KEGG' %in% stringr::str_to_upper(colnames(Annotation))) & (useKO==F) ){
      kegg_id =colnames(Annotation)[which('KEGG' == stringr::str_to_upper(colnames(Annotation)))[1]]
    }else{
      if ('KO' %in% stringr::str_to_upper(colnames(Annotation))){
        kegg_id =colnames(Annotation)[which('KO' == stringr::str_to_upper(colnames(Annotation)))[1]]
      }
    }
    if (kegg_id!=''){
        Annotation2USE=Annotation
        Annotation2USE['row.names'] = row.names(Annotation2USE)
        gene2Kegg = convert_agregate(Annotation2USE,'row.names',kegg_id,"/")
        colnames(gene2Kegg) = c('Gene','Kegg')
        info = KEGGREST::keggList(gene2Kegg$Kegg)
        kegg2names = data.frame(genes = names(info),info=info)
        return(c(gene2Kegg,kegg2names))
    }
    return(c('',''))
}

create_pathway_table <- function(outDir,up_reg,down_reg,Annotation,Pathway2name,Pathway2gene,show_cutoff=1,HTML=T,up_color='red',down_color='blue',useKO=T, Base_URL = "https://www.kegg.jp/kegg-bin/show_pathway?"){
  
  
  if ((length(down_reg)>0) || (length(up_reg)>0)){
    kegg_id=''
    if (('KEGG' %in% stringr::str_to_upper(colnames(Annotation))) & (useKO==F) ){
      kegg_id =colnames(Annotation)[which('KEGG' == stringr::str_to_upper(colnames(Annotation)))[1]]
    }else{
      if ('KO' %in% stringr::str_to_upper(colnames(Annotation))){
        kegg_id =colnames(Annotation)[which('KO' == stringr::str_to_upper(colnames(Annotation)))[1]]
      }
    }
    if (kegg_id!=''){
      Annotation2USE=Annotation
      Annotation2USE['row.names'] = row.names(Annotation2USE)
      gene2Kegg = convert_agregate(Annotation2USE,'row.names',kegg_id,"/")
      colnames(gene2Kegg) = c('Gene','Kegg')
      Pathway2gene = merge.data.frame(x =Pathway2gene,y = Pathway2name,by.x = colnames(Pathway2gene)[1] ,by.y = colnames(Pathway2name)[1])
      Pathway2gene[,1] = unlist(stringr::str_remove(string = Pathway2gene[,1],pattern = '.+:'))
      genes = c(up_reg,down_reg)
      Pathway2gene_filterd = Pathway2gene[Pathway2gene[,2] %in% genes,]
      colnames(Pathway2gene_filterd) = c('Pathway','Gene','Info')
      if (dim(Pathway2gene_filterd)[1]>0){
        Pathway2gene_filterd = merge.data.frame(x = Pathway2gene_filterd,y = gene2Kegg,by = 'Gene',all.x = T)
        colnames(Pathway2gene_filterd) = c('Gene','Pathway','Info','Kegg')
        UP = Pathway2gene_filterd[,'Gene'] %in% up_reg
        if (sum(UP)>0){
          Pathway2gene_filterd[UP,"URL"] = paste(Pathway2gene_filterd[UP,'Kegg'] , up_color ,sep = '%09,')     
        }
        DOWN = Pathway2gene_filterd[,'Gene'] %in% down_reg
        if (sum(DOWN)>0){
          Pathway2gene_filterd[DOWN,"URL"] = paste(Pathway2gene_filterd[DOWN,'Kegg'] , down_color ,sep = '%09,')     
        }
        Pathway2gene_count = aggregate.data.frame(x = Pathway2gene_filterd[,'Kegg'], by = list(Pathway2gene_filterd[,'Pathway']),FUN = function(x) length(unique(na.omit(x))))
        colnames(Pathway2gene_count) = c('Pathway','#KOs')
        Pathway = aggregate.data.frame(x =Pathway2gene_filterd ,
                                       by = list(Pathway2gene_filterd[,'Pathway']),
                                       FUN =function(x) paste(unique(na.omit(x)),sep = "/",collapse = "/"))
        Pathway['Base_URL'] = Base_URL
        
        Pathway[,'Kegg_URL'] = apply(X = Pathway,MARGIN = 1,FUN = function(x) paste(x['Base_URL'],x['Pathway'],sep = '',collapse = ''))
        Pathway[,'Kegg_URL'] = apply(X = Pathway,MARGIN = 1,FUN = function(x) paste(x['Kegg_URL'],x['URL'],sep = '/',collapse = '/'))
        Pathway[,'Kegg_URL'] = apply(X = Pathway,MARGIN = 1,FUN = function(x) paste(x['Kegg_URL'],"+multi",sep = '',collapse = ''))
        
        Pathway = merge.data.frame(x = Pathway,y = Pathway2gene_count,by = "Pathway" )
        row.names(Pathway) = Pathway$Pathway
        Pathway = Pathway[Pathway[,'#KOs']>=show_cutoff,c("Info","#KOs","Kegg_URL","Gene","Kegg")]
        Pathway =Pathway[order(Pathway[,'#KOs'],decreasing = T), ]
        write.table(Pathway,
                    file = file.path(outDir,paste('Kegg_Pathways_Links_With_Min_of',show_cutoff,'genes.tab', sep = '_')) ,
                    quote = F,
                    sep = "\t")
        if (HTML){
          Pathway[,'Kegg_URL'] = apply(X = Pathway,MARGIN = 1,FUN = function(x) paste('<a href="',x['Kegg_URL'],'" target="_blank">View Pathway</a>',sep = '',collapse = ''))
        }
        return(Pathway)  
      }else{
        return(data.frame())
      } 
    }else{
        return(data.frame())
    }
  }else{
    return(data.frame())
  }
}



plotCounts <- function (SE, gene, intgroup = "condition", normalized = TRUE, 
    transform = TRUE, main, xlab = "group", returnData = FALSE, 
    replaced = FALSE, pc, ...) 
{
    stopifnot(length(gene) == 1 & (is.character(gene) | (is.numeric(gene) & 
        (gene >= 1 & gene <= nrow(SE)))))
    if (!all(intgroup %in% names(colData(SE)))) 
        stop("all variables in 'intgroup' must be columns of colData")
    if (!returnData) {
        if (!all(sapply(intgroup, function(v) is(colData(SE)[[v]], 
            "factor")))) {
            stop("all variables in 'intgroup' should be factors, or choose returnData=TRUE and plot manually")
        }
    }
    if (missing(pc)) {
        pc <- if (transform) 
            0.5
        else 0
    }
    cnts <- assay(SE)[gene,]
    group <- if (length(intgroup) == 1) {
        colData(SE)[[intgroup]]
    }
    else if (length(intgroup) == 2) {
        lvls <- as.vector(t(outer(levels(colData(SE)[[intgroup[1]]]), 
            levels(colData(SE)[[intgroup[2]]]), function(x, 
                y) paste(x, y, sep = ":"))))
        droplevels(factor(apply(as.data.frame(colData(SE)[, 
            intgroup, drop = FALSE]), 1, paste, collapse = ":"), 
            levels = lvls))
    }
    else {
        factor(apply(as.data.frame(colData(SE)[, intgroup, drop = FALSE]), 
            1, paste, collapse = ":"))
    }
    data <- data.frame(count = cnts + pc, group = as.integer(group))
    logxy <- if (transform) 
        "y"
    else ""
    if (missing(main)) {
        main <- if (is.numeric(gene)) {
            rownames(dds)[gene]
        }
        else {
            gene
        }
    }
    ylab <-"Normalized Intensity"
    if (returnData) 
        return(data.frame(count = data$count, colData(SE)[intgroup]))
    plot(data$group + runif(ncol(SE), -0.05, 0.05), data$count, 
        xlim = c(0.5, max(data$group) + 0.5), log = logxy, xaxt = "n", 
        xlab = xlab, ylab = ylab, main = main, ...)
    axis(1, at = seq_along(levels(group)), levels(group))
}
#####################Functions-End################################

```

## Statistical Analysis:
```{r echo = FALSE, error = TRUE, comment='', message = FALSE, warning = FALSE}

    library("ggplot2")
    library("pheatmap")
    library("mclust")
    library("factoextra")
    library("cowplot")
    library("gridExtra")
    library("plotly")
    library("clusterProfiler")
    library("DT")
    library('DESeq2')
    
    theme_update(text = element_text(size=6))
    
    opt                = params$opt
    test2do            = params$test2do
    results            = params$results
    general            = params$general
    SE                 = params$SE
    base_out_dir       = params$base_out_dir
    SE_BatchRemoved    = params$SE_BatchRemoved
    Annotation         = params$Annotation
    Annotation_flag    = params$Annotation_flag
    ORGANISM           = params$ORGANISM
    KEGG_flag          = params$KEGG_flag
    ORGANISM_KEGG_flag = params$ORGANISM_KEGG_flag
    KEGG_KAAS_flag     = params$KEGG_KAAS_flag
    GO_flag            = params$GO_flag
    GO2gene_MF         = params$GO2gene_MF
    GO2name_MF         = params$GO2name_MF
    GO2gene_BP         = params$GO2gene_BP
    GO2name_BP         = params$GO2name_BP
    GO2gene_CC         = params$GO2gene_CC
    GO2name_CC         = params$GO2name_CC
    
    
    
    Pathway_show_cutoff = 1
    Pathway_up_color    = 'red'
    Pathway_down_color  = 'blue'
    
    if (!is.na(opt$Post_statistical_ALPHA)){
        FDR_PVAL_CUTOFF = opt$Post_statistical_ALPHA
    }else{
        FDR_PVAL_CUTOFF = opt$ALPHA
    }
    
    if (!is.na(opt$Post_statistical_FoldChange)){
        FC_CUTOFF = opt$Post_statistical_FoldChange #in linear scale
        FC_CUTOFF_log2 = log2(opt$Post_statistical_FoldChange) 
    }else{
        FC_CUTOFF = opt$FoldChange #in linear scale
        FC_CUTOFF_log2 = log2(opt$FoldChange) 
    }
     
    
    
    statistical_string = unlist(stringi::stri_split(str =  test2do,regex = ','))
        if (length(statistical_string)==3){
             htmltools::h4(sprintf("The statistical results of %s VS %s in %s:",statistical_string[2],statistical_string[3],statistical_string[1]))
        }else{
              htmltools::h4(sprintf("The statistical results of %s VS %s :",statistical_string[1],statistical_string[2]))
        }
    
    
    
        DESeqDataSet_Results = NA
        Normalized_counts = NA
        Normalized_counts_list=c()
        
        
        if (general) {
          test_name = 'GENERAL'
          opt$outDir=file.path(base_out_dir,'GENERAL')
          dir.create(opt$outDir, showWarnings = FALSE)
        }else {
            
            if (test2do=='No_DESIGN') {
              opt$outDir=file.path(base_out_dir,'No_DESIGN')
              dir.create(opt$outDir, showWarnings = FALSE)
              opt$CONTRAST=NA
              results = NA
            }else if (test2do=='only_clustering'){
              opt$outDir=file.path(base_out_dir,'Only_Clustering')
              dir.create(opt$outDir, showWarnings = FALSE)
              opt$CONTRAST=NA
              results = NA
            }else if (test2do=='No_Statistics'){
              opt$outDir=file.path(base_out_dir,'No_Statistics')
              dir.create(opt$outDir, showWarnings = FALSE)
              opt$CONTRAST=NA
              results = NA
            }else if (test2do=='Random_Forest'){
              library('randomForest')
              opt$outDir=file.path(base_out_dir,'Random_Forest')
              dir.create(opt$outDir, showWarnings = FALSE)
              opt$CONTRAST=NA
            }else{
                opt$CONTRAST=paste('condition',test2do,sep = ',')
                contrast_list = unlist(stringi::stri_split(str =  opt$CONTRAST,regex = ','))
                if (length(contrast_list)==2){
                      test_name = paste(contrast_list[1],contrast_list[2],sep = '_vs_')
                      contrast_list = as.list(contrast_list)
                }else{
                      test_name = paste(contrast_list[2],contrast_list[3],sep = '_vs_')
                }
                opt$outDir=file.path(base_out_dir,test_name)
                dir.create(opt$outDir, showWarnings = FALSE)
               if (!is.na(results)){
                 colnames(results)[colnames(results)=='AveExpr'] = 'baseMean'
                 results    = results[complete.cases(results), ]
                 Up_genes   = row.names( results[(results$log2FoldChange>FC_CUTOFF_log2) &  (results$padj<FDR_PVAL_CUTOFF),])
                 Down_genes = row.names( results[(results$log2FoldChange<FC_CUTOFF_log2) & (results$padj<FDR_PVAL_CUTOFF),])
                 cat(sprintf("%s Genes were analyzed, out of which:\nThe statistical Analysis found %s Up regulated genes\nThe statistical Analysis found %s Down regulated genes", nrow(results),length(Up_genes),length(Down_genes) ))
                 
               }
            }
    
        }

        ##################DeSeq-END####################################
```





```{r echo = FALSE, error = TRUE, comment='', message = FALSE, warning = FALSE,results='asis'}
        Normalized_counts_assay = NULL
        BatchRemoved = ''
        if (!is.null(SE)){
          Normalized_counts_assay = assay(SE)
          write.table(Normalized_counts_assay,
                        file = file.path(opt$outDir,paste(test_name,opt$NORMALIZATION_TYPE,BatchRemoved,'Normalized_Intensity.txt', sep = '_')) ,
                        quote = F,
                        sep = "\t")
        }
        
        if (!is.null(SE_BatchRemoved)){
          Normalized_counts_assay = assay(SE_BatchRemoved)
          BatchRemoved = 'Batch Removed'
          write.table(Normalized_counts_assay,
                        file = file.path(opt$outDir,paste(test_name,opt$NORMALIZATION_TYPE,BatchRemoved,'Normalized_Intensity.txt', sep = '_')) ,
                        quote = F,
                        sep = "\t")
        }
        ##################Print Normalized counts######################
        if (!is.null(Normalized_counts_assay)){
            
            if (!is.na(Annotation)) {
                  Normalized_counts_DATA = merge.data.frame(Normalized_counts_assay,Annotation,by="row.names",all.x = T,sort = F)
                  rownames(Normalized_counts_DATA) = Normalized_counts_DATA$Row.names
                  Normalized_counts_DATA$Row.names=NULL
                  Annotation_TEXT = ' and Annotation'
            }else{
                Normalized_counts_DATA = Normalized_counts_assay
                Annotation_TEXT = ''
            }
            cat(sprintf("<h4>%s</h4>",paste("The Next Table is of ",test_name,opt$NORMALIZATION_TYPE,BatchRemoved,'Normalized Intensity',Annotation_TEXT, sep = ' ')))
            Normalized_counts_table  =  datatable(Normalized_counts_DATA,
                                                  caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',
                                                                                            'Table: ', 
                                                                                            htmltools::em(paste("This Table is of ",test_name,opt$NORMALIZATION_TYPE,BatchRemoved,'Normalized Intensity',Annotation_TEXT, sep = ' '))
                                                                                    ),
                                                  options = list(keys = TRUE ,
                                                                 scrollX = TRUE,
                                                                 fixedHeader = FALSE,
                                                                 fixedColumns = TRUE,
                                                                 pageLength = 5,
                                                                 scrollY = 300,
                                                                 orderClasses=TRUE,
                                                                 autoWidth = TRUE,
                                                                 scroller = TRUE,
                                                                 dom = 'Bfrtip',
                                                                 buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                                                                 deferRender = TRUE),
                                                  class = 'cell-border stripe',
                                                  filter = 'top',
                                                  extensions = c('Buttons','FixedColumns','FixedHeader','KeyTable','Scroller'))
     
            
            htmltools::tagList(list(Normalized_counts_table))
        }
        ##################Print Normalized counts END#######################

        ##################Volcano plot and MA plot Vered##################

        if (!general){

            MA_Volcano_plot = NA
            MA_plot = NA
            Volcano_plot = NA 
            
            
            if (!is.na(results)){
    
                topT <- results
            
                    if (!is.na(opt$CONTRAST)){
                        cat(sprintf("<h4>%s</h4>",paste("Volcano Plot of ",test_name, sep = ' ')))
                        plotTitle = paste('Volcano Plot (', test_name, ')', sep="")
                        topT <- na.omit(as.data.frame(results))
                        fill = topT['padj']<FDR_PVAL_CUTOFF
                        fill[fill==F] = 'Not_SIG'
                        fill[fill == T & topT$log2FoldChange > FC_CUTOFF_log2] = 'UP'
                        fill[fill == T & topT$log2FoldChange < (-1)*FC_CUTOFF_log2] = 'DOWN'
                        volcano=ggplot(data = topT,mapping = aes(x=log2FoldChange, y=-log10(padj), fill=fill)) +
                            geom_point(size=1,pch=21)+
                            scale_fill_manual(values = c('blue','black','red'))+
                            geom_hline(yintercept =-log10(max(topT$padj[topT$padj<FDR_PVAL_CUTOFF], na.rm=TRUE)) ,size=0.2)+
                            geom_vline(xintercept = -1*FC_CUTOFF_log2,linetype="dotted",size=0.2)+
                            geom_vline(xintercept =  FC_CUTOFF_log2,linetype="dotted",size=0.2)+
                            coord_cartesian(xlim=c((-1)*max(abs(topT$log2FoldChange)),max(abs(topT$log2FoldChange))) )+
                            labs(x=bquote(~Log[2]~fold~change),y=bquote(~-log[10]~'FDR p-'~value))+
                            theme_light()+     
                            ggtitle(plotTitle)+
                            theme(plot.margin = margin(25,30,5,5),plot.title = element_text(size=9,hjust = 0.5,vjust=5,face = "bold"))+
                            theme(panel.grid = element_blank(),legend.position  ="none")
                        volcano+ggsave(filename = file.path(opt$outDir,paste(c(plotTitle,".pdf"),collapse ="")),width = 4,height = 4)
                        
                        grid::grid.newpage()
                        grid::grid.draw(volcano)
                        grid::grid.newpage()
                        # par(mar=c(5,5,5,5), cex=1.0, cex.main=1.4, cex.axis=1.4, cex.lab=1.4)
                        # #Adjusted P values (FDR Q values)
                        # with(topT, plot(log2FoldChange, -log10(padj), pch=20, main=plotTitle, cex=1.0, xlab=bquote(~Log[2]~fold~change), ylab=bquote(~-log[10]~'FDR p-'~value)))
                        # with(subset(topT, padj<FDR_PVAL_CUTOFF & abs(log2FoldChange)>FC_CUTOFF_log2), points(log2FoldChange, -log10(padj), pch=20, col="red", cex=0.5))
                        # #Add lines for absolute adjusted p-value and FC cutoffs 
                        # abline(v=-FC_CUTOFF_log2, col="black", lty=4, lwd=2.0)
                        # abline(v=FC_CUTOFF_log2, col="black", lty=4, lwd=2.0)
                        # if (length(topT$padj[topT$padj<FDR_PVAL_CUTOFF])>0){
                            # abline(h=-log10(max(topT$padj[topT$padj<FDR_PVAL_CUTOFF], na.rm=TRUE)), col="black", lty=4, lwd=FC_CUTOFF_log2)
                        # }
                        # Volcano_plot_ = recordPlot()
                        # cairo_pdf(file.path(opt$outDir,paste(c(plotTitle,".pdf"),collapse ="")))
                        # replayPlot(Volcano_plot_)
                        # trash = dev.off()
                        
                        # Volcano_plot=plot_ly(topT, x = ~log2FoldChange, y = ~-log10(padj),type='scatter', mode='markers',
                                             # showlegend = FALSE,
                                             # text=~paste(row.names(topT),
                                             # paste("FDR p− value:",padj,sep=" ") ,
                                             # paste("log2FoldChange:",log2FoldChange,sep=" ") ,
                                             # sep = "<br />" ),
                                             # hoverinfo = "text",
                                             # color = (~padj<FDR_PVAL_CUTOFF & abs(log2FoldChange)>FC_CUTOFF_log2),
                                             # colors= c('black','red'),
                                             # name=row.names(topT) ) %>%
                                     # add_markers() %>%
                                     # layout(title = paste("Volcano Plot of ",test_name, sep = ' '),
                                            # xaxis = list(title = 'Log2 Fold Change'),
                                            # yaxis = list(title = 'log10 FDR p− value')) 
                                            
                                            
                        # MA_plot=plot_ly(topT, x = ~baseMean , y = ~log2FoldChange,type='scatter', mode='markers',
                                        # showlegend = FALSE,
                                        # text=~paste(row.names(topT),
                                        # paste("FDR p− value:",padj,sep=" ") ,
                                        # paste("log2FoldChange:",log2FoldChange,sep=" ") ,
                                        # paste("Mean of Normalized Counts:",baseMean,sep=" ") ,
                                        # sep = "<br />" ),
                                        # hoverinfo = "text",
                                        # color = (~padj<FDR_PVAL_CUTOFF & abs(log2FoldChange)>FC_CUTOFF_log2),
                                        # colors= c('black','red'),
                                        # name=row.names(topT) ) %>%
                                # add_markers() %>%
                                # layout(title = paste("MA Plot of ",test_name, sep = ' '),
                                       # xaxis = list(title = 'Mean of Normalized Counts',type = "log"),
                                       # yaxis = list(title = 'Log2 Fold Change')) 
                        
                        # MA_Volcano_plot =   plot_ly(topT, x = ~log2FoldChange, z = ~-log10(padj), y = ~baseMean ,
                                                # showlegend = FALSE,
                                                # text=~paste(row.names(topT),
                                                            # paste("FDR p− value:",padj,sep=" ") ,
                                                            # paste("log2FoldChange:",log2FoldChange,sep=" ") ,
                                                            # paste("Mean of Normalized Counts:",baseMean,sep=" ") ,
                                                            # sep = "<br />" ),
                                                # hoverinfo = "text",
                                                # color = (~padj<FDR_PVAL_CUTOFF & abs(log2FoldChange)>FC_CUTOFF_log2),
                                                # colors= c('black','red'),
                                                # name=row.names(topT) ) %>%
                                        # add_markers() %>%
                                        # layout(title = paste("3D MA and Volcano Plots of ",test_name, sep = ' '),
                                               # scene = list(xaxis = list(title = 'Log2 Fold Change' ,showspikes = FALSE , autorange = T, showgrid = TRUE),
                                                            # zaxis = list(title = 'log10 FDR p− value', showspikes = FALSE ,autorange = T, showgrid = TRUE),
                                                            # yaxis = list(title = 'Mean of Normalized Counts', type = "log",showspikes = FALSE , autorange = T, showgrid = TRUE))) 
                    
                    }
                
                cat(sprintf("<h4>%s</h4>",paste("MA Plot of ",test_name, sep = ' ')))
                plotTitle = paste('MA Plot (', test_name, ')', sep="")
                ylimit=5
                MA=ggplot()+
                    geom_point(data = subset(topT,(padj>=FDR_PVAL_CUTOFF)&(abs(log2FoldChange)<=ylimit) ),mapping = aes(x=baseMean,y=log2FoldChange),size=0.5,pch=21,fill="black",colour="black")+
                    geom_point(data = subset(topT,(padj<FDR_PVAL_CUTOFF)&(log2FoldChange>FC_CUTOFF_log2)&(abs(log2FoldChange)<=ylimit) ),mapping = aes(x=baseMean,y=log2FoldChange),size=1,pch=21,fill="red",colour="black")+
                    geom_point(data = subset(topT,(padj<FDR_PVAL_CUTOFF)&(log2FoldChange<(-1)*FC_CUTOFF_log2)&(abs(log2FoldChange)<=ylimit) ),mapping = aes(x=baseMean,y=log2FoldChange),size=1,pch=21,fill="blue",colour="black")+
                    geom_point(data = subset(topT,(padj>=FDR_PVAL_CUTOFF)&(log2FoldChange>ylimit) ),mapping = aes(x=baseMean),y=ylimit,size=0.5,pch=24,fill="black",colour="black")+
                    geom_point(data = subset(topT,(padj>=FDR_PVAL_CUTOFF)&(log2FoldChange<=-1*ylimit) ),mapping = aes(x=baseMean),y=-1*ylimit,size=0.5,pch=25,fill="black",colour="black")+
                    geom_point(data = subset(topT,(padj<FDR_PVAL_CUTOFF)&(log2FoldChange>ylimit) ),mapping = aes(x=baseMean),y=ylimit,size=1,pch=24,fill="red",colour="black")+
                    geom_point(data = subset(topT,(padj<FDR_PVAL_CUTOFF)&(log2FoldChange<=-1*ylimit) ),mapping = aes(x=baseMean),y=-1*ylimit,size=1,pch=25,fill="blue",colour="black")+
                    scale_fill_manual(values = c('black','red'))+
                    geom_hline(yintercept = -1*FC_CUTOFF_log2,linetype="dotted",size=0.2)+
                    geom_hline(yintercept =  FC_CUTOFF_log2,linetype="dotted",size=0.2)+
                    #coord_cartesian(ylim=c(max(abs(topT$log2FoldChange)),-1*max(abs(topT$log2FoldChange))) )+
                    coord_cartesian(ylim=c(-1*ylimit,ylimit))+
                    labs(y=bquote(~Log[2]~fold~change),x='Mean Normalized Counts')+
                    theme_light()+     
                    ggtitle(plotTitle)+
                    scale_x_log10(labels = scales::comma)+
                    theme(plot.margin = margin(25,30,5,5),plot.title = element_text(size=9,hjust = 0.5,vjust=5,face = "bold"))+
                    theme(panel.grid = element_blank(),legend.position  ="none")
                MA+ggsave(filename = file.path(opt$outDir,paste(c(plotTitle,".pdf"),collapse ="")),width = 4,height = 4)
                grid::grid.newpage()
                grid::grid.draw(MA)
                grid::grid.newpage()
                        
                
                # plotMA(DESeqDataSet_Results, alpha=FDR_PVAL_CUTOFF, colNonSig = 'blue', ylim=c(-10,10), main=plotTitle)
                # abline(h=c(-FC_CUTOFF_log2,FC_CUTOFF_log2), col="red")
                # MA_plot_ = recordPlot()
                # trash = cairo_pdf(file.path(opt$outDir,paste(c(plotTitle,".pdf"),collapse ="")))
                # replayPlot(MA_plot_)
                # trash = dev.off()

            }
            
            
            # cat(sprintf("<h4>%s</h4>",paste("Volcano Plot of ",test_name, sep = ' ')))
            # grid::grid.newpage()
            # Volcano_plot
            # grid::grid.newpage()
            
            # cat(sprintf("<h4>%s</h4>",paste("MA Plot of ",test_name, sep = ' ')))
            # grid::grid.newpage()
            # MA_plot
            # grid::grid.newpage()

        
        
        }        
        
    ############################Original-PCA-START##############################################
        symbols = c("circle","square","diamond","cross","x","circle-open","diamond-open","square-open","star","star-diamond","triangle-up","star-triangle-up","star-square","hourglass","pentagon","circle-cross","square-cross","diamond-x","hexagram")
        
        cat(sprintf("<h2>%s</h2>", 'PCA Plots:'))

    ##################PCA-TOP500####################################
        if (!is.null(SE)){
            cat(sprintf("<h3>%s</h3>", 'PCA Plot Using Original Data:'))
            intgroup=c(opt$PCA_COLOR,opt$PCA_SHAPE,opt$PCA_SIZE)
            intgroup=intgroup[!is.na(intgroup)]
            PCA_data <- plotPCA(SE, intgroup=make.names(intgroup), returnData=TRUE,ntop=500)
            percentVar <- round(100 * attr(PCA_data, "percentVar"))

            if (is.na(opt$PCA_COLOR)){
              opt$PCA_COLOR='name'
            }

            if (is.na(opt$PCA_SHAPE)){
                PCA_data[,opt$PCA_COLOR] = factor(PCA_data[,opt$PCA_COLOR] , levels = unique(PCA_data[,opt$PCA_COLOR]))
                #PCA_data[,opt$PCA_SHAPE] = factor(PCA_data[,opt$PCA_SHAPE] , levels = unique(PCA_data[,opt$PCA_SHAPE]))
                write.csv(x = PCA_data ,file = file.path(opt$outDir,paste(c('TOP500_PCA',".csv"),collapse ="")))
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c('TOP500_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c('TOP500_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = symbols,
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA of the TOP 500 Most Variable Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot
            }else{
                PCA_data[,opt$PCA_COLOR] = factor(PCA_data[,opt$PCA_COLOR] , levels = unique(PCA_data[,opt$PCA_COLOR]))
                PCA_data[,opt$PCA_SHAPE] = factor(PCA_data[,opt$PCA_SHAPE] , levels = unique(PCA_data[,opt$PCA_SHAPE]))
                write.csv(x = PCA_data ,file = file.path(opt$outDir,paste(c('TOP500_PCA',".csv"),collapse ="")))
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c('TOP500_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c('TOP500_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("shape:",opt$PCA_SHAPE,get(make.names(opt$PCA_SHAPE)),sep=" ") ,
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = symbols,
                                               sizes = c(3,15),
                                               marker = list( line=list(color="black",width = 3),
                                                                sizemode = 'diameter',
                                                                color="black"),
                                               opacity = 0.8)%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = symbols,
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = symbols,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA of the TOP 500 Most Variable Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot
            }
        }
        ##################PCA-TOP500-END####################################

        # ##################PCA-ALL####################################
        if (!is.null(SE)){
            intgroup=c(opt$PCA_COLOR,opt$PCA_SHAPE,opt$PCA_SIZE)
            intgroup=intgroup[!is.na(intgroup)]
            PCA_data <- plotPCA(SE, intgroup=make.names(intgroup), returnData=TRUE,ntop='all')
            percentVar <- round(100 * attr(PCA_data, "percentVar"))

            if (is.na(opt$PCA_COLOR)){
                opt$PCA_COLOR='name'
            }

            if (is.na(opt$PCA_SHAPE)){
                PCA_data[,opt$PCA_COLOR] = factor(PCA_data[,opt$PCA_COLOR] , levels = unique(PCA_data[,opt$PCA_COLOR]))
                # PCA_data[,opt$PCA_SHAPE] = factor(PCA_data[,opt$PCA_SHAPE] , levels = unique(PCA_data[,opt$PCA_SHAPE]))
                write.csv(x = PCA_data ,file = file.path(opt$outDir,paste(c('ALL_PCA',".csv"),collapse ="")))
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c('ALL_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c('ALL_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot_ALL = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = symbols,
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA Using All Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot_ALL
            }else{
                PCA_data[,opt$PCA_COLOR] = factor(PCA_data[,opt$PCA_COLOR] , levels = unique(PCA_data[,opt$PCA_COLOR]))
                PCA_data[,opt$PCA_SHAPE] = factor(PCA_data[,opt$PCA_SHAPE] , levels = unique(PCA_data[,opt$PCA_SHAPE]))
                write.csv(x = PCA_data ,file = file.path(opt$outDir,paste(c('ALL_PCA',".csv"),collapse ="")))
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c('ALL_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
              
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c('ALL_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot_ALL = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("shape:",opt$PCA_SHAPE,get(make.names(opt$PCA_SHAPE)),sep=" ") ,
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = symbols,
                                               sizes = c(3,15),
                                               marker = list( line=list(color="black",width = 3),
                                                                sizemode = 'diameter',
                                                                color="black"),
                                               opacity = 0.8)%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = symbols,
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = symbols,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA Using All Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot_ALL
            }
        }
        # ##################PCA-END####################################
        
    ############################Original-PCA-ENDS##############################################




    ############################Batch-Effect-Corrected-PCA-START##############################################
    
        ##################PCA-TOP500####################################
         if (!is.null(SE_BatchRemoved)){
            cat(sprintf("<h3>%s</h3>", 'PCA Plot Using Batch Effect Corrected Data:'))
            extra_string="Batch_Effect_Corrected_"
            intgroup=c(opt$PCA_COLOR,opt$PCA_SHAPE,opt$PCA_SIZE)
            intgroup=intgroup[!is.na(intgroup)]
            PCA_data <- plotPCA(SE_BatchRemoved, intgroup=make.names(intgroup), returnData=TRUE,ntop=500)
            percentVar <- round(100 * attr(PCA_data, "percentVar"))

            if (is.na(opt$PCA_COLOR)){
              opt$PCA_COLOR='name'
            }

            if (is.na(opt$PCA_SHAPE)){
                PCA_data[,opt$PCA_COLOR] = factor(PCA_data[,opt$PCA_COLOR] , levels = unique(PCA_data[,opt$PCA_COLOR]))
                # PCA_data[,opt$PCA_SHAPE] = factor(PCA_data[,opt$PCA_SHAPE] , levels = unique(PCA_data[,opt$PCA_SHAPE]))
                write.csv(x = PCA_data ,file = file.path(opt$outDir,paste(c(extra_string,'TOP500_PCA',".csv"),collapse ="")))
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c(extra_string,'TOP500_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c(extra_string,'TOP500_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = symbols,
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA of the TOP 500 Most Variable Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot
            }else{
                PCA_data[,opt$PCA_COLOR] = factor(PCA_data[,opt$PCA_COLOR] , levels = unique(PCA_data[,opt$PCA_COLOR]))
                PCA_data[,opt$PCA_SHAPE] = factor(PCA_data[,opt$PCA_SHAPE] , levels = unique(PCA_data[,opt$PCA_SHAPE]))
                write.csv(x = PCA_data ,file = file.path(opt$outDir,paste(c(extra_string,'TOP500_PCA',".csv"),collapse ="")))
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c(extra_string,'TOP500_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c(extra_string,'TOP500_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("shape:",opt$PCA_SHAPE,get(make.names(opt$PCA_SHAPE)),sep=" ") ,
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = symbols,
                                               sizes = c(3,15),
                                               marker = list( line=list(color="black",width = 3),
                                                                sizemode = 'diameter',
                                                                color="black"),
                                               opacity = 0.8)%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = symbols,
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = symbols,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA of the TOP 500 Most Variable Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot
            }
        }
        ##################PCA-TOP500-END####################################

        # ##################PCA-ALL####################################
       if (!is.null(SE_BatchRemoved)){
            cat(sprintf("<h3>%s</h3>", 'PCA Plot Using Batch Effect Corrected Data:'))
            extra_string="Batch_Effect_Corrected_All_"
            intgroup=c(opt$PCA_COLOR,opt$PCA_SHAPE,opt$PCA_SIZE)
            intgroup=intgroup[!is.na(intgroup)]
            PCA_data <- plotPCA(SE_BatchRemoved, intgroup=make.names(intgroup), returnData=TRUE,ntop='all')
            percentVar <- round(100 * attr(PCA_data, "percentVar"))

            if (is.na(opt$PCA_COLOR)){
              opt$PCA_COLOR='name'
            }

            if (is.na(opt$PCA_SHAPE)){
                PCA_data[,opt$PCA_COLOR] = factor(PCA_data[,opt$PCA_COLOR] , levels = unique(PCA_data[,opt$PCA_COLOR]))
                # PCA_data[,opt$PCA_SHAPE] = factor(PCA_data[,opt$PCA_SHAPE] , levels = unique(PCA_data[,opt$PCA_SHAPE]))
                write.csv(x = PCA_data ,file = file.path(opt$outDir,paste(c(extra_string,'PCA',".csv"),collapse ="")))
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c(extra_string,'PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c(extra_string,'PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = symbols,
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA Using All Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot
            }else{
                PCA_data[,opt$PCA_COLOR] = factor(PCA_data[,opt$PCA_COLOR] , levels = unique(PCA_data[,opt$PCA_COLOR]))
                PCA_data[,opt$PCA_SHAPE] = factor(PCA_data[,opt$PCA_SHAPE] , levels = unique(PCA_data[,opt$PCA_SHAPE]))
                write.csv(x = PCA_data ,file = file.path(opt$outDir,paste(c(extra_string,'PCA',".csv"),collapse ="")))
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c(extra_string,'PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed() +
                    scale_y_continuous(expand = c(0.25,0.25))
                    
                ggsave(file.path(opt$outDir,paste(c(extra_string,'PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("shape:",opt$PCA_SHAPE,get(make.names(opt$PCA_SHAPE)),sep=" ") ,
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = symbols,
                                               sizes = c(3,15),
                                               marker = list( line=list(color="black",width = 3),
                                                                sizemode = 'diameter',
                                                                color="black"),
                                               opacity = 0.8)%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = symbols,
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = symbols,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA Using All Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot
            }
        }
        # ##################PCA-END####################################
        
    ############################Batch-Effect-Corrected-PCA-ENDS##############################################
      
     if (!is.null(SE_BatchRemoved)){
       Main_SE = SE_BatchRemoved
       Original_colData = as.data.frame(colData(Main_SE))
       Normalized_counts_assay = assay(Main_SE)
       coldata = Original_colData
     }else if (!is.null(SE)){
       Main_SE          = SE
       Original_colData = as.data.frame(colData(Main_SE))
       Normalized_counts_assay = assay(Main_SE)
       coldata = Original_colData
     }else{
       Main_SE          = NULL
       Original_colData = NULL
       coldata          = Original_colData
     }
    


    ##################Plot Counts################################    
        if (!is.null(Normalized_counts_assay)){
            plot_list = list()
            figure_count = 1
            if (!is.na(opt$GENES_PLOT)&&(!is.na(opt$X_AXIS)   )){
                intgroup=c(opt$X_AXIS,opt$GROUP)
                intgroup=intgroup[!is.na(intgroup)]
                X_AXIS=opt$X_AXIS
                if (is.na(opt$GROUP)){
                    GROUP=opt$X_AXIS
                }else{
                    GROUP=opt$GROUP
                }
                if (is.na(opt$SPLIT_BY)){
                    
                    for (gene in unlist(stringi::stri_split(str =  opt$GENES_PLOT,regex = ","))){
                        data=plotCounts(Main_SE, gene=gene,transform=F, intgroup=make.names(intgroup),returnData=TRUE)
                        p=ggplot(data, aes_string(make.names(X_AXIS), 'count',color=make.names(GROUP), group=make.names(GROUP))) +
                        ggtitle(paste("Gene ID : ",  gene  ,sep="\n")) +
                        theme(legend.position  ="none")+
                        geom_point(size=4)+
                        geom_boxplot() +
                        scale_shape_discrete(solid=F)+
                        geom_smooth(method="gam", fullrange=F, size=0.5)
                        ggsave(file.path(opt$outDir,paste(c('Count_plot_',gene,".pdf"),collapse ="")),p,dpi = 600, width = 6.99, height =6.99, units = "in")
                        plot_list[figure_count] <- list(p)
                        figure_count = figure_count + 1
                    }
                }else{
                    
                    for (gene in unlist(stringi::stri_split(str =  opt$GENES_PLOT,regex = ","))){
                        data=plotCounts(Main_SE, gene=gene,transform=F, intgroup=make.names(intgroup),returnData=TRUE)
                        p=ggplot(data, aes_string(make.names(X_AXIS), 'count',color=make.names(GROUP), group=make.names(GROUP))) +
                        ggtitle(paste("Gene ID : ",  gene  ,sep="\n")) +
                        theme(legend.position  ="none")+
                        facet_wrap(~opt$SPLIT_BY, ncol=1,scales = "free_y",strip.position = c("right"))+
                        geom_point(size=4)+
                        geom_boxplot() +
                        scale_shape_discrete(solid=F)+
                        stat_smooth(method="auto", fullrange=F, size=0.5)
                        ggsave(file.path(opt$outDir,paste(c('Count_plot_',gene,".pdf"),collapse ="")),p,dpi = 600, width = 6.99, height =6.99, units = "in")
                        plot_list[figure_count] <- list(p)
                        figure_count = figure_count + 1
                    }
                    
                }
            }
            if (length(plot_list)>0){
                cat(sprintf("<h2>%s</h2>", 'Count Plots:'))
                grid::grid.newpage()
                gp2 = plot_list[1]
                legend <- get_legend(gp2[[1]] + theme(legend.position  ="right"))
                grid::grid.draw(marrangeGrob(plot_list, nrow=1, ncol=2, top=legend))
                grid::grid.newpage()
            }
        }
        ##################Plot Counts-END#############################    

        ##################Clustering##################################   
        
        
        if (! general){
        
            cat(sprintf("<h2>%s</h2>", 'Clustering Analysis:'))
            main_plot_list  = list()
            up_reg   = c()
            down_reg = c()
            if (!is.na(results)){
                 sig.genes = c(Up_genes,Down_genes)
                 up_reg    = Up_genes   
                 down_reg  = Down_genes 
            }else if (!is.na(opt$significant_genes)){ 
                sig.genes = unlist(stringi::stri_split(str = opt$significant_genes,regex = ','))
                sig.genes = intersect(sig.genes,row.names(Normalized_counts_assay))
                #Normalized_counts_assay = Normalized_counts_assay[sig.genes,]
                cat(sprintf("<h3>%s</h3>", "NOTE: Clustering Analysis is done on the user defined significant genes !!!!"))
            }else if (!is.na(opt$significant_genes_file)) {
                sig.genes = read.delim(opt$significant_genes_file,header = F)
                sig.genes = intersect(sig.genes$V1,row.names(Normalized_counts_assay))
                
                #Normalized_counts_assay = Normalized_counts_assay[sig.genes,]
                cat(sprintf("<h3>%s</h3>", "NOTE: Clustering Analysis is done on the user defined significant genes !!!!")) 
            }else{
                sig.genes = rownames(Normalized_counts_assay)
                cat(sprintf("<h3>%s</h3>", 'NOTE: Clustering Analysis is done on all input genes !!!!'))
            }
             
    
            if (!is.na(opt$X_AXIS)){
    
                if (length(sig.genes)>0){
    
                    X_AXIS=opt$X_AXIS
                    if (is.na(opt$GROUP)){
                        GROUP=X_AXIS
                    }else{
                        GROUP=opt$GROUP
                    }
                    
                    if (is.na(opt$SPLIT_BY)){
                        if (!is.na(opt$CONTRAST)){
                            if (opt$SPLIT_BY_CONTRAST){
                                contrast_list_split = unlist(stringi::stri_split(str =  opt$CONTRAST,regex = ','))
                                if (length(contrast_list_split)==3){
                                    coldata = Original_colData[(Original_colData[contrast_list_split[1]]==contrast_list_split[2]) | (Original_colData[contrast_list_split[1]]==contrast_list_split[3]),]
                                    
                                    if (length(unique(coldata[,X_AXIS]))==1){
                                        if (length(unique(coldata[,GROUP]))>1){
                                            temp_X_AXIS = X_AXIS
                                            X_AXIS      = GROUP
                                            GROUP       = temp_X_AXIS
                                            cat(sprintf("<h4>%s%s%s%s%s</h4>",
                                                        'NOTE: Since there is only one group in "',
                                                        X_AXIS,
                                                        '" the X Axis will be replace with the grouping category "',
                                                        GROUP,
                                                        '"'))
                                        }
                                    }
                                }
                            }
                        }
                    }
                    
                    if (X_AXIS!=GROUP){
                        if (is.na(opt$SPLIT_BY)){
                            Normalized_counts_Annotated=merge(coldata[c(X_AXIS,GROUP)],t(Normalized_counts_assay),all.x = T ,by="row.names",sort=F)
                            SPLIT_BY=opt$SPLIT_BY
                            Normalized_counts_Annotated_mean=aggregate.data.frame(x = Normalized_counts_Annotated,by = c(Normalized_counts_Annotated[GROUP],Normalized_counts_Annotated[X_AXIS]),FUN = mean)
                            rownames(Normalized_counts_Annotated_mean)=paste(unlist(Normalized_counts_Annotated_mean[GROUP]),unlist(Normalized_counts_Annotated_mean[X_AXIS]))
                            Normalized_counts_Annotated_mean=Normalized_counts_Annotated_mean[order(rownames(Normalized_counts_Annotated_mean)),]
                            Normalized_counts_Annotated_mean$Row.names=NULL
                            Normalized_counts_Annotated_mean[unique(c(X_AXIS,GROUP))]=NULL
                            Normalized_counts_Annotated_mean[unique(c(X_AXIS,GROUP))]=NULL
                            
                            Heatmap_Normalized_counts_Annotated=Normalized_counts_Annotated
                            rownames(Heatmap_Normalized_counts_Annotated)=make.unique(paste(unlist(Heatmap_Normalized_counts_Annotated[GROUP]),
                                                                                            unlist(Heatmap_Normalized_counts_Annotated[X_AXIS]),
                                                                                            unlist(Heatmap_Normalized_counts_Annotated['Row.names'])),
                                                                                     sep=' ')
                            Heatmap_Normalized_counts_Annotated=Heatmap_Normalized_counts_Annotated[order(rownames(Heatmap_Normalized_counts_Annotated)),]
                            Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,GROUP))]=NULL
                            Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,GROUP))]=NULL
    
                        }else{
                            Normalized_counts_Annotated=merge(coldata[unique(c(X_AXIS,GROUP,opt$SPLIT_BY))],t(Normalized_counts_assay),all.x = T ,by="row.names",sort=F)
                            SPLIT_BY=unlist(as.list(unique(Normalized_counts_Annotated[opt$SPLIT_BY])))
                            Normalized_counts_Annotated_mean=aggregate.data.frame(x = Normalized_counts_Annotated,by = c(Normalized_counts_Annotated[GROUP],Normalized_counts_Annotated[X_AXIS]),FUN = mean)
                            rownames(Normalized_counts_Annotated_mean)=paste(unlist(Normalized_counts_Annotated_mean[GROUP]),unlist(Normalized_counts_Annotated_mean[X_AXIS]))
                            Normalized_counts_Annotated_mean=Normalized_counts_Annotated_mean[order(rownames(Normalized_counts_Annotated_mean)),]
                            SPLIT_BY_col=Normalized_counts_Annotated_mean[opt$SPLIT_BY]
                            Normalized_counts_Annotated_mean$Row.names=NULL
                            Normalized_counts_Annotated_mean[unique(c(X_AXIS,GROUP,opt$SPLIT_BY))]=NULL
                            Normalized_counts_Annotated_mean[unique(c(X_AXIS,GROUP,opt$SPLIT_BY))]=NULL
                            
                            Heatmap_Normalized_counts_Annotated=Normalized_counts_Annotated
                            rownames(Heatmap_Normalized_counts_Annotated)=make.unique(paste(unlist(Heatmap_Normalized_counts_Annotated[GROUP]),
                                                                                            unlist(Heatmap_Normalized_counts_Annotated[X_AXIS]),
                                                                                            unlist(Heatmap_Normalized_counts_Annotated['Row.names'])),
                                                                                     sep=' ')
                            Heatmap_Normalized_counts_Annotated=Heatmap_Normalized_counts_Annotated[order(rownames(Heatmap_Normalized_counts_Annotated)),]
                            Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,GROUP,opt$SPLIT_BY))]=NULL
                            Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,GROUP,opt$SPLIT_BY))]=NULL
                        }
    
                    }else{
                        if (is.na(opt$SPLIT_BY)){
                            Normalized_counts_Annotated=merge(coldata[c(X_AXIS)],t(Normalized_counts_assay),all.x = T,by="row.names",sort=F)
                            SPLIT_BY=opt$SPLIT_BY
                            Normalized_counts_Annotated_mean=aggregate.data.frame(x = Normalized_counts_Annotated,by = Normalized_counts_Annotated[X_AXIS],FUN = mean)
                            rownames(Normalized_counts_Annotated_mean)=unlist(Normalized_counts_Annotated_mean[X_AXIS])
                            Normalized_counts_Annotated_mean=Normalized_counts_Annotated_mean[order(rownames(Normalized_counts_Annotated_mean)),]
                            Normalized_counts_Annotated_mean[X_AXIS]=NULL
                            Normalized_counts_Annotated_mean[X_AXIS]=NULL
                            Normalized_counts_Annotated_mean$Row.names=NULL
                            
                            Heatmap_Normalized_counts_Annotated=Normalized_counts_Annotated
                            rownames(Heatmap_Normalized_counts_Annotated)=make.unique(as.character(paste(unlist(Heatmap_Normalized_counts_Annotated[X_AXIS]),
                                                                                                         unlist(Heatmap_Normalized_counts_Annotated['Row.names']))) ,
                                                                                     sep=' ')
                            Heatmap_Normalized_counts_Annotated=Heatmap_Normalized_counts_Annotated[order(rownames(Heatmap_Normalized_counts_Annotated)),]
                            Heatmap_Normalized_counts_Annotated[X_AXIS]=NULL
                            Heatmap_Normalized_counts_Annotated[X_AXIS]=NULL
    
                          
                        }else{
                            Normalized_counts_Annotated=merge(coldata[unique(c(X_AXIS,opt$SPLIT_BY))],t(Normalized_counts_assay),all.x = T,by="row.names",sort=F)
                            SPLIT_BY=unlist(as.list(unique(Normalized_counts_Annotated[opt$SPLIT_BY])))
                            Normalized_counts_Annotated_mean=aggregate.data.frame(x = Normalized_counts_Annotated,by = Normalized_counts_Annotated[X_AXIS],FUN = mean)
                            rownames(Normalized_counts_Annotated_mean)=unlist(Normalized_counts_Annotated_mean[X_AXIS])
                            Normalized_counts_Annotated_mean=Normalized_counts_Annotated_mean[order(rownames(Normalized_counts_Annotated_mean)),]
                            SPLIT_BY_col=Normalized_counts_Annotated_mean[opt$SPLIT_BY]
                            Normalized_counts_Annotated_mean[unique(c(X_AXIS,opt$SPLIT_BY))]=NULL
                            Normalized_counts_Annotated_mean[unique(c(X_AXIS,opt$SPLIT_BY))]=NULL
                            Normalized_counts_Annotated_mean$Row.names=NULL
                            
                            Heatmap_Normalized_counts_Annotated=Normalized_counts_Annotated
                            rownames(Heatmap_Normalized_counts_Annotated)=make.unique(as.character( paste( unlist(Heatmap_Normalized_counts_Annotated[X_AXIS]),
                                                                                                           unlist(Heatmap_Normalized_counts_Annotated['Row.names']))),
                                                                                     sep=' ')
                            Heatmap_Normalized_counts_Annotated=Heatmap_Normalized_counts_Annotated[order(rownames(Heatmap_Normalized_counts_Annotated)),]
                            Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,opt$SPLIT_BY))]=NULL
                            Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,opt$SPLIT_BY))]=NULL
                        }
                        
                        
                    }
    
                    Heatmap_Normalized_counts_Annotated=t(Heatmap_Normalized_counts_Annotated)
                    
                    for (SPLIT in SPLIT_BY){ 
                        if (is.na(SPLIT)){
                            SPLIT_Normalized_counts_Annotated_mean=t(Normalized_counts_Annotated_mean)
                            Heatmap_Normalized_counts_Annotated_mean=SPLIT_Normalized_counts_Annotated_mean
                            SPLIT=''
                            SPLIT_Normalized_counts_Annotated=Normalized_counts_Annotated
                        }else{
                            SPLIT_Normalized_counts_Annotated_mean=Normalized_counts_Annotated_mean
                            SPLIT_Normalized_counts_Annotated_mean=SPLIT_Normalized_counts_Annotated_mean[SPLIT_BY_col==SPLIT, ]
                            SPLIT_Normalized_counts_Annotated_mean=t(SPLIT_Normalized_counts_Annotated_mean)
                            Heatmap_Normalized_counts_Annotated_mean=t(Normalized_counts_Annotated_mean)
                            SPLIT_Normalized_counts_Annotated=Normalized_counts_Annotated[Normalized_counts_Annotated[opt$SPLIT_BY]==SPLIT, ]
                        }   
    
    
                        SPLIT_Normalized_counts_Annotated_mean=SPLIT_Normalized_counts_Annotated_mean[sig.genes,]
    
                        no_var=names(which( apply(SPLIT_Normalized_counts_Annotated_mean,MARGIN = 1,FUN = sd)==0))
                        if (length(no_var)>0){
                          SPLIT_Normalized_counts_Annotated_mean=SPLIT_Normalized_counts_Annotated_mean[!(row.names(SPLIT_Normalized_counts_Annotated_mean)  %in% no_var),]
                        }
    
                        
                        
                        
                        if (opt$stand){
                          SPLIT_Normalized_counts_Annotated_mean = t(scale(t(SPLIT_Normalized_counts_Annotated_mean)))
                          SPLIT_Normalized_counts_Annotated_mean = apply(SPLIT_Normalized_counts_Annotated_mean,
                                                                         MARGIN = c(1,2),
                                                                         FUN = function(x) round(x,digits = 5))
                        }
                        if (sum(duplicated(SPLIT_Normalized_counts_Annotated_mean)==F)>1){
                            if (nrow(SPLIT_Normalized_counts_Annotated_mean)>2) {
                               
                                
                                if (nrow(SPLIT_Normalized_counts_Annotated_mean)<=opt$k.max) {
                                    k.max=nrow(SPLIT_Normalized_counts_Annotated_mean)-1
                                }else{
                                    k.max=opt$k.max
                                }
                                if ((opt$FUNcluster=='click') && (!is.na(opt$CLICK_PATH))){
                                    clusters = Run_click(mat =as.matrix(SPLIT_Normalized_counts_Annotated_mean),click_path = opt$CLICK_PATH,outDir = opt$outDir,HOMOGENEITY = opt$CLICK_HOMOGENEITY)
                                }else{
                                    if (opt$Mclust){
                                        Fit_Mclust <- Mclust( as.matrix(SPLIT_Normalized_counts_Annotated_mean) ,G=1:k.max,modelNames = mclust.options("emModelNames"))
                                        Number_Of_Clusters=Fit_Mclust$G
                                        Clustering <- eclust(as.matrix(SPLIT_Normalized_counts_Annotated_mean),
                                                           stand =F, 
                                                           FUNcluster= opt$FUNcluster,
                                                           hc_metric =opt$hc_metric, 
                                                           graph = FALSE,
                                                           hc_method = opt$hc_method, 
                                                           k=Number_Of_Clusters ) 
                                        clusters=Clustering$cluster
                                    }else{
                                        
                                        method = c(opt$gap_maxSE_method,"firstSEmax", "Tibs2001SEmax", "globalSEmax",
                                                   "firstmax", "globalmax")
                                        for (gap_maxSE_method in method){
                                            Clustering <- try(eclust(as.matrix(SPLIT_Normalized_counts_Annotated_mean),stand =F,
                                                               FUNcluster= opt$FUNcluster,
                                                               hc_metric =opt$hc_metric,
                                                               graph = FALSE,
                                                               hc_method = opt$hc_method,
                                                               k.max =  k.max,
                                                               nboot = opt$nboot,
                                                               gap_maxSE = list(method= gap_maxSE_method, SE.factor = opt$gap_maxSE_SE.factor) ),
                                                    silent = T)
                                            if ((inherits(Clustering,"try-error"))==FALSE){
                                                clusters=Clustering$cluster
                                                if (gap_maxSE_method != opt$gap_maxSE_method){
                                                   cat(sprintf("<h5>%s</h5>",'The original gap_maxSE_method parameter did not work therefore it was changed to')) 
                                                   cat(sprintf("<h5>%s</h5>",gap_maxSE_method)) 
                                                }
                                                break
                                            }
                                        }
                                    }
                                }
                            }else if (nrow(SPLIT_Normalized_counts_Annotated_mean)==1){
                                clusters=rep(1,nrow(SPLIT_Normalized_counts_Annotated_mean))
                                names(clusters)=rownames((SPLIT_Normalized_counts_Annotated_mean))
                                cat(sprintf("<h4>%s</h4>","Since only 1 significant genes were detected, No clustering was performed"))
                            }else if (nrow(SPLIT_Normalized_counts_Annotated_mean)==2){
                                Clustering <- eclust(as.matrix(SPLIT_Normalized_counts_Annotated_mean),stand = F,
                                                           FUNcluster= 'kmeans',
                                                           graph = FALSE,
                                                           k.max = 2,
                                                           nboot = opt$nboot,
                                                           gap_maxSE = list(method= opt$gap_maxSE_method, SE.factor = opt$gap_maxSE_SE.factor) )
                                clusters=Clustering$cluster
                                cat(sprintf("<h4>%s</h4>","Since only 2 significant genes were detected, the clustering was performed using the kmeans method"))
                                
                            }else{
                                clusters=c()
                            }
                        }else{
                            clusters=rep(1,nrow(SPLIT_Normalized_counts_Annotated_mean) )
                            names(clusters)=rownames((SPLIT_Normalized_counts_Annotated_mean))
                        }
                        
                        if (length(no_var)>0){
                          if (length(clusters)>0){
                            temp=rep(max(clusters)+1,length(no_var) )
                          }else{
                            temp=rep(1,length(no_var) )
                          }
                          names(temp)=no_var
                          clusters=c(clusters,temp)
                        }
    
                        if ((opt$hc_metric=='spearman') | ((opt$hc_metric=='pearson') )){
                          hc_metric='correlation'
                        }else{
                          hc_metric=opt$hc_metric
                        }
                        
                        
                        New_clusters=c()
                        for (num in sort(unique(clusters))){
                            res_red=unique(names(clusters))
                            Genes=res_red[res_red  %in% names(clusters[clusters %in% num])]
                            if (length(Genes)>1){
                                if (opt$stand){
                                    heat_map=pheatmap(mat = as.matrix(Heatmap_Normalized_counts_Annotated_mean[Genes,]),
                                                    cluster_rows = T,show_rownames=F,
                                                    clustering_distance_rows = hc_metric ,
                                                    clustering_method=opt$hc_method,
                                                    cluster_cols = F,silent = T,scale = "row")
                                }else{
                                    heat_map=pheatmap(mat = as.matrix(Heatmap_Normalized_counts_Annotated_mean[Genes,]),
                                                    cluster_rows = T,show_rownames=F,
                                                    clustering_distance_rows = hc_metric ,
                                                    clustering_method=opt$hc_method,
                                                    cluster_cols = F,silent = T)
                                }
                                New_clusters=c(New_clusters,clusters[heat_map$tree_row$labels[heat_map$tree_row$order]])
                            }else{
                                New_clusters=c(New_clusters,clusters[Genes])
                            }
                        }
    
                        clusters=New_clusters
                        
                        
                        intgroup=c(opt$GROUP,opt$X_AXIS)
                        intgroup=intgroup[!is.na(intgroup)]
                        clusters_plots = plot_clusters(clusters,SPLIT_Normalized_counts_Annotated,c(GROUP,X_AXIS),c(GROUP,X_AXIS,"Normalized Intensity"),X_AXIS_ORDER=unique(coldata[X_AXIS]))
                        Clustering_Plot = clusters_plots[[1]]
                        
                        Clustering_Plot_file = file.path(opt$outDir,paste('Clusters_',SPLIT,".pdf",sep="")) 
                        ggsave(Clustering_Plot_file,Clustering_Plot,dpi = 600, width = 6.99, height = 6.99, units = "in")
                        
                         Clustering_Plot_file = file.path(opt$outDir,paste('Clusters_',SPLIT,".png",sep="")) 
                        ggsave(Clustering_Plot_file,Clustering_Plot,dpi = 600, width = 6.99, height =6.99, units = "in")
                        
                        
                        main_plot_list <- c(main_plot_list ,list(htmltools::h4(paste('The Next Figure is of the',SPLIT,"significant Genes Clusters",sep=" "))) )
                        
                        link = xfun::embed_file(path = Clustering_Plot_file,name = '',text = '' )
                        link$name='img'
                        link$attribs$src = link$attribs$href
                        link$attribs$href = NULL
                        
                        main_plot_list <- c(main_plot_list ,list(htmltools::img(link,alt = '')))
                        
             
                        # cat(sprintf("<h4>%s</h4>",paste('The Next Figure is of the',SPLIT,"significant Genes Clusters",sep=" ")))
                        
                        
                        
                        # grid::grid.newpage()
                        # grid::grid.draw(Clustering_Plot)
                        # grid::grid.newpage()
                        # grid::grid.raster(Clustering_Plot)
                        
                        
                        
                        if (!is.na(opt$GO_Heatmap)){
                            GO_Heatmap = unlist(stringi::stri_split(str = opt$GO_Heatmap,regex = ','))
                        }else{
                            GO_Heatmap = c()
                        }
                        Extra_annotation_row = data.frame(row.names = sig.genes)
                        Original_clusters = clusters
                        for (Heatmap_Type in c(GO_Heatmap,'Mean','Raw')){
                            annotation_row_COLORS = list()
                            genes    = sig.genes
                            clusters = Original_clusters
                            annotation_row = data.frame()
                            if (Heatmap_Type=='Mean'){
                                mat = as.matrix(Heatmap_Normalized_counts_Annotated_mean[genes,])
                            }else{
                                if ( stringi::stri_startswith(str = Heatmap_Type,fixed = 'GO:') ){
                                    New_genes = c()
                                    if (!is.na(GO2gene_MF)){
                                       New_genes = c(New_genes , GO2gene_MF[GO2gene_MF$GO %in% Heatmap_Type,'Gene'])
                                    }
                                    if (!is.na(GO2gene_BP)){
                                       New_genes = c(New_genes , GO2gene_BP[GO2gene_BP$GO %in% Heatmap_Type,'Gene'])
                                    }
                                    if (!is.na(GO2gene_CC)){
                                       New_genes = c(New_genes , GO2gene_CC[GO2gene_CC$GO %in% Heatmap_Type ,'Gene'])
                                    }
                                    
                                    genes    = genes[ genes %in% unique(New_genes)]
                                    Extra_annotation_row[Heatmap_Type] = 0
                                    Extra_annotation_row[genes,Heatmap_Type] = 1
                                    clusters = clusters[names(clusters) %in% genes]
                                }
                                mat = apply(X =Heatmap_Normalized_counts_Annotated[genes,] ,MARGIN = c(1,2),FUN = as.numeric)
                                
                                New_clusters=c()
                                for (num in sort(unique(clusters))){
                                    res_red=unique(names(clusters))
                                    Genes=res_red[res_red  %in% names(clusters[clusters %in% num])]
                                    if (length(Genes)>1){
                                        if (opt$stand){
                                            heat_map=pheatmap(mat = mat[Genes,],
                                                            cluster_rows = T,show_rownames=F,
                                                            clustering_distance_rows = hc_metric ,
                                                            clustering_method=opt$hc_method,
                                                            cluster_cols = F,silent = T,scale = "row")
                                        }else{
                                            heat_map=pheatmap(mat = mat[Genes,],
                                                            cluster_rows = T,show_rownames=F,
                                                            clustering_distance_rows = hc_metric ,
                                                            clustering_method=opt$hc_method,
                                                            cluster_cols = F,silent = T)
                                        }
                                        New_clusters=c(New_clusters,clusters[heat_map$tree_row$labels[heat_map$tree_row$order]])
                                    }else{
                                        New_clusters=c(New_clusters,clusters[Genes])
                                    }
                                }
    
                                clusters=New_clusters
    
                                
                            }
                            mat=mat[names(clusters),]
                            
                            write.table(mat,
                                        file = file.path(opt$outDir,paste('Significant_Genes_',Heatmap_Type,opt$NORMALIZATION_TYPE,'Normalized_counts.txt', sep = '_')) ,
                                        quote = F,
                                        sep = "\t")
                            
                            
                           
                            if (X_AXIS!=GROUP){
                                split=sapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[1])
                                #colnames(split)='split'
    
                                annotation_col=data.frame(row.names =colnames(mat) ,
                                                          X_AXIS = sapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[2] ),
                                                          GROUP  = sapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[1] )
                                                         )
                                                        
                                colnames(annotation_col)=c(X_AXIS,GROUP)
                                if (Heatmap_Type!='Mean'){
                                    if (!is.na(opt$Heatmap_Extra_Annotaions)){
                                        Heatmap_Extra_Annotaions = strsplit(x = opt$Heatmap_Extra_Annotaions,split = ",")[[1]]
                                        samples = unlist(lapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[3]))
                                        for ( Col_Extra_Annotaions in Heatmap_Extra_Annotaions){
                                            annotation_col[Col_Extra_Annotaions]  = coldata[samples,Col_Extra_Annotaions]
                                        }
                                    }
                                }
                                annotation_col[X_AXIS]  <- factor(annotation_col[,X_AXIS] ,levels=intersect(unique(coldata[,X_AXIS]),unique(annotation_col[,X_AXIS]) ))
                                annotation_col[GROUP]   <- factor(annotation_col[,GROUP] ,levels=intersect(unique(coldata[,GROUP]),unique(annotation_col[,GROUP]) ))
                                new_order = order(annotation_col[,GROUP],annotation_col[,X_AXIS])
                                annotation_col = annotation_col[new_order,,drop=FALSE]
                                mat = mat[,new_order,drop=FALSE]
                                annotation_row = data.frame("Clusters" = factor(clusters))
                                if (Heatmap_Type %in% c('Mean','Raw')){
                                    for (Extra_annotation in colnames(Extra_annotation_row)){
                                       annotation_row[Extra_annotation] = Extra_annotation_row[names(clusters),Extra_annotation]
                                       color_category = c("#FFFFFF","#000000")
                                       names(color_category) = c(0,1)
                                       annotation_row_COLORS[Extra_annotation] = list(color_category)
                                    }
                                }
                                if (Heatmap_Type!='Mean'){
                                    colnames(mat)             = sapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[3])
                                    row.names(annotation_col) = sapply(X =row.names(annotation_col),FUN = function(x) unlist(strsplit(x =x,split = " "))[3])
                                    show_colnames = T
                                }else{
                                    show_colnames = F
                                }
                                if (opt$stand){
                                    heat_map=pheatmap(mat =mat ,
                                                    cluster_rows= F,show_rownames=F,
                                                    cluster_cols=F,scale = "row",
                                                    annotation_row = annotation_row,
                                                    annotation_colors = annotation_row_COLORS,
                                                    #annotation_names_row=F,
                                                    border_color=NA,
                                                    silent = T,
                                                    fontsize_col = 7,
                                                    annotation_col=annotation_col ,
                                                    show_colnames = show_colnames,
                                                    gaps_row = cumsum(aggregate.data.frame(x = as.data.frame(clusters),by =list(clusters),FUN = length )[,"clusters"] ),
                                                    gaps_col = c(cumsum(rev(aggregate.data.frame(x = annotation_col[X_AXIS],by =annotation_col[c(X_AXIS,GROUP)],FUN = length))[,1]),
                                                                 rep(cumsum(rev(aggregate.data.frame(x = annotation_col[GROUP],by =annotation_col[c(GROUP)],FUN = length))[,1]),2)
                                                                 )
                                    )
                                }else{
                                        heat_map=pheatmap(mat =mat ,
                                                    cluster_rows= F,show_rownames=F,
                                                    cluster_cols=F,scale = "row",
                                                    annotation_row = annotation_row,
                                                    annotation_colors = annotation_row_COLORS,
                                                    #annotation_names_row=F,
                                                    border_color=NA,
                                                    silent = T,
                                                    fontsize_col = 7,
                                                    annotation_col=annotation_col ,
                                                    show_colnames = show_colnames,
                                                    gaps_row = cumsum(aggregate.data.frame(x = as.data.frame(clusters),by =list(clusters),FUN = length )[,"clusters"] ),
                                                    gaps_col = c(cumsum(rev(aggregate.data.frame(x = annotation_col[X_AXIS],by =annotation_col[c(X_AXIS,GROUP)],FUN = length))[,1]),
                                                                 rep(cumsum(rev(aggregate.data.frame(x = annotation_col[GROUP],by =annotation_col[c(GROUP)],FUN = length))[,1]),2)
                                                                 )
                                                )
                                }
                            
                            
                            }else{
                                annotation_col=data.frame(row.names =colnames(mat) ,
                                                        X_AXIS=sapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[1] ))
                                colnames(annotation_col)=c(X_AXIS)

                                if (Heatmap_Type!='Mean'){
                                    if (!is.na(opt$Heatmap_Extra_Annotaions)){
                                        Heatmap_Extra_Annotaions = strsplit(x = opt$Heatmap_Extra_Annotaions,split = ",")[[1]]
                                        samples = unlist(lapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[2]))
                                        for ( Col_Extra_Annotaions in Heatmap_Extra_Annotaions){
                                            annotation_col[Col_Extra_Annotaions]  = coldata[samples,Col_Extra_Annotaions]
                                        }
                                    }
                                }
                                annotation_col[X_AXIS]  <- factor(annotation_col[,X_AXIS] ,levels=intersect(unique(coldata[,X_AXIS]),unique(annotation_col[,X_AXIS]) ))
                                new_order = order(annotation_col[,X_AXIS])
                                annotation_col = annotation_col[new_order,,drop=FALSE]
                                mat = mat[,new_order,drop=FALSE]
                                annotation_row = data.frame("Clusters" = factor(clusters))
                                if (Heatmap_Type %in% c('Mean','Raw')){
                                   for (Extra_annotation in colnames(Extra_annotation_row)){
                                       annotation_row[Extra_annotation] = Extra_annotation_row[names(clusters),Extra_annotation]
                                       color_category = c("#FFFFFF","#000000")
                                       names(color_category) = c(0,1)
                                       annotation_row_COLORS[Extra_annotation] = list(color_category)
                                   }
                                }
                                
                                if (Heatmap_Type!='Mean'){
                                    colnames(mat)             = sapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[2])
                                    row.names(annotation_col) = sapply(X =row.names(annotation_col),FUN = function(x) unlist(strsplit(x =x,split = " "))[2])
                                    show_colnames = T
                                }else{
                                    show_colnames = F
                                }
                                
                                if (opt$stand){
                                    heat_map=pheatmap(mat = mat ,
                                                      cluster_rows= F,show_rownames=F,
                                                      cluster_cols=F,scale = "row",
                                                      silent = T,
                                                      fontsize_col = 7,
                                                      annotation_row=annotation_row,
                                                      annotation_colors = annotation_row_COLORS,
                                                      #annotation_names_row=T,
                                                      annotation_col=annotation_col,
                                                      show_colnames = show_colnames,
                                                      gaps_row = cumsum(aggregate.data.frame(x = as.data.frame(clusters),by =list(clusters),FUN = length )[,"clusters"] ),
                                                      gaps_col = cumsum(aggregate.data.frame(x = annotation_col[X_AXIS],by =annotation_col[X_AXIS],FUN = length)[,-1]),
                                                      border_color=NA
                                    )
                                }else{
                                    heat_map=pheatmap(mat =mat ,
                                                      cluster_rows= F,show_rownames=F,
                                                      cluster_cols=F,
                                                      silent = T,
                                                      fontsize_col = 7,
                                                      annotation_row=annotation_row,
                                                      annotation_colors = annotation_row_COLORS,
                                                      #annotation_names_row=T,
                                                      annotation_col=annotation_col,
                                                      show_colnames = show_colnames,
                                                      gaps_row = cumsum(aggregate.data.frame(x = as.data.frame(clusters),by =list(clusters),FUN = length )[,"clusters"] ),
                                                      gaps_col = cumsum(aggregate.data.frame(x = annotation_col[X_AXIS],by =annotation_col[X_AXIS],FUN = length)[,-1]),
                                                      border_color=NA
                                    )
                                }
                            }
                            
                            if (Heatmap_Type=='Raw'){
                                # cat(sprintf("<h4>%s</h4>",paste('The Next Figure is of the', SPLIT ,'Significant Genes relative expression Clustered and plotted as a HeatMap',sep=" ")))
                                # grid::grid.newpage()
                                # grid::grid.draw(heat_map$gtable)
                                # grid::grid.newpage()
                                save(list=ls(all.names = TRUE),file =file.path(opt$outDir,'SSession.RSession'))
                                main_plot_list <- c(main_plot_list ,list(htmltools::h4(paste('The Next Figure is of the', SPLIT ,'Significant Genes relative expression Clustered and plotted as a HeatMap',sep=" "))) )
                                
                            }else if (Heatmap_Type=='Mean') {
                                # cat(sprintf("<h4>%s</h4>",paste('The Next Figure is of the', SPLIT ,'Significant Genes relative expression [Mean over biological replicates] Clustered and plotted as a HeatMap',sep=" ")))
                                # grid::grid.newpage()
                                # grid::grid.draw(heat_map$gtable)
                                # grid::grid.newpage()
                                main_plot_list <- c(main_plot_list ,list(htmltools::h4(paste('The Next Figure is of the', SPLIT ,'Significant Genes relative expression [Mean over biological replicates] Clustered and plotted as a HeatMap',sep=" "))) )
                                
                            }
                            HeatMap_Plot_file = file.path(opt$outDir,paste('Clustering_heatmap_',SPLIT,'_',Heatmap_Type,".pdf",sep=""))
                            ggsave(HeatMap_Plot_file,heat_map$gtable,dpi = 600, width = 15, height = 15, units = "cm",scale = 1.5)
                            HeatMap_Plot_file = file.path(opt$outDir,paste('Clustering_heatmap_',SPLIT,'_',Heatmap_Type,".png",sep=""))
                            ggsave(HeatMap_Plot_file,heat_map$gtable,dpi = 600, width = 15, height = 15, units = "cm",scale = 1.5)
                            
                            link = xfun::embed_file(path = HeatMap_Plot_file,name = '',text = '' )
                            link$name='img'
                            link$attribs$src = link$attribs$href
                            link$attribs$href = NULL
                        
                            main_plot_list <- c(main_plot_list ,list(htmltools::img(link,alt = '')))
                            mat2=t(scale(t(mat)))
                            mat3=cbind(clusters[rownames(mat2)],mat2)
                            if (Heatmap_Type %in% c('Mean','Raw')){
                                for (Extra_annotation in colnames(Extra_annotation_row)){
                                    if (!Extra_annotation=="Clusters"){
                                        Extra_annotation_temp = data.frame(Extra_annotation = Extra_annotation_row[rownames(mat2),Extra_annotation])
                                        colnames(Extra_annotation_temp) = Extra_annotation 
                                        mat3=cbind(mat3,Extra_annotation_temp)
                                    }
                                }
                            }
                            if (!is.na(results)){
                                mat3=cbind(mat3,results[rownames(mat3),c('log2FoldChange',"padj")])
                            }
                            if (!is.na(Annotation)) {
                              mat3=merge.data.frame(mat3,Annotation,by="row.names",all.x = T,sort = F)
                              rownames(mat3)=mat3$Row.names
                              mat3$Row.names=NULL
                            }
                            colnames(mat3)[colnames(mat3)=="V1"]="Clusters"
                            colnames(mat3)[colnames(mat3)==""]="Clusters"
                            # col_names=colnames(mat3)
                            # col_names[col_names=="V1"]="Clusters"
                            # colnames(mat3)=col_names
                            mat3=mat3[rownames(mat2),]
                            write.csv(x = mat3,
                                      file = file.path(opt$outDir, paste('Clustering_heatmap_',SPLIT,'_',Heatmap_Type,".csv",sep="") ),
                                      quote = TRUE,
                                      row.names = TRUE)
                                      
                            
                            if (Heatmap_Type %in% c('Mean','Raw') ){
                                HeatMap_table  =  datatable(mat3,
                                                            caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',
                                                                                                    'Table: ', 
                                                                                                    htmltools::em(paste('This Table is of the ',SPLIT,'Significant Genes Clusterd [as in the HeatMap Figure] and Annotated',sep=""))
                                                                                            ),
                                                            options = list(keys = TRUE ,
                                                                         scrollX = TRUE,
                                                                         fixedHeader = FALSE,
                                                                         fixedColumns = TRUE,
                                                                         pageLength = 5,
                                                                         scrollY = 300,
                                                                         orderClasses=TRUE,
                                                                         autoWidth = TRUE,
                                                                         scroller = TRUE,
                                                                         dom = 'Bfrtip',
                                                                         buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                                                                         deferRender = TRUE),
                                                            class = 'cell-border stripe',
                                                            filter = 'top',
                                                            extensions = c('Buttons','FixedColumns','FixedHeader','KeyTable','Scroller'))
                                main_plot_list <- c(main_plot_list ,list(HeatMap_table) )
                            }
                            
                        }
                        
                        # save(list=ls(all.names = TRUE),file =file.path(opt$outDir,'SSession.RSession'))
                        # save.image(file.path(opt$outDir,'Session.RSession'))
                        
                        
                        
                        ##################Clustering-End##################################    
    
                        ##################GO/KEGG STAR####################################
                        # Go Enrichment:
                        #cat(sprintf("<h2>%s</h2>", 'Enrichment Analysis:'))
                        
                        main_plot_list <- c(main_plot_list ,list(htmltools::h2('Enrichment Analysis:')) )
                        if (Annotation_flag == 'OrgDb'){
                            gene2entrez = bitr(names(clusters), fromType=opt$GENE_ID_TYPE, toType=c("ENTREZID"), OrgDb=opt$Annotation_db)
                            gene2entrez = gene2entrez[!duplicated(gene2entrez[opt$GENE_ID_TYPE]),]
                            gene2entrez$CLUSTERS=sapply(X =gene2entrez[opt$GENE_ID_TYPE],FUN = function(x)  unlist(clusters[x]))
    
                            clusters_for_GO= gene2entrez$CLUSTERS
                            names(clusters_for_GO)=gene2entrez$ENTREZID
    
                            allRes <- clusters_enricher(opt$outDir,clusters_for_GO,"GO",opt$Annotation_db,Annotation$ENTREZID,"ENTREZID",paste('GO_Biological_Process_Enrichment_of_Clusters',SPLIT,sep="_"),pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,maxCategory = opt$Max_Dotplot)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                              heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'GO_Biological_Process_Enrichment_of_Clusters')
                              main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }
     
                                if (((length(down_reg)>0) || (length(up_reg)>0))){
                                    up_down_clusters = clusters
                                    if (length(down_reg)>0){
                                        up_down_clusters[down_reg]='Down'
                                    }
                                    if (length(up_reg)>0){
                                        up_down_clusters[up_reg]='UP'
                                    }
    
                                    allRes <- clusters_enricher(opt$outDir,up_down_clusters,"GO",opt$Annotation_db,Annotation$ENTREZID,"ENTREZID",paste('GO_Biological_Process_Enrichment_of_Up_and_Down_Clusters',SPLIT,sep="_"),pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff)
                                    main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                                    if (opt$Enriched_terms_overlap){
                                      heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'GO_Biological_Process_Enrichment_of_Up_and_Down_Clusters')
                                      main_plot_list <- c(main_plot_list ,list(heatmaps))
                                    }
    
                                }
     
                            One_cluster=clusters_for_GO
                            One_cluster[]=1
                            allRes <- clusters_enricher(opt$outDir,One_cluster,"GO",opt$Annotation_db,Annotation$ENTREZID,"ENTREZID",paste('GO_Biological_Process_Enrichment_of_All_Significant_Genes',SPLIT,sep="_"),pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,maxCategory = opt$Max_Dotplot)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                              heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'GO_Biological_Process_Enrichment_of_All_Significant_Genes')
                              main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }
                            
                            
                        }else{
                            if (GO_flag){
                                GOTypes = unlist(stringi::stri_split(str = opt$GO_Enrichment_Type,regex = ','))
                                for (GOType in GOTypes){
                                    GO2gene = NA
                                    GO2name = NA
                                    if (GOType == 'BP'){
                                      if ((!is.na(GO2gene_BP)) && (!is.na(GO2name_BP))) {
                                        GO2gene = GO2gene_BP
                                        GO2name = GO2name_BP
                                      }
                                    }
                                    if (GOType == 'MF'){
                                      if ((!is.na(GO2gene_MF)) && (!is.na(GO2name_MF))) {
                                        GO2gene = GO2gene_MF
                                        GO2name = GO2name_MF
                                      }
                                    }
                                    
                                    if (GOType == 'CC'){
                                      if ((!is.na(GO2gene_CC)) && (!is.na(GO2name_CC))) {
                                        GO2gene = GO2gene_CC
                                        GO2name = GO2name_CC
                                      }
                                    }
                                    
                                    if ((!is.na(GO2gene)) && (!is.na(GO2name))) {
                                        allRes <- Clusters_Enrichment_Test(opt$outDir,clusters,GO2name,GO2gene,paste(GOType,'_GO_Enrichment_of_Clusters',SPLIT,sep="_"),"GO",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                                        main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                                        if (opt$Enriched_terms_overlap){
                                            heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,paste(GOType,'_GO_Enrichment_of_Clusters'))
                                            main_plot_list <- c(main_plot_list ,list(heatmaps))
                                        }
                                        
                                        if (((length(down_reg)>0) || (length(up_reg)>0)) ){
                                            up_down_clusters = clusters
                                            if (length(down_reg)>0){
                                                up_down_clusters[down_reg]='Down'
                                            }
                                            if (length(up_reg)>0){
                                                up_down_clusters[up_reg]='UP'
                                            }
                                            
                                            allRes <- Clusters_Enrichment_Test(opt$outDir,up_down_clusters,GO2name,GO2gene,paste(GOType,'_GO_Enrichment_of_Up_and_Down_Clusters',SPLIT,sep="_"),"GO",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                                            if (opt$Enriched_terms_overlap){
                                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,paste(GOType,'_GO_Enrichment_of_Up_and_Down_Clusters'))
                                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                                            }
                                        }
                                        One_cluster=clusters
                                        One_cluster[]=1
                                        allRes <- Clusters_Enrichment_Test(opt$outDir,One_cluster,GO2name,GO2gene,paste(GOType,'_GO_Enrichment_of_All_Significant_Genes',SPLIT,sep="_"),"GO",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                                        main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                                        if (opt$Enriched_terms_overlap){
                                            heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,paste(GOType,'_GO_Enrichment_of_All_Significant_Genes'))
                                            main_plot_list <- c(main_plot_list ,list(heatmaps))
                                        }
                                    }
                                }
                                
                            }
                        }
                        
                        pathway_table = data.frame()
                        if (KEGG_flag){
                            if (opt$KEGG_Enrichment_of == 'ko'){
                                TERMS_Info= create_gene2kegg(Annotation,T)
                                TERMS2GENES = TERMS_Info[1]
                                TERMS2NAMES = TERMS_Info[2]
                                if ((length(GENES2TERMS)>0)&&(length(TERMS2NAMES)>0) ){
                                    Pathway2name_ = TERMS2NAMES
                                    Pathway2gene_ = TERMS2GENES
                                }else{
                                    Pathway2name_ = Pathway2name
                                    Pathway2gene_ = Pathway2gene
                                }
                                
                            }else{
                                Pathway2name_ = Pathway2name
                                Pathway2gene_ = Pathway2gene
                            }
                            allRes <- Clusters_Enrichment_Test(opt$outDir,clusters,Pathway2name_,Pathway2gene_,paste('KEGG_Enrichment_Analysis_of_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Clusters')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }
     
                            if (((length(down_reg)>0) || (length(up_reg)>0)) ){
                                up_down_clusters = clusters
                                if (length(down_reg)>0){
                                    up_down_clusters[down_reg]='Down'
                                }
                                if (length(up_reg)>0){
                                    up_down_clusters[up_reg]='UP'
                                }
    
                                allRes <- Clusters_Enrichment_Test(opt$outDir,up_down_clusters,Pathway2name_,Pathway2gene_,paste('KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                                main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                                if (opt$Enriched_terms_overlap){
                                    heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters')
                                    main_plot_list <- c(main_plot_list ,list(heatmaps))
                                }
    
                            }
     
                            One_cluster=clusters
                            One_cluster[]=1
                            allRes <- Clusters_Enrichment_Test(opt$outDir,One_cluster,Pathway2name_,Pathway2gene_,paste('KEGG_Enrichment_Analysis_of_All_Significant_Genes',SPLIT,sep="_"),"KEGG",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_All_Significant_Genes')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }
                           
                            if (((length(down_reg)>0) || (length(up_reg)>0))){
                                pathway_table = create_pathway_table(opt$outDir,up_reg,down_reg,Annotation,Pathway2name,Pathway2gene,Pathway_show_cutoff,T,Pathway_up_color,Pathway_down_color)
                            } else{
                                pathway_table = create_pathway_table(opt$outDir,sig.genes,c(),Annotation,Pathway2name,Pathway2gene,Pathway_show_cutoff,T,Pathway_up_color,Pathway_down_color)
                            }
                        }
                        
                        if (ORGANISM_KEGG_flag){
                            if (opt$KEGG_Enrichment_of == 'ko'){
                                TERMS_Info= create_gene2kegg(Annotation,F)
                                TERMS2GENES = TERMS_Info[1]
                                TERMS2NAMES = TERMS_Info[2]
                                if ((length(GENES2TERMS)>0)&&(length(TERMS2NAMES)>0) ){
                                    ORGANISM_Pathway2name_ = TERMS2NAMES
                                    ORGANISM_Pathway2gene_ = TERMS2GENES
                                }else{
                                    ORGANISM_Pathway2name_ = ORGANISM_Pathway2name
                                    ORGANISM_Pathway2gene_ = ORGANISM_Pathway2gene
                                }
                                
                            }else{
                                ORGANISM_Pathway2name_ = ORGANISM_Pathway2name
                                ORGANISM_Pathway2gene_ = ORGANISM_Pathway2gene
                            }
                            
                            allRes  <- Clusters_Enrichment_Test(opt$outDir,clusters,ORGANISM_Pathway2name_,ORGANISM_Pathway2gene_,paste(ORGANISM,'KEGG_Enrichment_Analysis_of_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                            
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Clusters')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }
                            
                            if (((length(down_reg)>0) || (length(up_reg)>0)) ){
                                up_down_clusters = clusters
                                if (length(down_reg)>0){
                                    up_down_clusters[down_reg]='Down'
                                }
                                if (length(up_reg)>0){
                                    up_down_clusters[up_reg]='UP'
                                }
    
                                allRes <- Clusters_Enrichment_Test(opt$outDir,up_down_clusters,ORGANISM_Pathway2name_,ORGANISM_Pathway2gene_,paste(ORGANISM,'KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                                main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                                if (opt$Enriched_terms_overlap){
                                    heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters')
                                    main_plot_list <- c(main_plot_list ,list(heatmaps))
                                }
    
                            }
                            
                            One_cluster=clusters
                            One_cluster[]=1
                            allRes <- Clusters_Enrichment_Test(opt$outDir,One_cluster,ORGANISM_Pathway2name_,ORGANISM_Pathway2gene_,paste(ORGANISM,'KEGG_Enrichment_Analysis_of_All_Significant_Genes',SPLIT,sep="_"),"KEGG",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_All_Significant_Genes')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }
                            
                            if (((length(down_reg)>0) || (length(up_reg)>0)) ){
                                pathway_table = create_pathway_table(opt$outDir,up_reg,down_reg,Annotation,ORGANISM_Pathway2name,ORGANISM_Pathway2gene,Pathway_show_cutoff,T,Pathway_up_color,Pathway_down_color,F)
                            } else{
                                pathway_table = create_pathway_table(opt$outDir,sig.genes,c(),Annotation,ORGANISM_Pathway2name,ORGANISM_Pathway2gene,Pathway_show_cutoff,T,Pathway_up_color,Pathway_down_color,F)
                            }
                        }
                        if (KEGG_KAAS_flag){
                            if (opt$KEGG_Enrichment_of == 'ko'){
                                TERMS_Info= create_gene2kegg(Annotation,T)
                                TERMS2GENES = TERMS_Info[1]
                                TERMS2NAMES = TERMS_Info[2]
                                if ((length(GENES2TERMS)>0)&&(length(TERMS2NAMES)>0) ){
                                    KASS_Pathway2name_ = TERMS2NAMES
                                    KASS_Pathway2gene_ = TERMS2GENES
                                }else{
                                    KASS_Pathway2name_ = KASS_Pathway2name
                                    KASS_Pathway2gene_ = KASS_Pathway2gene
                                }
                                
                            }else{
                                KASS_Pathway2name_ = KASS_Pathway2name
                                KASS_Pathway2gene_ = KASS_Pathway2gene
                            }
                            
                            allRes <- Clusters_Enrichment_Test(opt$outDir,clusters,KASS_Pathway2name_,KASS_Pathway2gene_,paste('KEGG_Enrichment_Analysis_of_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Clusters')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }
                            
                            
                            if (((length(down_reg)>0) || (length(up_reg)>0)) ){
                                up_down_clusters = clusters
                                if (length(down_reg)>0){
                                    up_down_clusters[down_reg]='Down'
                                }
                                if (length(up_reg)>0){
                                    up_down_clusters[up_reg]='UP'
                                }
    
                                allRes <- Clusters_Enrichment_Test(opt$outDir,up_down_clusters,KASS_Pathway2name_,KASS_Pathway2gene_,paste('KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                                main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                                if (opt$Enriched_terms_overlap){
                                    heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters')
                                    main_plot_list <- c(main_plot_list ,list(heatmaps))
                                }
                            }
                            
                            One_cluster=clusters
                            One_cluster[]=1
                            allRes <- Clusters_Enrichment_Test(opt$outDir,One_cluster,KASS_Pathway2name_,KASS_Pathway2gene_,paste('KEGG_Enrichment_Analysis_of_All_Significant_Genes',SPLIT,sep="_"),"KEGG",pAdjustMethod=opt$Enrichment_padjustmethod,pvalueCutoff=opt$Enrichment_pvaluecutoff,gene2ko=FALSE,maxCategory = opt$Max_Dotplot)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_All_Significant_Genes')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }
                            
                            if (((length(down_reg)>0) || (length(up_reg)>0)) ){
                                pathway_table = create_pathway_table(opt$outDir,up_reg,down_reg,Annotation,KASS_Pathway2name,KASS_Pathway2gene,Pathway_show_cutoff,T,Pathway_up_color,Pathway_down_color)
                            } else{
                                pathway_table = create_pathway_table(opt$outDir,sig.genes,c(),Annotation,KASS_Pathway2name,KASS_Pathway2gene,Pathway_show_cutoff,T,Pathway_up_color,Pathway_down_color)
                            }
                        }
                        ##################GO/KEGG-End####################################    
                    }
                    
                    if (length(pathway_table)>0){
                        main_plot_list <- c(main_plot_list ,list(htmltools::h2('KEGG Pathways:')) )
                        pathway_table_HTML  =  datatable(pathway_table,escape = FALSE,
                                                    caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',
                                                                                            'Table: ', 
                                                                                            htmltools::em(paste('This Table is of the KEGG Pathways Mapped with Significant Genes','',sep=""))
                                                                                    ),
                                                    options = list(keys = TRUE ,
                                                                 scrollX = TRUE,
                                                                 fixedHeader = FALSE,
                                                                 fixedColumns = TRUE,
                                                                 pageLength = 5,
                                                                 scrollY = 300,
                                                                 orderClasses=TRUE,
                                                                 autoWidth = TRUE,
                                                                 scroller = TRUE,
                                                                 dom = 'Bfrtip',
                                                                 buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                                                                 deferRender = TRUE),
                                                    class = 'cell-border stripe',
                                                    filter = 'top',
                                                    extensions = c('Buttons','FixedColumns','FixedHeader','KeyTable','Scroller'))
                        main_plot_list <- c(main_plot_list ,list(pathway_table_HTML) )
                    }
                    htmltools::tagList(list(c(main_plot_list)))
                }else{
                    cat("No significant genes were detected")
                }
            }else{
                cat("The 'X_AXIS' parameter must be given for clustering analysis ")
            }
            
            
        }
 #save.image(file.path(opt$outDir,'Session.RSession'))

```