---
title: "NeatSeq Flow DeSeq2 module Results"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    # fig.height: 10
    # fig.width:  10
    # mathjax: local
    #self_contained: FALSE
#runtime: shiny


params:
    opt: NA
    test2do: NA
    DESeqDataSet_base: NA
    base_out_dir: NA
    colData: NA
    countData: NA
    Annotation: NA
    Annotation_flag: NA
    KEGG_flag: FALSE
    ORGANISM_KEGG_flag: FALSE
    KEGG_KAAS_flag: FALSE
    GO_flag: FALSE
    
---

<style>
pre {
  overflow-x: auto;
}
pre code {
  word-wrap: normal;
  white-space: pre;
}
</style>

## Parameters Used in This Analysis:
```{r echo = FALSE, error = TRUE, comment='', message = FALSE, warning = FALSE}
if (test2do=='LTR'){
    opt$CONTRAST = NA
}else{
    opt$CONTRAST = test2do
}

parameters_used = as.data.frame(x = unlist(opt),row.names = names(opt))
colnames(parameters_used)=c('values')
print.data.frame(parameters_used,right = F,quote = F)
```


```{r echo = FALSE, error = TRUE, comment='', message = FALSE, warning = FALSE}
#####################Functions################################

plotPCA<-function (object, intgroup = "condition", ntop = 500, returnData = FALSE) {
  if (ntop!='all'){
    rv <- genefilter::rowVars(assay(object))
    select <- order(rv, decreasing = TRUE)[seq_len(min(ntop, 
                                                       length(rv)))]
    pca <- prcomp(t(assay(object)[select, ]))
  }else{
    pca <- prcomp(t(assay(object)))
  }
  percentVar <- pca$sdev^2/sum(pca$sdev^2)
  if (!all(intgroup %in% names(colData(object)))) {
    stop("the argument 'intgroup' should specify columns of colData(dds)")
  }
  intgroup.df <- as.data.frame(colData(object)[, intgroup, 
                                               drop = FALSE])
  group <- if (length(intgroup) > 1) {
    factor(apply(intgroup.df, 1, paste, collapse = " : "))
  }else{
    colData(object)[[intgroup]]
  }
  d <- data.frame(PC1 = pca$x[, 1], PC2 = pca$x[, 2],PC3 = pca$x[, 3], group = group, 
                  intgroup.df, name = colnames(object))
  if (returnData) {
    attr(d, "percentVar") <- percentVar[1:3]
    return(d)
  }
  ggplot(data = d, aes_string(x = "PC1", y = "PC2", color = "group")) + 
    geom_point(size = 3) + xlab(paste0("PC1: ", round(percentVar[1] * 
                                                        100), "% variance")) + ylab(paste0("PC2: ", round(percentVar[2] * 
                                                                                                            100), "% variance")) + coord_fixed()
}


cluster_enricher<-function(clusters,num,Type,organism,universe,keyType,Ontology="BP",pvalueCutoff=0.05,pAdjustMethod='fdr',qvalueCutoff=0.05){
  res_red=unique(names(clusters))
  Genes=res_red[res_red  %in% names(clusters[clusters %in% num])]
  if (Type=="GO"){
    res=enrichGO(gene      = Genes,
                 OrgDb         = organism,
                 universe      = universe,
                 keytype       = keyType,
                 ont           = Ontology,
                 pAdjustMethod = pAdjustMethod,
                 pvalueCutoff  = pvalueCutoff,
                 qvalueCutoff  = qvalueCutoff)
  }else{
    res=enrichKEGG(gene          = Genes, 
                   organism      = organism,
                   pAdjustMethod = pAdjustMethod,
                   pvalueCutoff  = pvalueCutoff,
                   qvalueCutoff  = qvalueCutoff,
                   universe      = universe,
                   keyType       = keyType,  
                   minGSSize     = 0,
                   maxGSSize     = length(res_red))
    
    
    
  }
  return(res)
}


clusters_enricher=function(outDir, clusters,Type,organism,universe,keyType,file_name,Ontology="BP",pvalueCutoff=0.05,pAdjustMethod='fdr',qvalueCutoff=0.05){
    allRes=list()
    original_allRes=list()
    cluster_names=list()
    count=1
    for (i in sort(unique(clusters))){
        temp=cluster_enricher(clusters,c(i),Type,organism,universe,keyType,Ontology,pvalueCutoff,pAdjustMethod,qvalueCutoff)
        if (length(temp)>0){
          allRes[count]<-temp
          cluster_names[count]=i
          count=count+1
        }
    } 
    names(allRes)=cluster_names
    allRes=clusterProfiler::merge_result(enrichResultList =allRes)
    allRes@fun<-"enrichGO"
    write.csv(x = allRes@compareClusterResult,
            file =file.path(outDir,paste(file_name,'.csv',collapse = "")) ,
            quote = TRUE,
            row.names = TRUE)
            
    Enrichment_table  = datatable(allRes@compareClusterResult,
                                  caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',
                                                                            'Table: ', 
                                                                            htmltools::em(paste("This Table is of",paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse  = ' ')))
                                                                    ),
                                  options = list(keys = TRUE ,
                                                 scrollX = TRUE,
                                                 fixedHeader = FALSE,
                                                 fixedColumns = TRUE,
                                                 pageLength = 5,
                                                 scrollY = 300,
                                                 orderClasses=TRUE,
                                                 autoWidth = TRUE,
                                                 scroller = TRUE,
                                                 dom = 'Bfrtip',
                                                 buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                                                 deferRender = TRUE),
                                  class = 'cell-border stripe',
                                  filter = 'top',
                                  extensions = c('Buttons','FixedColumns','FixedHeader','KeyTable','Scroller'))
    original_allRes = allRes
    Simplify_title = c()
    if (dim(allRes@compareClusterResult)[1]>0){
        if (Type=="GO"){
            allRes@fun<-"enrichGO"
            temp_allRes<-try(clusterProfiler::simplify(allRes, cutoff=0.7, by="p.adjust", select_fun=min),silent = T)
            if (!inherits(temp_allRes,"try-error")){
                Simplify_title = list(htmltools::h6('*Simplify:  Redundant GO Terms Were Removed From the Figure, Showing Only the Most Significant Among Very Similar (>0.7) GO Terms; For more information see GOSemSim and clusterProfiler R packages'))
                allRes=temp_allRes
                file_name=paste("Simplify",file_name,collapse = "_")
                write.csv(x = allRes@compareClusterResult,file =file.path(outDir,paste(file_name,'.csv',sep='',collapse = "")) ,quote = FALSE,row.names = TRUE)
            }
        }else{
            allRes@fun<-"enrichKEGG"
        }
        if (dim(allRes@compareClusterResult)[1]>50){
            font.size=4
        }else{
            font.size=9
        }

        if (dim(allRes@compareClusterResult)[1]>0){
            #cat(sprintf("<h4>%s</h4>", paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ") ))
            x=DOSE::dotplot(allRes,x=allRes@compareClusterResult$Cluster,showCategory=10000,font.size =font.size)+
            ggplot2::ggsave(filename = file.path(outDir,paste(file_name,".pdf",sep='',collapse = "")),dpi = 600,device = "pdf",width = 20,height = 20)
            grid::grid.newpage()
            return(list(original_allRes,list(htmltools::h4(paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ")),ggplotly(x),Simplify_title,Enrichment_table)))
        }
    }
    
     return(list(original_allRes,list(htmltools::h4(paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ")))))
}


General_Enrichment_Test<-function(clusters,num,TERM2NAME,TERM2GENE,pAdjustMethod='fdr',pvalueCutoff=0.05){
  res_red=unique(TERM2GENE[,2])
  Genes=res_red[res_red  %in% names(clusters[clusters %in% num])]
  
  res=enricher(Genes, TERM2GENE=TERM2GENE, 
               TERM2NAME=TERM2NAME,
               minGSSize     = 0,
               maxGSSize     = length(res_red),
               pAdjustMethod = pAdjustMethod,
               pvalueCutoff  = pvalueCutoff
  ) 
  
  return(res)
}


generat_urls<-function(allRes,gene2ko){
  temp_table=allRes@compareClusterResult
  temp_table$URL=apply(X = temp_table,MARGIN = 1,FUN = function(x) paste(c("http://www.kegg.jp/kegg-bin/show_pathway?",stringi::stri_replace_all(str = x["ID"],replacement = "",regex = "path:",collapse = ""),"/", paste(sapply( unlist(stringi::stri_split(str = x["geneID"],regex = "/")),FUN = function(x) gene2ko[gene2ko$V1==x,"V2"]),collapse = "+") ),collapse = ""))
  allRes@compareClusterResult=temp_table
  return(allRes)
}


Clusters_Enrichment_Test=function(outDir,clusters,TERM2NAME,TERM2GENE,file_name,Type,pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE){
    allRes=list()
    original_allRes = list()
    cluster_names=list()
    count=1
    for (i in sort(unique(clusters))){
        temp=General_Enrichment_Test(clusters,c(i),TERM2NAME,TERM2GENE,pAdjustMethod,pvalueCutoff )
        if (length(temp)>0){
          allRes[count]<-temp
          cluster_names[count]=i
          count=count+1
        }
    } 
    names(allRes)=cluster_names
    allRes=clusterProfiler::merge_result(enrichResultList =allRes)
    if (Type=="KO"){
        allRes<-generat_urls(allRes,gene2ko)
    }
    write.csv(x = allRes@compareClusterResult,
            file =file.path(outDir,paste(file_name,'.csv',collapse = "")) ,
            quote = TRUE,
            row.names = TRUE)
            
    Enrichment_table  = datatable(allRes@compareClusterResult,
                                  caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',
                                                                            'Table: ', 
                                                                            htmltools::em(paste("This Table is of",paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse  = ' ')))
                                                                    ),
                                  options = list(keys = TRUE ,
                                                 scrollX = TRUE,
                                                 fixedHeader = FALSE,
                                                 fixedColumns = TRUE,
                                                 pageLength = 5,
                                                 scrollY = 300,
                                                 orderClasses=TRUE,
                                                 autoWidth = TRUE,
                                                 scroller = TRUE,
                                                 dom = 'Bfrtip',
                                                 buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                                                 deferRender = TRUE),
                                  class = 'cell-border stripe',
                                  filter = 'top',
                                  extensions = c('Buttons','FixedColumns','FixedHeader','KeyTable','Scroller'))

    original_allRes = allRes
    Simplify_title = c()
    if (Type=="GO"){
        allRes@fun<-"enrichGO"
        temp_allRes<-try(clusterProfiler::simplify(allRes, cutoff=0.7, by="p.adjust", select_fun=min),silent = T)
        if (!inherits(temp_allRes,"try-error")){
            Simplify_title = list(htmltools::h6('*Simplify:  Redundant GO Terms Were Removed From the Figure, Showing Only the Most Significant Among Very Similar (>0.7) GO Terms; For more information see GOSemSim and clusterProfiler R packages'))
            allRes=temp_allRes
            file_name=paste("Simplify",file_name,collapse = "_")
            write.csv(x = allRes@compareClusterResult,file =file.path(outDir,paste(file_name,'.csv',sep='',collapse = "")) ,quote = FALSE,row.names = TRUE)
        }
    }else{
        allRes@fun<-"enrichKEGG"
    }
    if (dim(allRes@compareClusterResult)[1]>50){
        font.size=4
    }else{
        font.size=9
    }

    if (dim(allRes@compareClusterResult)[1]>0){
        #cat(sprintf("<h4>%s</h4>", paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ") ))
        x=DOSE::dotplot(allRes,showCategory=10000,font.size=font.size)+ 
        ggplot2::ggsave(filename = file.path(outDir,paste(file_name,".pdf",sep='',collapse = "")),dpi = 600,device = "pdf",width = 20,height = 20)
        grid::grid.newpage()
        return(list(original_allRes,list(htmltools::h4(paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ")),ggplotly(x),Simplify_title,Enrichment_table)))
    }
    return(list(original_allRes,list(htmltools::h4(paste(unlist(stringi::stri_split(str = file_name,fixed='_')),collapse = " ")),Enrichment_table)))
}


plot_clusters<-function(clusters,vs_ano,color_group=c('Type','Time_int'),titles=c("Type","Time","EXP"),split_by=c(),smooth=T,X_AXIS_ORDER=NA){
    plot_list  = list()
    title_list = list()
    count=1
    for (i in sort(unique(clusters))){
        Df=data.frame()
        genes=names(clusters[clusters==i])
        for (j in genes){
          if (length(split_by)>0){
            temp=subset.data.frame(x =vs_ano,,c(split_by,color_group,j))
            colnames(temp)=c("split_by","Type","Time","EXP")
            Df=rbind(Df,temp)
          }else{
            temp=subset.data.frame(x =vs_ano,,c(color_group,j))
            colnames(temp)=c("Type","Time","EXP")
            Df=rbind(Df,temp)
          }
        }
        if (color_group[1]==color_group[2]){
          Df$Type='Trend'
        }
        if (length(X_AXIS_ORDER)>1){
            Df$Time <-factor(Df$Time,levels=intersect(X_AXIS_ORDER,unique(Df$Time)))
        }
        if (length(split_by)>0){
            title_list[count]=list(c(i,length(genes)) ) 
            plot_list[count]=list(ggplot(data=Df, aes(x=Time, y=EXP, group=Type)) + 
                                    facet_wrap(~split_by, ncol=1,scales = "free_y",strip.position = c("right"))+
                                    theme(strip.text.y = element_text(size = 7, colour = "black"))+#,face="bold" ,angle = 90))+
                                    #theme(strip.background = element_blank())+
                                    ggtitle( paste(paste("Cluster ", i  ,sep="") ,length(genes) ,sep="\n")) +
                                    #theme(plot.title = element_text(colour = "black", size = 12)) + 
                                    theme(legend.position  ="none")+
                                    xlab(titles[2]) +
                                    ylab(titles[3]) +
                                    theme(axis.title =element_text(colour = "black", size = 10) )+
                                    theme(legend.title =element_text(colour = "black", size = 10) )+
                                    theme(legend.text =element_text(colour = "black", size = 8) )+
                                    theme(axis.text.y =   element_text(colour = "black", size = 6))+
                                    theme(axis.text.x =   element_text(colour = "black", size = 6))+
                                    theme(plot.margin = unit(c(0.5,0.2,0.5,0.2),"cm")  )+
                                    #scale_color_discrete(name=titles[1])+
                                    #scale_linetype_manual(name=titles[1],values=c(1,5))+
                                    scale_x_discrete(limits=unique(Df$Time))+
                                    theme(legend.key.width =unit(3,"line")) 
                                    #scale_y_continuous(breaks=c(seq(0,10,by=2)) )
                                )
        }else{
            title_list[count]=list(c(i,length(genes)) ) 
            plot_list[count]=list(ggplot(data=Df, aes(x=Time, y=EXP, group=Type)) + 
                                    ggtitle( paste(paste("Cluster ", i  ,sep="") ,length(genes) ,sep="\n")) +
                                    #theme(plot.title = element_text(colour = "black", size = 12)) + 
                                    theme(legend.position  ="none")+
                                    xlab(titles[2]) +
                                    ylab(titles[3]) +
                                    theme(axis.title =element_text(colour = "black", size = 10) )+
                                    theme(legend.title =element_text(colour = "black", size = 10) )+
                                    theme(legend.text =element_text(colour = "black", size = 8) )+
                                    theme(axis.text.y =   element_text(colour = "black", size = 6))+
                                    theme(axis.text.x =   element_text(colour = "black", size = 6))+
                                    theme(plot.margin = unit(c(0.5,0.2,0.5,0.2),"cm")  )+
                                    #scale_color_discrete(name=titles[1])+
                                    #scale_linetype_manual(name=titles[1],values=c(1,5))+
                                    scale_x_discrete(limits=unique(Df$Time))+
                                    theme(legend.key.width = unit(3,"line")) 
                                    #scale_y_continuous(breaks=c(seq(0,10,by=2)) )
                                )
        }
        
        
        if (smooth){
            plot_list[count]=list(plot_list[[count]]+
                                    stat_smooth(method="loess", fullrange=F, size=0.5 ,aes(linetype=Type,color=Type)) 
                                )
            gp2=plot_list[count]
            res<-try(get_legend(gp2[[1]] + theme(legend.position  ="right")+guides(color=guide_legend(title=titles[1]),linetype=guide_legend(title=titles[1]))) ,silent = T)
            if (inherits(res,"try-error")){
                plot_list[count]=list(plot_list[[count]]+
                                        stat_summary(fun.y=mean, geom="point", size = 3,aes(color=Type))+
                                        stat_summary(fun.data = "mean_se", geom = "errorbar", width = .3,size = 1,aes(color=Type),show.legend = F)
                                     )
            }
        }else{
            plot_list[count]=list(plot_list[[count]]+
                                    stat_summary(fun.y=mean, geom="line", size = 1.3,aes(linetype=Type,color=Type))+
                                    stat_summary(fun.data = "mean_se", geom = "errorbar", width = .3,size = 1,aes(color=Type),show.legend = F)
                                )
        }

        count=count+1  
    }
    
    # ml_plotly = sapply(X =c(1:length(plot_list)),
                       # FUN = function(x) list(ggplotly(plot_list[[x]]) %>% 
                                                       # style(text=paste(
                                                                          # paste("Cluster:",title_list[[x]][1],sep=" ") ,
                                                                          # paste("Number of Genes:",title_list[[x]][2],sep=" ") ,
                                                                          # sep = "<br />" ),
                                                              # hoverinfo = "text")))
                       
    # ml_plotly = subplot(c(ml_plotly),
                        # nrows = ceiling(length(plot_list)/3),
                        # titleX = T,
                        # titleY  = F,
                        # shareX = T,
                        # shareY = F) %>%
                        # layout(title='Clusters',legend = list(orientation = 'h', y = -0.2))
    gp2=plot_list[1]
    if (color_group[1]==color_group[2]){
        ml<-marrangeGrob(plot_list, nrow=2, ncol=3, top=NULL)
    }else{
        legend <- get_legend(gp2[[1]] + theme(legend.position  ="right")+guides(color=guide_legend(title=titles[1]),linetype=guide_legend(title=titles[1])))
        ml<-marrangeGrob(plot_list, nrow=2, ncol=3,right=legend, top=NULL)
        
    }

    return(list(ml))#,ml_plotly))
}



plot_sheard_genes<-function(allRes,outDir,file_name){
    heatmaps=list()
    if (length(allRes)>1){
        for (cluster in unique(allRes$Cluster)){
            TEMP = na.omit(allRes[allRes$Cluster==cluster,])
            genes = unique(unlist(stringi::stri_split(paste(TEMP$geneID,sep = ,collapse = '/'),fixed = '/')))
            
            if ((length(TEMP$ID)>1) &&((length(genes)>1))){
                mat  = matrix(0, nrow = length(TEMP$ID), ncol = length(genes))
                rownames(mat) = TEMP$ID
                colnames(mat) = genes


                for (x in TEMP$ID){
                  for (y in genes){
                    mat[x,y] = length( unlist(intersect( unlist(stringi::stri_split(TEMP[TEMP$ID==x,'geneID'],fixed = '/')),y )))
                    
                  }
                }

                rownames(mat) = TEMP$Description
                
                if ((length(TEMP$ID)>20) || ((length(genes)>200))){
                    heat_map = pheatmap(mat = mat,cluster_rows = T,
                                        cluster_cols = T,
                                        silent = T,
                                        legend = F)
                
                }else{
                    if (length(unique(as.vector(mat)))==2 ){
                        color=colorRampPalette(c('white','pink'))(2)
                        mybreaks=NA
                    }else{
                        color=colorRampPalette(c('pink'))(1)
                        mybreaks=c(0,1)
                    }
                    heat_map = pheatmap(mat = mat,cluster_rows = T,
                            treeheight_col = 0,
                            treeheight_row = 0,
                            width = 5,
                            height =5,
                            cellheight = 10,
                            fontsize_row =5,
                            fontsize_col = 1,
                            main = paste('Cluster ',cluster),
                            border_color = 'white',
                            cluster_cols = T,
                            breaks = mybreaks,
                            filename = file.path(outDir,paste('Cluster',cluster,'_genes2term_',file_name,".pdf",collapse = "")),
                            color = color,
                            legend = F)
                         
                }
                write.csv(x = mat[heat_map$tree_row$order,heat_map$tree_col$order],
                      quote = T,
                      row.names = T,
                      file = file.path(outDir,paste('Cluster',cluster,'_genes2term_',file_name,".csv",collapse = "")))
        
            
                mat  = matrix(0, nrow = length(TEMP$ID), ncol = length(TEMP$ID))
                rownames(mat) = TEMP$ID
                colnames(mat) = TEMP$ID

                for (x in TEMP$ID){
                  for (y in TEMP$ID){
                    mat[x,y] =100*(2*length( unlist(intersect( unlist(stringi::stri_split(TEMP[TEMP$ID==x,'geneID'],fixed = '/')),unlist(stringi::stri_split(TEMP[TEMP$ID==y,'geneID'],fixed = '/'))))))/(length(unlist(stringi::stri_split(TEMP[TEMP$ID==x,'geneID'],fixed = '/'))) +  length(unlist(stringi::stri_split(TEMP[TEMP$ID==y,'geneID'],fixed = '/'))))
                    
                  }
                }

                rownames(mat) = TEMP$Description
                colnames(mat) = TEMP$Description
                if (length(unique(as.vector(mat)))>1 ){
                    color=colorRampPalette(rev(RColorBrewer::brewer.pal(n = 7, name ="RdYlBu") ))( 100)
                    mybreaks=seq(0,1,0.01)
                }else{
                    color=colorRampPalette(c('red'))(1)
                    mybreaks=c(0,1)
                }
                    
                if (length(TEMP$ID)>20){
                    heat_map = pheatmap(mat = mat,cluster_rows = T,
                                        main = paste('Cluster ',cluster),
                                        treeheight_col = 0,
                                        treeheight_row = 0,
                                        cluster_cols = T,
                                        silent = T,
                                        legend = T)
                
                }else{
                    heat_map = pheatmap(mat = mat,cluster_rows = T,
                                width = 5,
                                height =5,
                                treeheight_col = 0,
                                treeheight_row = 0,
                                breaks = mybreaks,
                                fontsize_row =5,
                                fontsize_col = 5,
                                main = paste('Cluster ',cluster),
                                border_color = 'white',
                                cluster_cols = T,
                                color = color,
                                filename = file.path(outDir,paste('Cluster',cluster,'_term2term_',file_name,".pdf",collapse = "")),
                                legend = T)
                }

                write.csv(x = mat[heat_map$tree_row$order,heat_map$tree_col$order],
                          quote = T,
                          row.names = T,
                          file = file.path(outDir,paste('Cluster',cluster,'_term2term_',file_name,".csv",collapse = "")))
                
                heatmap_title=htmltools::h4(paste(unlist(stringi::stri_split(str = paste('Cluster',cluster,file_name,' Terms Genes Overlap',collapse = ""),fixed='_')),collapse = " "))
                heatmaps = c(heatmaps ,list(heatmap_title))
                mat = mat[heat_map$tree_row$order,heat_map$tree_col$order]
                heatmaps = c(heatmaps ,list(plot_ly(z = mat,
                                                    x=colnames(mat),
                                                    y=rownames(mat),
                                                    colors = color,
                                                    type = "heatmap")
                                             )
                            )
            }
        }
        
    }
    return(heatmaps)
}


Run_click<-function(mat,click_path,outDir,HOMOGENEITY = 0.5){
      writeLines(text =  paste(dim(mat)[1],dim(mat)[2],sep = ' ' ),con = file.path(outDir,'clickInput.orig'))
      write.table(x = mat,append = T,file = file.path(outDir,'clickInput.orig'),sep = '\t',col.names = F)
      lines=c()
      lines = c(lines,'DATA_TYPE')
      lines = c(lines,'FP ')
      lines = c(lines,'INPUT_FILES_PREFIX')
      lines = c(lines,file.path(outDir,'clickInput '))
      lines = c(lines,'OUTPUT_FILE_PREFIX')
      lines = c(lines,file.path(outDir,'clickOutput '))
      lines = c(lines,'SIMILARITY_TYPE')
      lines = c(lines,'CORRELATION ')
      lines = c(lines,'HOMOGENEITY')
      lines = c(lines,as.character(HOMOGENEITY))
      writeLines(text =  lines,con = file.path(outDir,'params.txt'))
      system(command = paste(click_path,file.path(outDir,'params.txt'),sep = ' ') )
      clusters = read.table(file = file.path(outDir,'clickOutput.res.sol'),sep = '\t',header = F,row.names = 1)
      clusters = setNames(unlist(as.list(clusters)), row.names(clusters))
      return(clusters)
}


#####################Functions-End################################

```

## Statistical Analysis:
```{r echo = FALSE, error = TRUE, comment='', message = FALSE, warning = FALSE}

    library("ggplot2")
    library("pheatmap")
    library("mclust")
    library("factoextra")
    library("cowplot")
    library("gridExtra")
    library("plotly")
    library("clusterProfiler")
    library("DT")
    library('DESeq2')
    
    opt = params$opt
    test2do = params$test2do
    DESeqDataSet_base = params$DESeqDataSet_base
    base_out_dir = params$base_out_dir
    colData = params$colData
    countData = params$countData
    Annotation = params$Annotation
    Annotation_flag = params$Annotation_flag
    KEGG_flag = params$KEGG_flag
    ORGANISM_KEGG_flag = params$ORGANISM_KEGG_flag
    KEGG_KAAS_flag = params$KEGG_KAAS_flag
    GO_flag = params$GO_flag
    
    Original_colData   = colData
    Original_countData = countData
    
    if (!is.na(opt$Post_statistical_ALPHA)){
        FDR_PVAL_CUTOFF = opt$Post_statistical_ALPHA
    }else{
        FDR_PVAL_CUTOFF = opt$ALPHA
    }
    
    if (!is.na(opt$Post_statistical_FoldChange)){
        FC_CUTOFF = opt$Post_statistical_FoldChange #in linear scale
        FC_CUTOFF_log2 = log2(opt$Post_statistical_FoldChange) 
    }else{
        FC_CUTOFF = opt$FoldChange #in linear scale
        FC_CUTOFF_log2 = log2(opt$FoldChange) 
    }
     
    
        statistical_string = unlist(stringi::stri_split(str =  test2do,regex = ','))
        if (length(statistical_string)==3){
             htmltools::h4(sprintf("The statistical results of %s VS %s in %s:",statistical_string[2],statistical_string[3],statistical_string[1]))
        }else{
             htmltools::h4(sprintf("The statistical results of %s:",test2do))
        }
        DESeqDataSet_Results = NA
        Normalized_counts = NA
        Normalized_counts_list=c()
        DESeqDataSet=DESeqDataSet_base
        if (test2do=='LTR'){
          opt$outDir=file.path(base_out_dir,'LTR')
          dir.create(opt$outDir, showWarnings = FALSE)
          
          DESeqDataSet <- DESeq(DESeqDataSet, test="LRT",
                                reduced = as.formula(opt$LRT),
                                parallel=F)
          
          DESeqDataSet_Results <- results(DESeqDataSet,alpha = opt$ALPHA)
          opt$CONTRAST=NA
        }else if (test2do=='No_DESIGN') {
          opt$outDir=file.path(base_out_dir,'No_DESIGN')
          dir.create(opt$outDir, showWarnings = FALSE)
          opt$CONTRAST=NA
        }else if (test2do=='only_clustering'){
          opt$outDir=file.path(base_out_dir,'Only_Clustering')
          dir.create(opt$outDir, showWarnings = FALSE)
          Normalized_counts_assay = countData
          opt$CONTRAST=NA
        }else{
            opt$CONTRAST=test2do
            contrast_list = unlist(stringi::stri_split(str =  opt$CONTRAST,regex = ','))
            if (length(contrast_list)==2){
                contrast_list=c('',contrast_list)
            }
            test_name = paste(contrast_list[2],contrast_list[3],sep = '_vs_')
            opt$outDir=file.path(base_out_dir,test_name)
            dir.create(opt$outDir, showWarnings = FALSE)
            DESeqDataSet_Results <- results(DESeqDataSet,
                                            contrast     = unlist(stringi::stri_split(str = opt$CONTRAST ,regex = ",")) ,
                                            alpha        = opt$ALPHA,
                                            lfcThreshold = log2(opt$FoldChange)   )
          
        }

        if (!is.na(DESeqDataSet_Results)){
            DESeqDataSet_Results_redOrdered <- as.matrix(DESeqDataSet_Results[order(DESeqDataSet_Results$padj),])
            summary(DESeqDataSet_Results)
        }

        # Normalization
        if (!is.na(DESeqDataSet)){
            if (opt$NORMALIZATION_TYPE=='RLOG'){
                Normalized_counts <- rlog(DESeqDataSet, blind=opt$BLIND)
            }else{
                Normalized_counts <- varianceStabilizingTransformation(DESeqDataSet, blind=opt$BLIND)
            }
            Normalized_counts_list=list(Normalized_counts)
            if (!is.na(opt$removeBatchEffect)){
                if (opt$removeBatchEffect_method=="sva"){
                    if(!(all(c('sva') %in% installed.packages()))) {
                        if (Sys.getenv("CONDA_PREFIX")!=""){
                            source("http://bioconductor.org/biocLite.R")
                            try(biocLite("sva", version = "3.8"),silent = F)
                        }else{
                          cat("The Bioconductor sva package is not installed. You must install it for this script to work!")
                        }
                    } 
                    try(library("sva"),silent = F)
                    if ("package:sva" %in% search()==FALSE){
                        cat(sprintf("%s","The Bioconductor sva package is not installed!! will use limma instead"))
                        opt$removeBatchEffect_method="limma"
                    }
                }
                BatchEffects = unlist(stringi::stri_split(str = opt$removeBatchEffect ,regex = ','))
                if (opt$removeBatchEffect_method=="sva"){
                        if (length(BatchEffects)>1){
                            cat(sprintf("%s","It is Not possible to use more then one batch effect using the sva package, will use only the first one!!"))
                        }
                        DESIGN_list = unlist(stringi::stri_split( stringi::stri_replace(str = opt$DESIGN,
                                                                                   regex =' |~',
                                                                                   mode = 'all',
                                                                                   replacement = ''),
                                                            fixed = '+'))
                        New_DESIGN =paste0('~',paste(DESIGN_list[DESIGN_list!=BatchEffects[1]],collapse ='+'))
                        
                        modcombat = model.matrix( as.formula(New_DESIGN) , data=Original_colData)
                        combat_edata = ComBat(dat = assay(Normalized_counts),
                                              batch = Original_colData[,BatchEffects[1]],
                                              mod = modcombat,
                                              par.prior = T,
                                              mean.only=F)
                        assay(Normalized_counts) = combat_edata
                        
                }else{
                
                    if (length(BatchEffects)>1){
                            assay(Normalized_counts) = limma::removeBatchEffect(assay(Normalized_counts),
                                                                                batch = Normalized_counts@colData[,BatchEffects[1]],
                                                                                batch2= Normalized_counts@colData[,BatchEffects[2]])
                    }else{
                            assay(Normalized_counts) = limma::removeBatchEffect(assay(Normalized_counts),
                                                                                batch = Normalized_counts@colData[,BatchEffects[1]])
                    }
                }
                Normalized_counts_list = c(Normalized_counts_list,Normalized_counts)
            }
            
            Normalized_counts_assay = assay(Normalized_counts)
        }


        ##################DeSeq-END####################################
```





```{r echo = FALSE, error = TRUE, comment='', message = FALSE, warning = FALSE,results='asis'}
        ##################DeSeq-Print Results As Is (Vered 14.6.2018)##
        if (!is.na(DESeqDataSet_Results)){
            Results_for_print = as.data.frame(DESeqDataSet_Results)

            if (!is.na(opt$LRT)){
                Results_for_print = Results_for_print[,c('pvalue','padj')]
                test_name = 'LRT'

            }else{
                if (!is.na(opt$CONTRAST)){
                    Results_for_print = Results_for_print[,c('log2FoldChange','pvalue','padj')]
                    contrast_list = unlist(stringi::stri_split(str =  opt$CONTRAST,regex = ','))
                    if (length(contrast_list)==2){
                        contrast_list=c('',contrast_list)
                    }
                    test_name = paste(contrast_list[2],contrast_list[3],sep = '.vs.')
                }
            }

            colnames(Results_for_print) = unlist(lapply(colnames(Results_for_print), function(x)  paste(x, test_name,sep = '.')) ) 
            write.table(Results_for_print,
                        file = file.path(opt$outDir,paste(test_name,'txt', sep = '.')) ,
                        quote = F,
                        sep = "\t",
                        col.names=NA)
        }
        ##################DeSeq-Print Results END######################

        ##################Print Normalized counts######################
        if (!is.na(Normalized_counts)){
            write.table(Normalized_counts_assay,
                        file = file.path(opt$outDir,paste(test_name,opt$NORMALIZATION_TYPE,'Normalized_counts.txt', sep = '_')) ,
                        quote = F,
                        sep = "\t")
           
            
            if (!is.na(Annotation)) {
                  Normalized_counts_DATA = merge.data.frame(Normalized_counts_assay,Annotation,by="row.names",all.x = T,sort = F)
                  rownames(Normalized_counts_DATA) = Normalized_counts_DATA$Row.names
                  Normalized_counts_DATA$Row.names=NULL
                  Annotation_TEXT = ' and Annotation'
            }else{
                Normalized_counts_DATA = Normalized_counts_assay
                Annotation_TEXT = ''
            }
            cat(sprintf("<h4>%s</h4>",paste("The Next Table is of ",test_name,opt$NORMALIZATION_TYPE,'Normalized Counts',Annotation_TEXT, sep = ' ')))
            Normalized_counts_table  =  datatable(Normalized_counts_DATA,
                                                  caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',
                                                                                            'Table: ', 
                                                                                            htmltools::em(paste("This Table is of ",test_name,opt$NORMALIZATION_TYPE,'Normalized Counts',Annotation_TEXT, sep = ' '))
                                                                                    ),
                                                  options = list(keys = TRUE ,
                                                                 scrollX = TRUE,
                                                                 fixedHeader = FALSE,
                                                                 fixedColumns = TRUE,
                                                                 pageLength = 5,
                                                                 scrollY = 300,
                                                                 orderClasses=TRUE,
                                                                 autoWidth = TRUE,
                                                                 scroller = TRUE,
                                                                 dom = 'Bfrtip',
                                                                 buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                                                                 deferRender = TRUE),
                                                  class = 'cell-border stripe',
                                                  filter = 'top',
                                                  extensions = c('Buttons','FixedColumns','FixedHeader','KeyTable','Scroller'))
     
            
            htmltools::tagList(list(Normalized_counts_table))
        }
        ##################Print Normalized counts END#######################

        ##################Volcano plot and MA plot Vered##################
        MA_Volcano_plot = NA
        MA_plot = NA
        Volcano_plot = NA 
        
        
        if (!is.na(DESeqDataSet_Results)){

            topT <- as.data.frame(DESeqDataSet_Results)

            if (!is.na(opt$LRT)){
              cat('No Volcano plot for LTR')
            }else{
                if (!is.na(opt$CONTRAST)){
                    cat(sprintf("<h4>%s</h4>",paste("Volcano Plot of ",test_name, sep = ' ')))
                    contrast_list = unlist(stringi::stri_split(str =  opt$CONTRAST,regex = ','))
                    if (length(contrast_list)==2){
                        contrast_list=c('',contrast_list)
                    }
                    test_name = paste(contrast_list[2],contrast_list[3],sep = ' vs ')
                    plotTitle = paste('Volcano Plot (', test_name, ')', sep="")
                   
                    par(mar=c(5,5,5,5), cex=1.0, cex.main=1.4, cex.axis=1.4, cex.lab=1.4)

                    topT <- na.omit(as.data.frame(DESeqDataSet_Results))
                    #Adjusted P values (FDR Q values)
                    with(topT, plot(log2FoldChange, -log10(padj), pch=20, main=plotTitle, cex=1.0, xlab=bquote(~Log[2]~fold~change), ylab=bquote(~-log[10]~'FDR p-'~value)))

                    with(subset(topT, padj<FDR_PVAL_CUTOFF & abs(log2FoldChange)>FC_CUTOFF_log2), points(log2FoldChange, -log10(padj), pch=20, col="red", cex=0.5))

                    #Add lines for absolute adjusted p-value and FC cutoffs 
                    abline(v=-FC_CUTOFF_log2, col="black", lty=4, lwd=2.0)
                    abline(v=FC_CUTOFF_log2, col="black", lty=4, lwd=2.0)
                    if (length(topT$padj[topT$padj<FDR_PVAL_CUTOFF])>0){
                        abline(h=-log10(max(topT$padj[topT$padj<FDR_PVAL_CUTOFF], na.rm=TRUE)), col="black", lty=4, lwd=FC_CUTOFF_log2)
                    }
                    Volcano_plot_ = recordPlot()

                    pdf(file.path(opt$outDir,paste(c(plotTitle,".pdf"),collapse ="")))
                    replayPlot(Volcano_plot_)
                    trash = dev.off()
                    
                    Volcano_plot=plot_ly(topT, x = ~log2FoldChange, y = ~-log10(padj),type='scatter', mode='markers',
                                         showlegend = FALSE,
                                         text=~paste(row.names(topT),
                                         paste("FDR p− value:",padj,sep=" ") ,
                                         paste("log2FoldChange:",log2FoldChange,sep=" ") ,
                                         sep = "<br />" ),
                                         hoverinfo = "text",
                                         color = (~padj<FDR_PVAL_CUTOFF & abs(log2FoldChange)>FC_CUTOFF_log2),
                                         colors= c('black','red'),
                                         name=row.names(topT) ) %>%
                                 add_markers() %>%
                                 layout(title = paste("Volcano Plot of ",test_name, sep = ' '),
                                        xaxis = list(title = 'Log2 Fold Change'),
                                        yaxis = list(title = 'log10 FDR p− value')) 
                                        
                                        
                    MA_plot=plot_ly(topT, x = ~baseMean , y = ~log2FoldChange,type='scatter', mode='markers',
                                    showlegend = FALSE,
                                    text=~paste(row.names(topT),
                                    paste("FDR p− value:",padj,sep=" ") ,
                                    paste("log2FoldChange:",log2FoldChange,sep=" ") ,
                                    paste("Mean of Normalized Counts:",baseMean,sep=" ") ,
                                    sep = "<br />" ),
                                    hoverinfo = "text",
                                    color = (~padj<FDR_PVAL_CUTOFF & abs(log2FoldChange)>FC_CUTOFF_log2),
                                    colors= c('black','red'),
                                    name=row.names(topT) ) %>%
                            add_markers() %>%
                            layout(title = paste("MA Plot of ",test_name, sep = ' '),
                                   xaxis = list(title = 'Mean of Normalized Counts',type = "log"),
                                   yaxis = list(title = 'Log2 Fold Change')) 
                    
                    MA_Volcano_plot =   plot_ly(topT, x = ~log2FoldChange, z = ~-log10(padj), y = ~baseMean ,
                                            showlegend = FALSE,
                                            text=~paste(row.names(topT),
                                                        paste("FDR p− value:",padj,sep=" ") ,
                                                        paste("log2FoldChange:",log2FoldChange,sep=" ") ,
                                                        paste("Mean of Normalized Counts:",baseMean,sep=" ") ,
                                                        sep = "<br />" ),
                                            hoverinfo = "text",
                                            color = (~padj<FDR_PVAL_CUTOFF & abs(log2FoldChange)>FC_CUTOFF_log2),
                                            colors= c('black','red'),
                                            name=row.names(topT) ) %>%
                                    add_markers() %>%
                                    layout(title = paste("3D MA and Volcano Plots of ",test_name, sep = ' '),
                                           scene = list(xaxis = list(title = 'Log2 Fold Change' ,showspikes = FALSE , autorange = T, showgrid = TRUE),
                                                        zaxis = list(title = 'log10 FDR p− value', showspikes = FALSE ,autorange = T, showgrid = TRUE),
                                                        yaxis = list(title = 'Mean of Normalized Counts', type = "log",showspikes = FALSE , autorange = T, showgrid = TRUE))) 
                
                }
            }

            cat(sprintf("<h4>%s</h4>",paste("MA Plot of ",test_name, sep = ' ')))
            plotTitle = paste('MA Plot (', test_name, ')', sep="")
            plotMA(DESeqDataSet_Results, alpha=FDR_PVAL_CUTOFF, colNonSig = 'blue', ylim=c(-10,10), main=plotTitle)
            abline(h=c(-FC_CUTOFF_log2,FC_CUTOFF_log2), col="red")
            MA_plot_ = recordPlot()
            trash = pdf(file.path(opt$outDir,paste(c(plotTitle,".pdf"),collapse ="")))
            replayPlot(MA_plot_)
            trash = dev.off()
        }
        
        
        # cat(sprintf("<h4>%s</h4>",paste("Volcano Plot of ",test_name, sep = ' ')))
        # grid::grid.newpage()
        # Volcano_plot
        # grid::grid.newpage()
        
        # cat(sprintf("<h4>%s</h4>",paste("MA Plot of ",test_name, sep = ' ')))
        # grid::grid.newpage()
        # MA_plot
        # grid::grid.newpage()
        
        
    ############################Original-PCA-START##############################################
    
        cat(sprintf("<h2>%s</h2>", 'PCA Plots:'))
        if (length(Normalized_counts_list)==2){
            PCA_Normalized_counts = Normalized_counts_list[[1]]
            cat(sprintf("<h3>%s</h3>", 'PCA Plot Using Original Data:'))
        }else if (length(Normalized_counts_list)==1){
            PCA_Normalized_counts = Normalized_counts_list[[1]]
        }else if (length(Normalized_counts_list)==0){
            PCA_Normalized_counts = NA
        }
        
    ##################PCA-TOP500####################################
        if (!is.na(PCA_Normalized_counts)){
            intgroup=c(opt$PCA_COLOR,opt$PCA_SHAPE,opt$PCA_SIZE)
            intgroup=intgroup[!is.na(intgroup)]
            PCA_data <- plotPCA(PCA_Normalized_counts, intgroup=make.names(intgroup), returnData=TRUE,ntop=500)
            percentVar <- round(100 * attr(PCA_data, "percentVar"))

            if (is.na(opt$PCA_COLOR)){
              opt$PCA_COLOR='name'
            }

            if (is.na(opt$PCA_SHAPE)){
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c('TOP500_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c('TOP500_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA of the TOP 500 Most Variable Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot
            }else{
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c('TOP500_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c('TOP500_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("shape:",opt$PCA_SHAPE,get(make.names(opt$PCA_SHAPE)),sep=" ") ,
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               sizes = c(3,15),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter',
                                                                color="white"),
                                               opacity = 0.8)%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA of the TOP 500 Most Variable Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot
            }
        }
        ##################PCA-TOP500-END####################################

        # ##################PCA-ALL####################################
        if (!is.na(PCA_Normalized_counts)){
            intgroup=c(opt$PCA_COLOR,opt$PCA_SHAPE,opt$PCA_SIZE)
            intgroup=intgroup[!is.na(intgroup)]
            PCA_data <- plotPCA(PCA_Normalized_counts, intgroup=make.names(intgroup), returnData=TRUE,ntop='all')
            percentVar <- round(100 * attr(PCA_data, "percentVar"))

            if (is.na(opt$PCA_COLOR)){
                opt$PCA_COLOR='name'
            }

            if (is.na(opt$PCA_SHAPE)){
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c('ALL_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c('ALL_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot_ALL = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA Using All Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot_ALL
            }else{
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c('ALL_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
              
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c('ALL_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot_ALL = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("shape:",opt$PCA_SHAPE,get(make.names(opt$PCA_SHAPE)),sep=" ") ,
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               sizes = c(3,15),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter',
                                                                color="white"),
                                               opacity = 0.8)%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA Using All Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot_ALL
            }
        }
        # ##################PCA-END####################################
        
    ############################Original-PCA-ENDS##############################################




    ############################Batch-Effect-Corrected-PCA-START##############################################
    
    if (length(Normalized_counts_list)==2){
        PCA_Normalized_counts = Normalized_counts_list[[2]]
        cat(sprintf("<h3>%s</h3>", 'PCA Plot Using Batch Effect Corrected Data:'))
        extra_string="Batch_Effect_Corrected_"
    }        
        ##################PCA-TOP500####################################
        if (length(Normalized_counts_list)==2){
            intgroup=c(opt$PCA_COLOR,opt$PCA_SHAPE,opt$PCA_SIZE)
            intgroup=intgroup[!is.na(intgroup)]
            PCA_data <- plotPCA(PCA_Normalized_counts, intgroup=make.names(intgroup), returnData=TRUE,ntop=500)
            percentVar <- round(100 * attr(PCA_data, "percentVar"))

            if (is.na(opt$PCA_COLOR)){
              opt$PCA_COLOR='name'
            }

            if (is.na(opt$PCA_SHAPE)){
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c(extra_string,'TOP500_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c(extra_string,'TOP500_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA of the TOP 500 Most Variable Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot
            }else{
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c(extra_string,'TOP500_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c(extra_string,'TOP500_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("shape:",opt$PCA_SHAPE,get(make.names(opt$PCA_SHAPE)),sep=" ") ,
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               sizes = c(3,15),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter',
                                                                color="white"),
                                               opacity = 0.8)%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA of the TOP 500 Most Variable Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot
            }
        }
        ##################PCA-TOP500-END####################################

        # ##################PCA-ALL####################################
        if (length(Normalized_counts_list)==2){
            intgroup=c(opt$PCA_COLOR,opt$PCA_SHAPE,opt$PCA_SIZE)
            intgroup=intgroup[!is.na(intgroup)]
            PCA_data <- plotPCA(PCA_Normalized_counts, intgroup=make.names(intgroup), returnData=TRUE,ntop='all')
            percentVar <- round(100 * attr(PCA_data, "percentVar"))

            if (is.na(opt$PCA_COLOR)){
                opt$PCA_COLOR='name'
            }

            if (is.na(opt$PCA_SHAPE)){
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c(extra_string,'ALL_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")

                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c(extra_string,'ALL_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot_ALL = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA Using All Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot_ALL
            }else{
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC2', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    scale_shape_discrete(solid=F)+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c(extra_string,'ALL_PCA_pc1_pc2',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
              
                pca_res=ggplot(PCA_data, aes_string('PC1', 'PC3', color=make.names(opt$PCA_COLOR),shape=make.names(opt$PCA_SHAPE),size=make.names(opt$PCA_SIZE)) )+
                    geom_count()+
                    guides(color=guide_legend(order = 1 ,title=opt$PCA_COLOR))+
                    guides(shape=guide_legend(order  = 2,title=opt$PCA_SHAPE))+
                    guides(size=guide_legend(order  = 2,title=opt$PCA_SIZE))+
                    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
                    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
                    coord_fixed()
                ggsave(file.path(opt$outDir,paste(c(extra_string,'ALL_PCA_pc1_pc3',".pdf"),collapse ="")),pca_res,dpi = 600, width = 6.99, height =6.99, units = "in")
                
                PCA_plot_ALL = plot_ly(PCA_data, x = ~PC1, y = ~PC3, z = ~PC2,
                                    text=~paste(row.names(PCA_data),
                                                 paste("shape:",opt$PCA_SHAPE,get(make.names(opt$PCA_SHAPE)),sep=" ") ,
                                                 paste("color:",opt$PCA_COLOR,get(make.names(opt$PCA_COLOR)),sep=" ") ,
                                                 paste("size:",opt$PCA_SIZE,get(make.names(opt$PCA_SIZE)),sep=" ") ,
                                                 sep = "<br />" ),
                                    hoverinfo = "text")%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               sizes = c(3,15),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter',
                                                                color="white"),
                                               opacity = 0.8)%>%
                                    add_trace( mode="markers",
                                               visible ="legendonly",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               opacity = 1)%>%
                                    add_trace( mode="markers",
                                               type='scatter3d', x = ~PC1, y = ~PC3, z = ~PC2,
                                               symbol = ~get(make.names((opt$PCA_SHAPE))),
                                               symbols = c("circle","square","diamond","cross","x"),
                                               size  = ~get(make.names((opt$PCA_SIZE))),
                                               sizes = c(3,15),
                                               name=row.names(PCA_data),
                                               color=~get(make.names(opt$PCA_COLOR)),
                                               marker = list( line=list(color="black",width = 1),
                                                                sizemode = 'diameter'
                                                            ),
                                               showlegend =F,
                                               opacity = 0.8)%>%
                                    layout(title = 'PCA Using All Genes',
                                           scene = list(xaxis = list(title = paste0("PC1: ",percentVar[1],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        yaxis = list(title = paste0("PC3: ",percentVar[3],"% variance"), showspikes = FALSE ,autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE),
                                                        zaxis = list(title = paste0("PC2: ",percentVar[2],"% variance"),showspikes = FALSE , autorange = TRUE, showgrid = TRUE, zeroline = FALSE, showline = FALSE, autotick = TRUE, ticks = '', showticklabels = FALSE))) 
                PCA_plot_ALL
            }
        }
        # ##################PCA-END####################################
        
    ############################Batch-Effect-Corrected-PCA-ENDS##############################################





        ##################Plot Counts################################    
        if (!is.na(Normalized_counts)){
            plot_list = list()
            figure_count = 1
            if (!is.na(opt$GENES_PLOT)&(!is.na(opt$X_AXIS)   )){
                intgroup=c(opt$X_AXIS,opt$GROUP)
                intgroup=intgroup[!is.na(intgroup)]
                X_AXIS=opt$X_AXIS
                if (is.na(opt$GROUP)){
                    GROUP=opt$X_AXIS
                }else{
                    GROUP=opt$GROUP
                }
                if (is.na(opt$SPLIT_BY)){
                    
                    for (gene in unlist(stringi::stri_split(str =  opt$GENES_PLOT,regex = ","))){
                        data=plotCounts(DESeqDataSet, gene=gene,transform=F, intgroup=make.names(intgroup),returnData=TRUE)
                        p=ggplot(data, aes_string(make.names(X_AXIS), 'count',color=make.names(GROUP), group=make.names(GROUP))) +
                        ggtitle(paste("Gene ID : ",  gene  ,sep="\n")) +
                        theme(legend.position  ="none")+
                        geom_point(size=4)+
                        geom_boxplot() +
                        scale_shape_discrete(solid=F)+
                        geom_smooth(method="gam", fullrange=F, size=0.5)
                        ggsave(file.path(opt$outDir,paste(c('Count_plot_',gene,".pdf"),collapse ="")),p,dpi = 600, width = 6.99, height =6.99, units = "in")
                        plot_list[figure_count] <- list(p)
                        figure_count = figure_count + 1
                    }
                }else{
                    
                    for (gene in unlist(stringi::stri_split(str =  opt$GENES_PLOT,regex = ","))){
                        data=plotCounts(DESeqDataSet, gene=gene,transform=F, intgroup=make.names(intgroup),returnData=TRUE)
                        p=ggplot(data, aes_string(make.names(X_AXIS), 'count',color=make.names(GROUP), group=make.names(GROUP))) +
                        ggtitle(paste("Gene ID : ",  gene  ,sep="\n")) +
                        theme(legend.position  ="none")+
                        facet_wrap(~opt$SPLIT_BY, ncol=1,scales = "free_y",strip.position = c("right"))+
                        geom_point(size=4)+
                        geom_boxplot() +
                        scale_shape_discrete(solid=F)+
                        stat_smooth(method="auto", fullrange=F, size=0.5)
                        ggsave(file.path(opt$outDir,paste(c('Count_plot_',gene,".pdf"),collapse ="")),p,dpi = 600, width = 6.99, height =6.99, units = "in")
                        plot_list[figure_count] <- list(p)
                        figure_count = figure_count + 1
                    }
                    
                }
            }
            if (length(plot_list)>0){
                cat(sprintf("<h2>%s</h2>", 'Count Plots:'))
                grid::grid.newpage()
                gp2 = plot_list[1]
                legend <- get_legend(gp2[[1]] + theme(legend.position  ="right"))
                grid::grid.draw(marrangeGrob(plot_list, nrow=1, ncol=2, top=legend))
                grid::grid.newpage()
            }
        }
        ##################Plot Counts-END#############################    

        ##################Clustering##################################    
        cat(sprintf("<h2>%s</h2>", 'Clustering Analysis:'))
        main_plot_list  = list()
        up_reg   = c()
        down_reg = c()
        if (!is.na(opt$significant_genes)){ 
            sig.genes = unlist(stringi::stri_split(str = opt$significant_genes,regex = ','))
            Normalized_counts_assay = Normalized_counts_assay[sig.genes,]
            cat(sprintf("<h3>%s</h3>", 'NOTE: Clustering Analysis is done on the user defined significant genes !!!!'))
        }else if (!is.na(DESeqDataSet_Results)){
            #sig.genes = rownames(DESeqDataSet_Results_redOrdered[(DESeqDataSet_Results_redOrdered[,"padj"]<FDR_PVAL_CUTOFF)&(!is.na(DESeqDataSet_Results_redOrdered[,"padj"])),])
            up_reg    = rownames(DESeqDataSet_Results_redOrdered[(DESeqDataSet_Results_redOrdered[,"log2FoldChange"]>FC_CUTOFF_log2)&(DESeqDataSet_Results_redOrdered[,"padj"]<FDR_PVAL_CUTOFF)&(!is.na(DESeqDataSet_Results_redOrdered[,"padj"])),])
            down_reg  = rownames(DESeqDataSet_Results_redOrdered[(DESeqDataSet_Results_redOrdered[,"log2FoldChange"]<FC_CUTOFF_log2)&(DESeqDataSet_Results_redOrdered[,"padj"]<FDR_PVAL_CUTOFF)&(!is.na(DESeqDataSet_Results_redOrdered[,"padj"])),])
            sig.genes = c(up_reg,down_reg)
        }else{
            sig.genes = rownames(countData)
            cat(sprintf("<h3>%s</h3>", 'NOTE: Clustering Analysis is done on all input genes !!!!'))
        }

        if (!is.na(opt$X_AXIS)){

            if (length(sig.genes)>0){

                X_AXIS=opt$X_AXIS
                if (is.na(opt$GROUP)){
                    GROUP=X_AXIS
                }else{
                    GROUP=opt$GROUP
                }
                
                if (is.na(opt$SPLIT_BY)){
                    if (!is.na(opt$CONTRAST)){
                        if (opt$SPLIT_BY_CONTRAST){
                            contrast_list_split = unlist(stringi::stri_split(str =  opt$CONTRAST,regex = ','))
                            if (length(contrast_list_split)==3){
                                colData = Original_colData[(Original_colData[contrast_list_split[1]]==contrast_list_split[2]) | (Original_colData[contrast_list_split[1]]==contrast_list_split[3]),]
                                
                                if (length(unique(colData[,X_AXIS]))==1){
                                    if (length(unique(colData[,GROUP]))>1){
                                        temp_X_AXIS = X_AXIS
                                        X_AXIS      = GROUP
                                        GROUP       = temp_X_AXIS
                                        cat(sprintf("<h4>%s%s%s%s%s</h4>",
                                                    'NOTE: Since there is only one group in "',
                                                    X_AXIS,
                                                    '" the X Axis will be replace with the grouping category "',
                                                    GROUP,
                                                    '"'))
                                    }
                                }
                            }
                        }
                    }
                }
                
                if (X_AXIS!=GROUP){
                    if (is.na(opt$SPLIT_BY)){
                        Normalized_counts_Annotated=merge(colData[c(X_AXIS,GROUP)],t(Normalized_counts_assay),all.x = T ,by="row.names",sort=F)
                        SPLIT_BY=opt$SPLIT_BY
                        Normalized_counts_Annotated_mean=aggregate.data.frame(x = Normalized_counts_Annotated,by = c(Normalized_counts_Annotated[GROUP],Normalized_counts_Annotated[X_AXIS]),FUN = mean)
                        rownames(Normalized_counts_Annotated_mean)=paste(unlist(Normalized_counts_Annotated_mean[GROUP]),unlist(Normalized_counts_Annotated_mean[X_AXIS]))
                        Normalized_counts_Annotated_mean=Normalized_counts_Annotated_mean[order(rownames(Normalized_counts_Annotated_mean)),]
                        Normalized_counts_Annotated_mean$Row.names=NULL
                        Normalized_counts_Annotated_mean[unique(c(X_AXIS,GROUP))]=NULL
                        Normalized_counts_Annotated_mean[unique(c(X_AXIS,GROUP))]=NULL
                        
                        Heatmap_Normalized_counts_Annotated=Normalized_counts_Annotated
                        rownames(Heatmap_Normalized_counts_Annotated)=make.unique(paste(unlist(Heatmap_Normalized_counts_Annotated[GROUP]),
                                                                                        unlist(Heatmap_Normalized_counts_Annotated[X_AXIS]),
                                                                                        unlist(Heatmap_Normalized_counts_Annotated['Row.names'])),
                                                                                 sep=' ')
                        Heatmap_Normalized_counts_Annotated=Heatmap_Normalized_counts_Annotated[order(rownames(Heatmap_Normalized_counts_Annotated)),]
                        Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,GROUP))]=NULL
                        Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,GROUP))]=NULL

                    }else{
                        Normalized_counts_Annotated=merge(colData[unique(c(X_AXIS,GROUP,opt$SPLIT_BY))],t(Normalized_counts_assay),all.x = T ,by="row.names",sort=F)
                        SPLIT_BY=unlist(as.list(unique(Normalized_counts_Annotated[opt$SPLIT_BY])))
                        Normalized_counts_Annotated_mean=aggregate.data.frame(x = Normalized_counts_Annotated,by = c(Normalized_counts_Annotated[GROUP],Normalized_counts_Annotated[X_AXIS]),FUN = mean)
                        rownames(Normalized_counts_Annotated_mean)=paste(unlist(Normalized_counts_Annotated_mean[GROUP]),unlist(Normalized_counts_Annotated_mean[X_AXIS]))
                        Normalized_counts_Annotated_mean=Normalized_counts_Annotated_mean[order(rownames(Normalized_counts_Annotated_mean)),]
                        SPLIT_BY_col=Normalized_counts_Annotated_mean[opt$SPLIT_BY]
                        Normalized_counts_Annotated_mean$Row.names=NULL
                        Normalized_counts_Annotated_mean[unique(c(X_AXIS,GROUP,opt$SPLIT_BY))]=NULL
                        Normalized_counts_Annotated_mean[unique(c(X_AXIS,GROUP,opt$SPLIT_BY))]=NULL
                        
                        Heatmap_Normalized_counts_Annotated=Normalized_counts_Annotated
                        rownames(Heatmap_Normalized_counts_Annotated)=make.unique(paste(unlist(Heatmap_Normalized_counts_Annotated[GROUP]),
                                                                                        unlist(Heatmap_Normalized_counts_Annotated[X_AXIS]),
                                                                                        unlist(Heatmap_Normalized_counts_Annotated['Row.names'])),
                                                                                 sep=' ')
                        Heatmap_Normalized_counts_Annotated=Heatmap_Normalized_counts_Annotated[order(rownames(Heatmap_Normalized_counts_Annotated)),]
                        Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,GROUP,opt$SPLIT_BY))]=NULL
                        Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,GROUP,opt$SPLIT_BY))]=NULL
                    }

                }else{
                    if (is.na(opt$SPLIT_BY)){
                        Normalized_counts_Annotated=merge(colData[c(X_AXIS)],t(Normalized_counts_assay),all.x = T,by="row.names",sort=F)
                        SPLIT_BY=opt$SPLIT_BY
                        Normalized_counts_Annotated_mean=aggregate.data.frame(x = Normalized_counts_Annotated,by = Normalized_counts_Annotated[X_AXIS],FUN = mean)
                        rownames(Normalized_counts_Annotated_mean)=unlist(Normalized_counts_Annotated_mean[X_AXIS])
                        Normalized_counts_Annotated_mean=Normalized_counts_Annotated_mean[order(rownames(Normalized_counts_Annotated_mean)),]
                        Normalized_counts_Annotated_mean[X_AXIS]=NULL
                        Normalized_counts_Annotated_mean[X_AXIS]=NULL
                        Normalized_counts_Annotated_mean$Row.names=NULL
                        
                        Heatmap_Normalized_counts_Annotated=Normalized_counts_Annotated
                        rownames(Heatmap_Normalized_counts_Annotated)=make.unique(as.character(paste(unlist(Heatmap_Normalized_counts_Annotated[X_AXIS]),
                                                                                                     unlist(Heatmap_Normalized_counts_Annotated['Row.names']))) ,
                                                                                 sep=' ')
                        Heatmap_Normalized_counts_Annotated=Heatmap_Normalized_counts_Annotated[order(rownames(Heatmap_Normalized_counts_Annotated)),]
                        Heatmap_Normalized_counts_Annotated[X_AXIS]=NULL
                        Heatmap_Normalized_counts_Annotated[X_AXIS]=NULL

                      
                    }else{
                        Normalized_counts_Annotated=merge(colData[unique(c(X_AXIS,opt$SPLIT_BY))],t(Normalized_counts_assay),all.x = T,by="row.names",sort=F)
                        SPLIT_BY=unlist(as.list(unique(Normalized_counts_Annotated[opt$SPLIT_BY])))
                        Normalized_counts_Annotated_mean=aggregate.data.frame(x = Normalized_counts_Annotated,by = Normalized_counts_Annotated[X_AXIS],FUN = mean)
                        rownames(Normalized_counts_Annotated_mean)=unlist(Normalized_counts_Annotated_mean[X_AXIS])
                        Normalized_counts_Annotated_mean=Normalized_counts_Annotated_mean[order(rownames(Normalized_counts_Annotated_mean)),]
                        SPLIT_BY_col=Normalized_counts_Annotated_mean[opt$SPLIT_BY]
                        Normalized_counts_Annotated_mean[unique(c(X_AXIS,opt$SPLIT_BY))]=NULL
                        Normalized_counts_Annotated_mean[unique(c(X_AXIS,opt$SPLIT_BY))]=NULL
                        Normalized_counts_Annotated_mean$Row.names=NULL
                        
                        Heatmap_Normalized_counts_Annotated=Normalized_counts_Annotated
                        rownames(Heatmap_Normalized_counts_Annotated)=make.unique(as.character( paste( unlist(Heatmap_Normalized_counts_Annotated[X_AXIS]),
                                                                                                       unlist(Heatmap_Normalized_counts_Annotated['Row.names']))),
                                                                                 sep=' ')
                        Heatmap_Normalized_counts_Annotated=Heatmap_Normalized_counts_Annotated[order(rownames(Heatmap_Normalized_counts_Annotated)),]
                        Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,opt$SPLIT_BY))]=NULL
                        Heatmap_Normalized_counts_Annotated[unique(c(X_AXIS,opt$SPLIT_BY))]=NULL
                    }
                    
                    
                }

                Heatmap_Normalized_counts_Annotated=t(Heatmap_Normalized_counts_Annotated)
                
                for (SPLIT in SPLIT_BY){ 
                    if (is.na(SPLIT)){
                        SPLIT_Normalized_counts_Annotated_mean=t(Normalized_counts_Annotated_mean)
                        Heatmap_Normalized_counts_Annotated_mean=SPLIT_Normalized_counts_Annotated_mean
                        SPLIT=''
                        SPLIT_Normalized_counts_Annotated=Normalized_counts_Annotated
                    }else{
                        SPLIT_Normalized_counts_Annotated_mean=Normalized_counts_Annotated_mean
                        SPLIT_Normalized_counts_Annotated_mean=SPLIT_Normalized_counts_Annotated_mean[SPLIT_BY_col==SPLIT, ]
                        SPLIT_Normalized_counts_Annotated_mean=t(SPLIT_Normalized_counts_Annotated_mean)
                        Heatmap_Normalized_counts_Annotated_mean=t(Normalized_counts_Annotated_mean)
                        SPLIT_Normalized_counts_Annotated=Normalized_counts_Annotated[Normalized_counts_Annotated[opt$SPLIT_BY]==SPLIT, ]
                    }   


                    SPLIT_Normalized_counts_Annotated_mean=SPLIT_Normalized_counts_Annotated_mean[sig.genes,]

                    no_var=names(which( apply(SPLIT_Normalized_counts_Annotated_mean,MARGIN = 1,FUN = sd)==0))
                    if (length(no_var)>0){
                      SPLIT_Normalized_counts_Annotated_mean=SPLIT_Normalized_counts_Annotated_mean[!(row.names(SPLIT_Normalized_counts_Annotated_mean)  %in% no_var),]
                    }

                    
                    
                    if (opt$stand){
                      SPLIT_Normalized_counts_Annotated_mean = t(scale(t(SPLIT_Normalized_counts_Annotated_mean)))
                      SPLIT_Normalized_counts_Annotated_mean = apply(SPLIT_Normalized_counts_Annotated_mean,
                                                                     MARGIN = c(1,2),
                                                                     FUN = function(x) round(x,digits = 5))
                    }
                    if (sum(duplicated(SPLIT_Normalized_counts_Annotated_mean)==F)>1){
                        if (nrow(SPLIT_Normalized_counts_Annotated_mean)>2) {
                           
                            
                            if (nrow(SPLIT_Normalized_counts_Annotated_mean)<=opt$k.max) {
                                k.max=nrow(SPLIT_Normalized_counts_Annotated_mean)-1
                            }else{
                                k.max=opt$k.max
                            }
                            if ((opt$FUNcluster=='click')&(!is.na(opt$CLICK_PATH))){
                                clusters = Run_click(mat =as.matrix(SPLIT_Normalized_counts_Annotated_mean),click_path = opt$CLICK_PATH,outDir = opt$outDir,HOMOGENEITY = opt$CLICK_HOMOGENEITY)
                            }else{
                                if (opt$Mclust){
                                    Fit_Mclust <- Mclust( as.matrix(SPLIT_Normalized_counts_Annotated_mean) ,G=1:k.max,modelNames = mclust.options("emModelNames"))
                                    Number_Of_Clusters=Fit_Mclust$G
                                    Clustering <- eclust(as.matrix(SPLIT_Normalized_counts_Annotated_mean),
                                                       stand =F, 
                                                       FUNcluster= opt$FUNcluster,
                                                       hc_metric =opt$hc_metric, 
                                                       graph = FALSE,
                                                       hc_method = opt$hc_method, 
                                                       k=Number_Of_Clusters ) 
                                    clusters=Clustering$cluster
                                }else{

                                    Clustering <- eclust(as.matrix(SPLIT_Normalized_counts_Annotated_mean),stand =F,
                                                       FUNcluster= opt$FUNcluster,
                                                       hc_metric =opt$hc_metric,
                                                       graph = FALSE,
                                                       hc_method = opt$hc_method,
                                                       k.max =  k.max,
                                                       nboot = opt$nboot,
                                                       gap_maxSE = list(method= "Tibs2001SEmax", SE.factor = 1) )
                                    clusters=Clustering$cluster
                                }
                            }
                        }else if (nrow(SPLIT_Normalized_counts_Annotated_mean)==1){
                            clusters=c(1)
                            names(clusters)=rownames((SPLIT_Normalized_counts_Annotated_mean))
                        }else if (nrow(SPLIT_Normalized_counts_Annotated_mean)==2){
                            Clustering <- eclust(as.matrix(SPLIT_Normalized_counts_Annotated_mean),stand = F,
                                                       FUNcluster= 'kmeans',
                                                       graph = FALSE,
                                                       k.max = 2,
                                                       nboot = opt$nboot,
                                                       gap_maxSE = list(method= "Tibs2001SEmax", SE.factor = 1) )
                            clusters=Clustering$cluster
                            cat(sprintf("<h4>%s</h4>",'Since only 2 significant genes were detected, the clustering was performed using the kmeans method'))
                            
                        }else{
                            clusters=c()
                        }
                    }else{
                        clusters=rep(1,nrow(SPLIT_Normalized_counts_Annotated_mean) )
                        names(clusters)=rownames((SPLIT_Normalized_counts_Annotated_mean))
                    }
                    
                    if (length(no_var)>0){
                      if (length(clusters)>0){
                        temp=rep(max(clusters)+1,length(no_var) )
                      }else{
                        temp=rep(1,length(no_var) )
                      }
                      names(temp)=no_var
                      clusters=c(clusters,temp)
                    }

                    if ((opt$hc_metric=='spearman') | ((opt$hc_metric=='pearson') )){
                      hc_metric='correlation'
                    }else{
                      hc_metric=opt$hc_metric
                    }
                    
                    
                    New_clusters=c()
                    for (num in sort(unique(clusters))){
                        res_red=unique(names(clusters))
                        Genes=res_red[res_red  %in% names(clusters[clusters %in% num])]
                        if (length(Genes)>1){
                            if (opt$stand){
                                heat_map=pheatmap(mat = as.matrix(Heatmap_Normalized_counts_Annotated_mean[Genes,]),
                                                cluster_rows = T,show_rownames=F,
                                                clustering_distance_rows = hc_metric ,
                                                clustering_method=opt$hc_method,
                                                cluster_cols = F,silent = T,scale = "row")
                            }else{
                                heat_map=pheatmap(mat = as.matrix(Heatmap_Normalized_counts_Annotated_mean[Genes,]),
                                                cluster_rows = T,show_rownames=F,
                                                clustering_distance_rows = hc_metric ,
                                                clustering_method=opt$hc_method,
                                                cluster_cols = F,silent = T)
                            }
                            New_clusters=c(New_clusters,clusters[heat_map$tree_row$labels[heat_map$tree_row$order]])
                        }else{
                            New_clusters=c(New_clusters,clusters[Genes])
                        }
                    }

                    clusters=New_clusters
                    
                    
                    intgroup=c(opt$GROUP,opt$X_AXIS)
                    intgroup=intgroup[!is.na(intgroup)]
                    clusters_plots = plot_clusters(clusters,SPLIT_Normalized_counts_Annotated,c(GROUP,X_AXIS),c(GROUP,X_AXIS,"Normalized counts"),X_AXIS_ORDER=unique(colData[X_AXIS]))
                    Clustering_Plot = clusters_plots[[1]]
                    ggsave(file.path(opt$outDir,paste('Clusters_',SPLIT,".pdf",sep="")),Clustering_Plot,dpi = 600, width = 6.99, height =3.99, units = "in")
                    cat(sprintf("<h4>%s</h4>",paste('The Next Figure is of the',SPLIT,'Significant Genes Clusters',sep=" ")))
                    grid::grid.newpage()
                    grid::grid.draw(Clustering_Plot)
                    grid::grid.newpage()
                    # Clustering_Plot_plotly = clusters_plots[2]
                    # main_plot_list[main_figure_count] <- list(Clustering_Plot_plotly)
                    # main_figure_count = main_figure_count + 1


                    genes=sig.genes
                    for (Heatmap_Type in c('Mean','Raw')){
                    
                        if (Heatmap_Type=='Mean'){
                            mat = as.matrix(Heatmap_Normalized_counts_Annotated_mean[genes,])
                        }else{
                            mat = apply(X =Heatmap_Normalized_counts_Annotated[genes,] ,MARGIN = c(1,2),FUN = as.numeric)
                            
                            New_clusters=c()
                            for (num in sort(unique(clusters))){
                                res_red=unique(names(clusters))
                                Genes=res_red[res_red  %in% names(clusters[clusters %in% num])]
                                if (length(Genes)>1){
                                    if (opt$stand){
                                        heat_map=pheatmap(mat = mat[Genes,],
                                                        cluster_rows = T,show_rownames=F,
                                                        clustering_distance_rows = hc_metric ,
                                                        clustering_method=opt$hc_method,
                                                        cluster_cols = F,silent = T,scale = "row")
                                    }else{
                                        heat_map=pheatmap(mat = mat[Genes,],
                                                        cluster_rows = T,show_rownames=F,
                                                        clustering_distance_rows = hc_metric ,
                                                        clustering_method=opt$hc_method,
                                                        cluster_cols = F,silent = T)
                                    }
                                    New_clusters=c(New_clusters,clusters[heat_map$tree_row$labels[heat_map$tree_row$order]])
                                }
                            }

                            clusters=New_clusters

                            
                        }
                        mat=mat[names(clusters),]
                        
                        write.table(mat,
                                    file = file.path(opt$outDir,paste('Significant_Genes_',Heatmap_Type,opt$NORMALIZATION_TYPE,'Normalized_counts.txt', sep = '_')) ,
                                    quote = F,
                                    sep = "\t")
                        
                        
                        
                        if (X_AXIS!=GROUP){
                            split=sapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[1])
                            #colnames(split)='split'

                            annotation_col=data.frame(row.names =colnames(mat) ,
                                                    X_AXIS=sapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[2] ),
                                                    GROUP=sapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[1]) )
                            colnames(annotation_col)=c(X_AXIS,GROUP)
                            annotation_col[X_AXIS]  <- factor(annotation_col[,X_AXIS] ,levels=intersect(unique(colData[,X_AXIS]),unique(annotation_col[,X_AXIS]) ))
                            annotation_col[GROUP]   <- factor(annotation_col[,GROUP] ,levels=intersect(unique(colData[,GROUP]),unique(annotation_col[,GROUP]) ))
                            new_order = order(annotation_col[,GROUP],annotation_col[,X_AXIS])
                            annotation_col = annotation_col[new_order,,drop=FALSE]
                            mat = mat[,new_order,drop=FALSE]

                            heat_map=pheatmap(mat =mat ,
                                            cluster_rows= F,show_rownames=F,
                                            cluster_cols=F,scale = "row",
                                            annotation_row=data.frame("Clusters"=factor(clusters) ),
                                            #annotation_names_row=F,
                                            border_color=NA,
                                            silent = T,
                                            annotation_col=annotation_col ,
                                            show_colnames = T,
                                            gaps_row = cumsum(aggregate.data.frame(x = as.data.frame(clusters),by =list(clusters),FUN = length )[,"clusters"] ),
                                            gaps_col = c(cumsum(rev(aggregate.data.frame(x = annotation_col[X_AXIS],by =annotation_col[c(X_AXIS,GROUP)],FUN = length))[,1]),
                                                         rep(cumsum(rev(aggregate.data.frame(x = annotation_col[GROUP],by =annotation_col[c(GROUP)],FUN = length))[,1]),2)
                                                         )
                                            
                            )
                        
                        
                        }else{
                            annotation_col=data.frame(row.names =colnames(mat) ,
                                                    X_AXIS=sapply(X =colnames(mat),FUN = function(x) unlist(strsplit(x =x,split = " "))[1] ))
                            colnames(annotation_col)=c(X_AXIS)
                            annotation_col[X_AXIS]  <- factor(annotation_col[,X_AXIS] ,levels=intersect(unique(colData[,X_AXIS]),unique(annotation_col[,X_AXIS]) ))
                            new_order = order(annotation_col[,X_AXIS])
                            annotation_col = annotation_col[new_order,,drop=FALSE]
                            mat = mat[,new_order,drop=FALSE]
                            if (opt$stand){
                                heat_map=pheatmap(mat = mat ,
                                                  cluster_rows= F,show_rownames=F,
                                                  cluster_cols=F,scale = "row",
                                                  silent = T,
                                                  annotation_row=data.frame("Clusters"=factor(clusters) ),
                                                  #annotation_names_row=T,
                                                  annotation_col=annotation_col,
                                                  show_colnames = T,
                                                  gaps_row = cumsum(aggregate.data.frame(x = as.data.frame(clusters),by =list(clusters),FUN = length )[,"clusters"] ),
                                                  gaps_col = cumsum(aggregate.data.frame(x = annotation_col[X_AXIS],by =annotation_col[X_AXIS],FUN = length)[,-1]),
                                                  border_color=NA
                                )
                            }else{
                                heat_map=pheatmap(mat =mat ,
                                                  cluster_rows= F,show_rownames=F,
                                                  cluster_cols=F,
                                                  silent = T,
                                                  annotation_row=data.frame("Clusters"=factor(clusters) ),
                                                  #annotation_names_row=T,
                                                  annotation_col=annotation_col,
                                                  show_colnames = T,
                                                  gaps_row = cumsum(aggregate.data.frame(x = as.data.frame(clusters),by =list(clusters),FUN = length )[,"clusters"] ),
                                                  gaps_col = cumsum(aggregate.data.frame(x = annotation_col[X_AXIS],by =annotation_col[X_AXIS],FUN = length)[,-1]),
                                                  border_color=NA
                                )
                            }
                        }
                        
                        if (Heatmap_Type=='Raw'){
                            cat(sprintf("<h4>%s</h4>",paste('The Next Figure is of the', SPLIT ,'Significant Genes relative expression Clustered and plotted as a HeatMap',sep=" ")))
                            grid::grid.newpage()
                            grid::grid.draw(heat_map$gtable)
                            grid::grid.newpage()
                        }else{
                            cat(sprintf("<h4>%s</h4>",paste('The Next Figure is of the', SPLIT ,'Significant Genes relative expression [Mean over biological replicates] Clustered and plotted as a HeatMap',sep=" ")))
                            grid::grid.newpage()
                            grid::grid.draw(heat_map$gtable)
                            grid::grid.newpage()
                        }
                        ggsave(file.path(opt$outDir,paste('Clustering_heatmap_',SPLIT,'_',Heatmap_Type,".pdf",sep="")),heat_map$gtable,dpi = 600, width = 15, height = 15, units = "cm",scale = 1.5)

                        mat2=t(scale(t(mat)))
                        mat3=cbind(clusters[rownames(mat2)],mat2)
                        if (!is.na(DESeqDataSet_Results)){
                            mat3=cbind(mat3,DESeqDataSet_Results_redOrdered[rownames(mat3),c('log2FoldChange',"padj")])
                        }
                        if (!is.na(Annotation)) {
                          mat3=merge.data.frame(mat3,Annotation,by="row.names",all.x = T,sort = F)
                          rownames(mat3)=mat3$Row.names
                          mat3$Row.names=NULL
                        }
                        colnames(mat3)[colnames(mat3)=="V1"]="Clusters"
                        colnames(mat3)[colnames(mat3)==""]="Clusters"
                        # col_names=colnames(mat3)
                        # col_names[col_names=="V1"]="Clusters"
                        # colnames(mat3)=col_names
                        mat3=mat3[rownames(mat2),]
                        write.csv(x = mat3,
                                  file = file.path(opt$outDir, paste('Clustering_heatmap_',SPLIT,'_',Heatmap_Type,".csv",sep="") ),
                                  quote = TRUE,
                                  row.names = TRUE)
                                  
                        
                        
                        
                        HeatMap_table  =  datatable(mat3,
                                                    caption = htmltools::tags$caption(style = 'caption-side: bottom; text-align: center;',
                                                                                            'Table: ', 
                                                                                            htmltools::em(paste('This Table is of the ',SPLIT,'Significant Genes Clusterd [as in the HeatMap Figure] and Annotated',sep=""))
                                                                                    ),
                                                    options = list(keys = TRUE ,
                                                                 scrollX = TRUE,
                                                                 fixedHeader = FALSE,
                                                                 fixedColumns = TRUE,
                                                                 pageLength = 5,
                                                                 scrollY = 300,
                                                                 orderClasses=TRUE,
                                                                 autoWidth = TRUE,
                                                                 scroller = TRUE,
                                                                 dom = 'Bfrtip',
                                                                 buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                                                                 deferRender = TRUE),
                                                    class = 'cell-border stripe',
                                                    filter = 'top',
                                                    extensions = c('Buttons','FixedColumns','FixedHeader','KeyTable','Scroller'))
                        main_plot_list <- c(main_plot_list ,list(HeatMap_table) )
                        
                        
                    }



                    ##################Clustering-End##################################    

                    ##################GO/KEGG STAR####################################
                    # Go Enrichment:
                    #cat(sprintf("<h2>%s</h2>", 'Enrichment Analysis:'))
                    
                    main_plot_list <- c(main_plot_list ,list(htmltools::h2('Enrichment Analysis:')) )
                    if (Annotation_flag == 'OrgDb'){
                        gene2entrez = bitr(names(clusters), fromType=opt$GENE_ID_TYPE, toType=c("ENTREZID"), OrgDb=opt$Annotation_db)
                        gene2entrez = gene2entrez[!duplicated(gene2entrez[opt$GENE_ID_TYPE]),]
                        gene2entrez$CLUSTERS=sapply(X =gene2entrez[opt$GENE_ID_TYPE],FUN = function(x)  unlist(clusters[x]))

                        clusters_for_GO= gene2entrez$CLUSTERS
                        names(clusters_for_GO)=gene2entrez$ENTREZID

                        allRes <- clusters_enricher(opt$outDir,clusters_for_GO,"GO",opt$Annotation_db,Annotation$ENTREZID,"ENTREZID",paste('GO_Biological_Process_Enrichment_of_Clusters',SPLIT,sep="_"))
                        main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                        if (opt$Enriched_terms_overlap){
                          heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'GO_Biological_Process_Enrichment_of_Clusters')
                          main_plot_list <- c(main_plot_list ,list(heatmaps))
                        }
 
                            if (((length(down_reg)>0) || (length(up_reg)>0)) && (is.na(opt$LRT))){
                                up_down_clusters = clusters
                                if (length(down_reg)>0){
                                    up_down_clusters[down_reg]='Down'
                                }
                                if (length(up_reg)>0){
                                    up_down_clusters[up_reg]='UP'
                                }

                                allRes <- clusters_enricher(opt$outDir,up_down_clusters,"GO",opt$Annotation_db,Annotation$ENTREZID,"ENTREZID",paste('GO_Biological_Process_Enrichment_of_Up_and_Down_Clusters',SPLIT,sep="_"))
                                main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                                if (opt$Enriched_terms_overlap){
                                  heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'GO_Biological_Process_Enrichment_of_Up_and_Down_Clusters')
                                  main_plot_list <- c(main_plot_list ,list(heatmaps))
                                }

                            }
 
                        One_cluster=clusters_for_GO
                        One_cluster[]=1
                        allRes <- clusters_enricher(opt$outDir,One_cluster,"GO",opt$Annotation_db,Annotation$ENTREZID,"ENTREZID",paste('GO_Biological_Process_Enrichment_of_All_Significant_Genes',SPLIT,sep="_"))
                        main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                        if (opt$Enriched_terms_overlap){
                          heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'GO_Biological_Process_Enrichment_of_All_Significant_Genes')
                          main_plot_list <- c(main_plot_list ,list(heatmaps))
                        }
                        
                        
                    }else{
                        if (GO_flag){
                            allRes <- Clusters_Enrichment_Test(opt$outDir,clusters,GO2name_BP,GO2gene_BP,paste('GO_Biological_Process_Enrichment_of_Clusters',SPLIT,sep="_"),"GO",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'GO_Biological_Process_Enrichment_of_Clusters')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }
 
                            if (((length(down_reg)>0) || (length(up_reg)>0)) && (is.na(opt$LRT))){
                                up_down_clusters = clusters
                                if (length(down_reg)>0){
                                    up_down_clusters[down_reg]='Down'
                                }
                                if (length(up_reg)>0){
                                    up_down_clusters[up_reg]='UP'
                                }

                                allRes <- Clusters_Enrichment_Test(opt$outDir,up_down_clusters,GO2name_BP,GO2gene_BP,paste('GO_Biological_Process_Enrichment_of_Up_and_Down_Clusters',SPLIT,sep="_"),"GO",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                                main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                                if (opt$Enriched_terms_overlap){
                                    heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'GO_Biological_Process_Enrichment_of_Up_and_Down_Clusters')
                                    main_plot_list <- c(main_plot_list ,list(heatmaps))
                                }

                            }
 
                            One_cluster=clusters
                            One_cluster[]=1
                            allRes <- Clusters_Enrichment_Test(opt$outDir,One_cluster,GO2name_BP,GO2gene_BP,paste('GO_Biological_Process_Enrichment_of_All_Significant_Genes',SPLIT,sep="_"),"GO",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'GO_Biological_Process_Enrichment_of_All_Significant_Genes')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }
                            
                            
                        }
                    }
                    if (KEGG_flag){
                        allRes <- Clusters_Enrichment_Test(opt$outDir,clusters,Pathway2name,Pathway2gene,paste('KEGG_Enrichment_Analysis_of_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                        main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                        if (opt$Enriched_terms_overlap){
                            heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Clusters')
                            main_plot_list <- c(main_plot_list ,list(heatmaps))
                        }
 
                        if (((length(down_reg)>0) || (length(up_reg)>0)) && (is.na(opt$LRT))){
                            up_down_clusters = clusters
                            if (length(down_reg)>0){
                                up_down_clusters[down_reg]='Down'
                            }
                            if (length(up_reg)>0){
                                up_down_clusters[up_reg]='UP'
                            }

                            allRes <- Clusters_Enrichment_Test(opt$outDir,up_down_clusters,Pathway2name,Pathway2gene,paste('KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }

                        }
 
                        One_cluster=clusters
                        One_cluster[]=1
                        allRes <- Clusters_Enrichment_Test(opt$outDir,One_cluster,Pathway2name,Pathway2gene,paste('KEGG_Enrichment_Analysis_of_All_Significant_Genes',SPLIT,sep="_"),"KEGG",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                        main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                        if (opt$Enriched_terms_overlap){
                            heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_All_Significant_Genes')
                            main_plot_list <- c(main_plot_list ,list(heatmaps))
                        }
                       
                        
                    }
                    if (ORGANISM_KEGG_flag){
                        allRes  <- Clusters_Enrichment_Test(opt$outDir,clusters,ORGANISM_Pathway2name,ORGANISM_Pathway2gene,paste(ORGANISM,'KEGG_Enrichment_Analysis_of_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                        main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                        if (opt$Enriched_terms_overlap){
                            heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Clusters')
                            main_plot_list <- c(main_plot_list ,list(heatmaps))
                        }
 
                        if (((length(down_reg)>0) || (length(up_reg)>0)) && (is.na(opt$LRT))){
                            up_down_clusters = clusters
                            if (length(down_reg)>0){
                                up_down_clusters[down_reg]='Down'
                            }
                            if (length(up_reg)>0){
                                up_down_clusters[up_reg]='UP'
                            }

                            allRes <- Clusters_Enrichment_Test(opt$outDir,up_down_clusters,ORGANISM_Pathway2name,ORGANISM_Pathway2gene,paste(ORGANISM,'KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }

                        }

 
                        One_cluster=clusters
                        One_cluster[]=1
                        allRes <- Clusters_Enrichment_Test(opt$outDir,One_cluster,ORGANISM_Pathway2name,ORGANISM_Pathway2gene,paste(ORGANISM,'KEGG_Enrichment_Analysis_of_All_Significant_Genes',SPLIT,sep="_"),"KEGG",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                        main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                        if (opt$Enriched_terms_overlap){
                            heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_All_Significant_Genes')
                            main_plot_list <- c(main_plot_list ,list(heatmaps))
                        }
                        
                        
                    }
                    if (KEGG_KAAS_flag){
                        allRes <- Clusters_Enrichment_Test(opt$outDir,clusters,KASS_Pathway2name,KASS_Pathway2gene,paste('KEGG_Enrichment_Analysis_of_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                        main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                        if (opt$Enriched_terms_overlap){
                            heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Clusters')
                            main_plot_list <- c(main_plot_list ,list(heatmaps))
                        }
                        
                        
                        if (((length(down_reg)>0) || (length(up_reg)>0)) && (is.na(opt$LRT))){
                            up_down_clusters = clusters
                            if (length(down_reg)>0){
                                up_down_clusters[down_reg]='Down'
                            }
                            if (length(up_reg)>0){
                                up_down_clusters[up_reg]='UP'
                            }

                            allRes <- Clusters_Enrichment_Test(opt$outDir,up_down_clusters,KASS_Pathway2name,KASS_Pathway2gene,paste('KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters',SPLIT,sep="_"),"KEGG",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                            main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                            if (opt$Enriched_terms_overlap){
                                heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_Up_and_Down_Clusters')
                                main_plot_list <- c(main_plot_list ,list(heatmaps))
                            }

                        }

                        One_cluster=clusters
                        One_cluster[]=1
                        allRes <- Clusters_Enrichment_Test(opt$outDir,One_cluster,KASS_Pathway2name,KASS_Pathway2gene,paste('KEGG_Enrichment_Analysis_of_All_Significant_Genes',SPLIT,sep="_"),"KEGG",pAdjustMethod='fdr',pvalueCutoff=0.05,gene2ko=FALSE)
                        main_plot_list <- c(main_plot_list ,list(allRes[[2]]) )
                        if (opt$Enriched_terms_overlap){
                            heatmaps = plot_sheard_genes(allRes[[1]]@compareClusterResult,opt$outDir,'KEGG_Enrichment_Analysis_of_All_Significant_Genes')
                            main_plot_list <- c(main_plot_list ,list(heatmaps))
                        }
                         
                        
                    }        
                    ##################GO/KEGG-End####################################    
                
                }
                
            htmltools::tagList(list(c(main_plot_list)))
            }else{
                cat('No significant genes were detected')
            }
        }else{
            cat('The "X_AXIS" parameter must be given for clustering analysis')
        }
 save.image(file.path(opt$outDir,'Session.RSession'))
 colData   = Original_colData   
 countData = Original_countData 

```